### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by vraho10** [Lunatrius/Schematica#105]
Don't know if this has been answered or not but I need help!

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/19/15 2:37 AM
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.client.renderer.WorldRenderer.func_178970_b()V
	at com.github.lunatrius.schematica.client.gui.GuiHelper.drawItemStackSlot(GuiHelper.java:35)
	at com.github.lunatrius.schematica.client.gui.GuiHelper.drawItemStack(GuiHelper.java:19)
	at com.github.lunatrius.schematica.client.gui.GuiSchematicLoadSlot.func_180791_a(GuiSchematicLoadSlot.java:63)
	at net.minecraft.client.gui.GuiSlot.func_148120_b(GuiSlot.java:420)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:194)
	at com.github.lunatrius.schematica.client.gui.GuiSchematicLoad.func_73863_a(GuiSchematicLoad.java:96)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:307)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1103)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.client.gui.GuiHelper.drawItemStackSlot(GuiHelper.java:35)
	at com.github.lunatrius.schematica.client.gui.GuiHelper.drawItemStack(GuiHelper.java:19)
	at com.github.lunatrius.schematica.client.gui.GuiSchematicLoadSlot.func_180791_a(GuiSchematicLoadSlot.java:63)
	at net.minecraft.client.gui.GuiSlot.func_148120_b(GuiSlot.java:420)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:194)
	at com.github.lunatrius.schematica.client.gui.GuiSchematicLoad.func_73863_a(GuiSchematicLoad.java:96)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:307)

-- Screen render details --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.GuiSchematicLoad
	Mouse location: Scaled: (194, 62). Absolute: (583, 653)
	Screen size: Scaled: (532, 280). Absolute: (1595, 840). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['VaughnH'/65100939, l='MpServer', x=510.49, y=68.00, z=11836.38]]
	Chunk stats: MultiplayerChunkCache: 82, 82
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 500.00,62.00,11947.00 - World: (500,62,11947), Chunk: (at 4,3,11 in 31,746; contains blocks 496,0,11936 to 511,255,11951), Region: (0,23; contains chunks 0,736 to 31,767, blocks 0,0,11776 to 511,255,12287)
	Level time: 1176100719 game time, 1178310075 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['VaughnH'/65100939, l='MpServer', x=510.49, y=68.00, z=11836.38]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1091) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 280373752 bytes (267 MB) / 562581504 bytes (536 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.18 Powered by Forge 11.15.0.1596 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.8-11.15.0.1596-1.8.8.jar) 
	UCHIJA	Forge{11.15.0.1596} [Minecraft Forge] (forge-1.8.8-11.15.0.1596-1.8.8.jar) 
	UCHIJA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.8.jar) 
	UCHIJA	Schematica{1.7.5.112} [Schematica] (Schematica-Mod-1.8.jar) 
	Loaded coremods (and transformers): 
	Launched Version: 1.8.8-forge1.8.8-11.15.0.1596-1.8.8
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce 9400 OpenGL Engine GL version 2.1 NVIDIA-10.0.35 310.90.10.05b12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: KiLO.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8135 @ 2.66GHz
```

**Comment by Lunatrius** [comment]
1. The 1.8 builds are not compatible with 1.8.8.
2. You are using a severely outdated version of LunatriusCore/Schematica.
3. I'm currently finishing the 1.8.8 updates, the new builds should be available soon (no ETA, but the mods **run** in-dev, need a few fixes here and there).
