### ISSUE TITLE
Crash using Version 1.8-1.7.7.140-universal

### ISSUE THREAD

**Issue by smb64** [Lunatrius/Schematica#111]
Crashes within moments of placing water via a bucket.
Minecraft Crash Report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 1/23/16 2:13 PM
Description: Tesselating block in world

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
	at net.minecraft.block.BlockLiquid.func_180687_h(SourceFile:164)
	at net.minecraft.block.BlockLiquid.func_180689_a(SourceFile:259)
	at net.minecraft.client.renderer.BlockFluidRenderer.func_178270_a(BlockFluidRenderer.java:90)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:260)
	at com.github.lunatrius.schematica.client.renderer.chunk.proxy.SchematicRenderChunkList.func_178581_b(SchematicRenderChunkList.java:46)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
	at net.minecraft.block.BlockLiquid.func_180687_h(SourceFile:164)
	at net.minecraft.block.BlockLiquid.func_180689_a(SourceFile:259)
	at net.minecraft.client.renderer.BlockFluidRenderer.func_178270_a(BlockFluidRenderer.java:90)

-- Block being tesselated --
Details:
	Block type: ID #9 (tile.water // net.minecraft.block.BlockStaticLiquid)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (46,5,4), Chunk: (at 14,0,4 in 2,0; contains blocks 32,0,0 to 47,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:260)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['smb64'/195, l='MpServer', x=260.54, y=58.06, z=-10.74]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -216.00,64.00,216.00 - World: (-216,64,216), Chunk: (at 8,4,8 in -14,13; contains blocks -224,0,208 to -209,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1548824 game time, 1228 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['smb64'/195, l='MpServer', x=260.54, y=58.06, z=-10.74]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:407)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 177323368 bytes (169 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: Minecraft 1.8 MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 Optifine OptiFine_1.8_HD_U_G7 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	ForgeEssentials{1.8.3} [Forge Essentials] (forgeessentials-1.8-1.8.3.54-server.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.30} [LunatriusCore] (LunatriusCore-1.8-1.1.2.30-universal.jar) 
	UCHIJAAAA	moreplayermodels{1.8.0_beta} [MorePlayerModels] (MorePlayerModels_1.8.0 (1).jar) 
	UCHIJAAAA	Schematica{1.7.7.140} [Schematica] (Schematica-1.8-1.7.7.140-universal.jar) 
	UCHIJAAAA	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.8-6.1.1-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
	ForgeEssentials: Running ForgeEssentials 1.8.3.54 (4140a85). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Launched Version: 1.8-forge1.8-11.14.4.1577
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Lunatrius** [comment]
I assume you tried to place the water block in the same position where a water block was present in the schematic? I'll take a look into it.

Side note, 1.8 is no longer supported and the fix will be only available for 1.8.9 (if a fix is required at all).

**Comment by smb64** [comment]
yes, while building an enderman xp grinder in the end.
also here is the schematic I was using (uploaded in zip format due to the github's restriction) incase you want to test it, seems to crash somewhere around the grinding room
[xp grinder.zip](https://github.com/Lunatrius/Schematica/files/102150/xp.grinder.zip)

**Comment by Lunatrius** [comment]
Tried to reproduce it, but was unable to do so. Could you test the following things:
 * is it reproducible in a new world (superflat overworld and/or the end)?
 * does it work if you remove ForgeEssentials, moreplayermodels and worldedit?
 * can you reproduce it with the 1.8.9 version?

If you'll use your SP world for testing, make sure you have a backup handy if you plan to continue using 1.8 after you'll be done testing.

**Comment by Lunatrius** [comment]
Closing this due to lack of feedback - if it still happens feel free to re-open.
