### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by TechnologicApe** [Lunatrius/Schematica#115]
I've noticed some blocks don't get saved properly to a schematics file. Blocks like JABBA Barrels and Refined Relocation's Pipes, they get saved as bedrock.

**Comment by Lunatrius** [comment]
That usually happens when a TileEntity can't be saved on the client side. The log file should contain more information why exactly it fails.

**Comment by TechnologicApe** [comment]
Is there a way to fix it?

**Comment by TechnologicApe** [comment]
I read the log,but I don't understand why it wasn't working.

**Comment by Lunatrius** [comment]
You don't have to understand the log, I just need the stacktrace from the log. Try to save a schematic, the stacktrace will be in the last 100 lines of the log file.

**Comment by TechnologicApe** [comment]
http://pastebin.com/sudiY2fr

**Comment by Lunatrius** [comment]
Looks like JABBA barrels can't be saved client side. Could you try `/schematicaSave` if it's a SP world?

**Comment by TechnologicApe** [comment]
Doesn't seem to be working. I've tried: 
/schematicaSave <X Y Z> <X Y Z>
/schematicaSave <X> <Y> <Z> <X> <Y> <Z>
/schematicaSave X Y Z X Y Z
Am I missing Something?

**Comment by TechnologicApe** [comment]
there's supposed to be XYZ in the top two iterations

**Comment by Lunatrius** [comment]
Typing `/schematicaSave` will bring up the help text: `/schematicaSave <x> <y> <z> <x> <y> <z> <filename>`

**Comment by TechnologicApe** [comment]
OK, I just tried it, it still loads barrels as Bedrock.

**Comment by Lunatrius** [comment]
In that case there is not much I can do about. It's crashing in JABBA's `writeToNBT` method which is what vanilla Minecraft uses to save blocks and tile entities into NBT.
```
java.lang.NullPointerException
 >  at mcp.mobius.betterbarrels.common.blocks.TileEntityBarrel.writeToNBT(TileEntityBarrel.java:465) ~[TileEntityBarrel.class:?]
    at com.github.lunatrius.schematica.nbt.NBTHelper.writeTileEntityToCompound(NBTHelper.java:145) ~[NBTHelper.class:?]
    at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.writeToNBT(SchematicAlpha.java:142) [SchematicAlpha.class:?]
    ...
```

**Comment by TechnologicApe** [comment]
OK. I'll see what they say over at JABBA

**Comment by Lunatrius** [comment]
Was there any comment from ProfMobious' side? Because it seems weird that the saving breaks when saving to a schematic but not to the save file even though the same method is used.

**Comment by TechnologicApe** [comment]
I couldn't find a way to contact them. I never found their Github. However I tried to save a schematic with Refined Relocation and the pipes didn't even save, not even replaced, just didn't save the blocks. The other blocks but not Refined Relocation's

**Comment by Lunatrius** [comment]
Pretty sure JABBA is on Bitbucket. Most of the times tile entities fail to save because they depend on something that is not standard *or* possibly because I forgot to toggle/enable/set something. In JABBA's case I'm not really sure why it happens.

**Comment by TechnologicApe** [comment]
I've since removed JABBA and replaced it the Storage Drawers, which works, but refined relocation doesn't.
