### ISSUE TITLE
NoSuchMethodError: FMLControlledNamespacedRegistry

### ISSUE THREAD

**Issue by Skittlewink** [Lunatrius/Schematica#119]
READ THIS
---
Your game will crash with `java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry` if you use Forge 1817 or newer. To avoid this please **use Forge 1816 or earlier**. The long story short, Forge 1.9 is rapidly changing things and I don't feel like pushing out *recompiles* for stuff that works in older versions.

*Having multiple, recompiled version would increase the amount of crashes due to an invalid Forge version - it's just easier this way.* Once we get 1.9.3 things should hopefully be stable again.
-- @Lunatrius

---

```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 4/3/16 12:57 AM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getObject(Lnet/minecraft/util/ResourceLocation;)Ljava/lang/Object;
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['Skittlewink'/363, l='MpServer', x=346.60, y=36.71, z=-128.61], EntityOtherPlayerMP['BaccaOrigin'/85, l='MpServer', x=295.35, y=9.75, z=-64.28], EntityOtherPlayerMP['Carlll'/67, l='MpServer', x=346.33, y=6.95, z=-52.80]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (413,4,-132), Chunk: (at 13,0,12 in 25,-9; contains blocks 400,0,-144 to 415,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 214907 game time, 22717 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 13 total; [EntityPlayerSP['Skittlewink'/363, l='MpServer', x=346.60, y=36.71, z=-128.61], EntitySheep['Sheep'/32, l='MpServer', x=328.56, y=4.00, z=-158.75], EntitySheep['Sheep'/2, l='MpServer', x=271.29, y=4.00, z=-137.63], EntityOtherPlayerMP['Carlll'/67, l='MpServer', x=346.33, y=6.95, z=-52.80], EntityOtherPlayerMP['BaccaOrigin'/85, l='MpServer', x=295.35, y=9.75, z=-64.28], EntityOtherPlayerMP['Carlll'/67, l='MpServer', x=346.33, y=6.95, z=-52.80], EntityItem['item.item.egg'/361, l='MpServer', x=409.58, y=4.00, z=-182.72], EntityChicken['Chicken'/11, l='MpServer', x=410.45, y=4.00, z=-195.18], EntityPig['Pig'/12, l='MpServer', x=311.29, y=4.00, z=-167.43], EntityPig['Pig'/13, l='MpServer', x=348.65, y=4.00, z=-187.27], EntityOtherPlayerMP['BaccaOrigin'/85, l='MpServer', x=295.35, y=9.75, z=-64.28], EntityCow['Cow'/22, l='MpServer', x=398.71, y=4.00, z=-83.79], EntityCow['Cow'/31, l='MpServer', x=346.45, y=4.00, z=-65.17]]
	Retry entities: 0 total; []
	Server brand: CraftBukkit
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 142148552 bytes (135 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1826 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1826-1.9.jar) 
	UCHIJA	Forge{12.16.0.1826} [Minecraft Forge] (forge-1.9-12.16.0.1826-1.9.jar) 
	UCHIJA	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCHIJA	Schematica{1.7.7.144} [Schematica] (Schematica-1.9-1.7.7.144-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: 1.9-forge1.9-12.16.0.1826-1.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4331, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz
```

**Comment by Lunatrius** [comment]
Similar to Lunatrius/Stackie#7, most likely required a recompile. Given how unstable Forge currently is (unstable as in 'things are changing') I'd suggest to revert back to Forge 1816 for the time being.

**Comment by Lunatrius** [comment]
Fixed in `1.7.7.145`.

**Comment by HOTSHOT2001** [comment]
i crash every time i try and load a schematic here is the crash:
http://pastebin.com/stKnY3Kj

**Comment by Lunatrius** [comment]
```
java.lang.ClassCastException: com.github.lunatrius.schematica.client.world.chunk.ChunkProviderSchematic cannot be cast to net.minecraft.client.multiplayer.ChunkProviderClient
    at net.minecraft.client.multiplayer.WorldClient.func_72863_F(WorldClient.java:502)
    at net.minecraft.client.multiplayer.WorldClient.func_72863_F(WorldClient.java:47)
    at net.malisis.core.util.chunkblock.ChunkBlockHandler.getAffectedChunks(ChunkBlockHandler.java:338)
    at net.malisis.core.util.chunkcollision.ChunkCollision.getRayTraceResult(ChunkCollision.java:132) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    at net.minecraft.world.World.func_147447_a(World.java:885)
    at com.github.lunatrius.schematica.handler.client.RenderTickHandler.rayTrace(RenderTickHandler.java:50)
    at com.github.lunatrius.schematica.handler.client.RenderTickHandler.onRenderTick(RenderTickHandler.java:23)
```

malisis core(?) is doing something it shouldn't be doing. I'd suggest reporting this to the author of that mod.

**Comment by ferdavs98** [comment]
When teleported to the twilight forest, the Minecraft crashes out. Or when I create a flat world
then Delete the mod:     dungeonmobs!!!

**Comment by Lunatrius** [comment]
You did not supply a crash report. Also, please do not use random issues for such comments, either use the MCF forum thread or create a new issue if you can supply enough information.
