### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ChawHD** [Lunatrius/Schematica#120]
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 06/04/16 01:41
Description: Batching chunks

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:141)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)
	at com.github.lunatrius.schematica.client.renderer.chunk.overlay.RenderOverlay.func_178581_b(RenderOverlay.java:157)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:141)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)

-- Affected level --
Details:
	Level name: MpServer
	All players: 8 total; [EntityPlayerSP['Chaw'/178681, l='MpServer', x=-3214.19, y=102.00, z=-1855.15], EntityOtherPlayerMP['Josh3738'/11813, l='MpServer', x=-3257.63, y=68.63, z=-1857.09], EntityOtherPlayerMP['Yank33'/8272, l='MpServer', x=-3270.18, y=108.28, z=-1848.07], EntityOtherPlayerMP['arockstar28'/8118, l='MpServer', x=-3220.50, y=59.59, z=-1838.91], EntityOtherPlayerMP['CynicalKing'/115661, l='MpServer', x=-3244.75, y=28.63, z=-1854.62], EntityOtherPlayerMP['ryno2'/10998, l='MpServer', x=-3211.56, y=112.78, z=-1897.91], EntityOtherPlayerMP['Pepto_Bismol_'/126001, l='MpServer', x=-3227.28, y=134.53, z=-1885.16], EntityOtherPlayerMP['joenaj'/10317, l='MpServer', x=-3207.04, y=22.23, z=-1861.75]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 1706.00,62.00,-1352.00 - World: (1706,62,-1352), Chunk: (at 10,3,8 in 106,-85; contains blocks 1696,0,-1360 to 1711,255,-1345), Region: (3,-3; contains chunks 96,-96 to 127,-65, blocks 1536,0,-1536 to 2047,255,-1025)
	Level time: 523726086 game time, 184335434 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntityPlayerSP['Chaw'/178681, l='MpServer', x=-3214.19, y=102.00, z=-1855.15], EntityOtherPlayerMP['Josh3738'/11813, l='MpServer', x=-3257.63, y=68.63, z=-1857.09], EntityOtherPlayerMP['Yank33'/8272, l='MpServer', x=-3270.18, y=108.28, z=-1848.07], EntityOtherPlayerMP['arockstar28'/8118, l='MpServer', x=-3220.50, y=59.59, z=-1838.91], EntityOtherPlayerMP['CynicalKing'/115661, l='MpServer', x=-3244.75, y=28.63, z=-1854.62], EntityOtherPlayerMP['Josh3738'/11813, l='MpServer', x=-3257.63, y=68.63, z=-1857.09], EntityOtherPlayerMP['ryno2'/10998, l='MpServer', x=-3211.56, y=112.78, z=-1897.91], EntityOtherPlayerMP['Pepto_Bismol_'/126001, l='MpServer', x=-3227.28, y=134.53, z=-1885.16], EntityOtherPlayerMP['joenaj'/10317, l='MpServer', x=-3195.16, y=16.97, z=-1874.40], EntityOtherPlayerMP['CynicalKing'/115661, l='MpServer', x=-3244.75, y=28.63, z=-1854.62], EntityArmorStand['Armor Stand'/2253, l='MpServer', x=-3226.50, y=184.00, z=-1808.50], EntityOtherPlayerMP['joenaj'/10317, l='MpServer', x=-3207.04, y=22.23, z=-1861.75], EntityOtherPlayerMP['joenaj'/10317, l='MpServer', x=-3207.04, y=22.23, z=-1861.75], EntityArmorStand['Armor Stand'/2254, l='MpServer', x=-3225.50, y=184.00, z=-1809.50], EntityOtherPlayerMP['Wrynn'/7804, l='MpServer', x=-3218.72, y=108.34, z=-1907.91], EntityOtherPlayerMP['Yank33'/8272, l='MpServer', x=-3270.18, y=108.28, z=-1848.07], EntityOtherPlayerMP['Pepto_Bismol_'/126001, l='MpServer', x=-3227.28, y=134.53, z=-1885.16], EntityOtherPlayerMP['Ziko'/20283, l='MpServer', x=-3285.03, y=119.22, z=-1852.03], EntityOtherPlayerMP['KBR'/8231, l='MpServer', x=-3282.50, y=117.00, z=-1823.50], EntityOtherPlayerMP['arockstar28'/8118, l='MpServer', x=-3220.50, y=59.59, z=-1838.91], EntityOtherPlayerMP['ryno2'/10998, l='MpServer', x=-3211.56, y=112.78, z=-1897.91]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 272116384 bytes (259 MB) / 665067520 bytes (634 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJA	Schematica{1.7.7.142} [Schematica] (Schematica-Mod-1.8.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §a§lNoBoomss §fInFinite 16x Edit§a§l[V1].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
```

**Comment by Lunatrius** [comment]
Try tweaking graphical settings, lower the schematic and/or Minecraft render distance, try turning VBOs on and off.

It also appears that you're not running Minecraft on a dedicated graphics card, could you verify that on the F3 menu? It should say either NVIDIA, AMD/ATI or Intel for the graphics card.

**Comment by ChawHD** [comment]
Ok, i'll do that. Thanks for help.

**Comment by ChawHD** [comment]
I do seem to be using a dedicated graphics card: https://gyazo.com/7c71ce96951db32aaaef49ba4eb07dd8

**Comment by ChawHD** [comment]
It still crashes no matter what I do.. I've changed VBOs, schematic render distance and mc render distance.

**Comment by Lunatrius** [comment]
Are you trying to move the schematic underground? If that is the case, update to `1.7.7.143`.

**Comment by ChawHD** [comment]
I am, thank you.

**Comment by Lunatrius** [comment]
Did that fix it?

**Comment by Lunatrius** [comment]
I assume that fixed it. Closing this, feel free to re-open if it didn't.

**Comment by YForYoshi** [comment]
i have the exact same problem and reducing graphics and turning off the VBO and more wont work,and I don't know how to fix it.
