### ISSUE TITLE
game crash?

### ISSUE THREAD

**Issue by newielander** [Lunatrius/Schematica#125]
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10-4-16 18:38
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getObject(Lnet/minecraft/util/ResourceLocation;)Ljava/lang/Object;
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['newlander007'/0, l='MpServer', x=-42,03, y=106,90, z=-47,69]]
	Chunk stats: MultiplayerChunkCache: 1156, 1156
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-36,99,-60), Chunk: (at 12,6,4 in -3,-4; contains blocks -48,0,-64 to -33,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 720293 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['newlander007'/0, l='MpServer', x=-42,03, y=106,90, z=-47,69]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 347822760 bytes (331 MB) / 714461184 bytes (681 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1863 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1863-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1863} [Minecraft Forge] (forge-1.9-12.16.0.1863-1.9.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.144} [Schematica] (Schematica-1.9-1.7.7.144-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.0' Renderer: 'AMD Radeon R9 200 Series'
	Launched Version: 1.9-forge1.9-12.16.0.1863-1.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: CodeCrafted Custom 1_9.zip
	Current Language: LOLCAT (Kingdom of Cats)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
```

**Comment by Lunatrius** [comment]
#119 

Long story short: **use Forge 1816 or earlier**. Check the top of the above issue for more details.
