### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tsqa** [Lunatrius/Schematica#127]
```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 4/12/16 6:25 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getObject(Lnet/minecraft/util/ResourceLocation;)Ljava/lang/Object;
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['B4NK'/68513, l='MpServer', x=2394.30, y=81.00, z=-689.70]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (960,74,295), Chunk: (at 0,4,7 in 60,18; contains blocks 960,0,288 to 975,255,303), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 1204788322 game time, 937638000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['B4NK'/68513, l='MpServer', x=2394.30, y=81.00, z=-689.70]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.9-SNAPSHOT:b6b015f:1142) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 300250160 bytes (286 MB) / 637857792 bytes (608 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.23 Powered by Forge 12.16.0.1859 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1859-1.9.jar) 
	UCHIJA	Forge{12.16.0.1859} [Minecraft Forge] (forge-1.9-12.16.0.1859-1.9.jar) 
	UCHIJA	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCHIJA	Schematica{1.7.7.144} [Schematica] (Schematica-1.9-1.7.7.144-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.9-forge1.9-12.16.0.1859-1.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4331, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
```

**Comment by Lunatrius** [comment]
#119
