### ISSUE TITLE
Crash while loading a schematic

### ISSUE THREAD

**Issue by Fuxxii** [Lunatrius/Schematica#128]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 15.04.16 22:07
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getId(Ljava/lang/Object;)I
	at com.github.lunatrius.schematica.world.storage.Schematic.setBlockState(Schematic.java:63)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.storage.Schematic.setBlockState(Schematic.java:63)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['BlackCanaryDC'/84, l='MpServer', x=-367,17, y=4,00, z=1008,44]]
	Chunk stats: MultiplayerChunkCache: 1024, 1024
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-360,4,1002), Chunk: (at 8,0,10 in -23,62; contains blocks -368,0,992 to -353,255,1007), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 2102 game time, 2102 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntitySlime['Schleim'/67, l='MpServer', x=-310,52, y=4,95, z=1028,34], EntityCow['Kuh'/68, l='MpServer', x=-295,50, y=4,00, z=1034,50], EntitySlime['Schleim'/69, l='MpServer', x=-301,15, y=4,42, z=1058,23], EntitySlime['Schleim'/70, l='MpServer', x=-308,38, y=5,17, z=1060,52], EntitySlime['Schleim'/71, l='MpServer', x=-316,33, y=4,00, z=1078,19], EntitySlime['Schleim'/72, l='MpServer', x=-300,16, y=4,00, z=1080,30], EntitySlime['Schleim'/77, l='MpServer', x=-301,93, y=4,17, z=1053,35], EntitySlime['Schleim'/14, l='MpServer', x=-440,79, y=4,27, z=984,23], EntityPig['Schwein'/15, l='MpServer', x=-438,67, y=4,00, z=999,73], EntitySlime['Schleim'/17, l='MpServer', x=-446,45, y=4,55, z=1035,99], EntityPig['Schwein'/19, l='MpServer', x=-432,36, y=4,00, z=1046,93], EntitySlime['Schleim'/20, l='MpServer', x=-438,94, y=4,27, z=1055,07], EntitySlime['Schleim'/25, l='MpServer', x=-424,43, y=4,00, z=986,88], EntitySlime['Schleim'/26, l='MpServer', x=-434,69, y=4,00, z=1042,91], EntitySheep['Schaf'/27, l='MpServer', x=-424,50, y=4,00, z=1081,50], EntityPlayerSP['BlackCanaryDC'/84, l='MpServer', x=-367,17, y=4,00, z=1008,44], EntityHorse['Esel'/32, l='MpServer', x=-387,66, y=4,00, z=949,79], EntitySlime['Schleim'/33, l='MpServer', x=-396,53, y=4,00, z=968,93], EntitySlime['Schleim'/34, l='MpServer', x=-373,13, y=4,00, z=1007,78], EntitySlime['Schleim'/35, l='MpServer', x=-401,71, y=4,17, z=1048,12], EntitySlime['Schleim'/37, l='MpServer', x=-371,32, y=4,00, z=931,31], EntitySlime['Schleim'/38, l='MpServer', x=-375,29, y=4,42, z=966,70], EntitySlime['Schleim'/39, l='MpServer', x=-375,90, y=4,00, z=1037,01], EntitySlime['Schleim'/40, l='MpServer', x=-375,11, y=4,17, z=1027,61], EntitySlime['Schleim'/43, l='MpServer', x=-366,54, y=4,00, z=954,68], EntitySlime['Schleim'/44, l='MpServer', x=-357,48, y=4,00, z=1063,35], EntitySlime['Schleim'/51, l='MpServer', x=-335,76, y=4,76, z=1048,07], EntitySlime['Schleim'/52, l='MpServer', x=-325,67, y=5,17, z=1082,37], EntitySlime['Schleim'/59, l='MpServer', x=-311,96, y=4,00, z=1086,33], EntitySlime['Schleim'/60, l='MpServer', x=-314,20, y=4,00, z=1079,09], EntitySlime['Schleim'/61, l='MpServer', x=-323,14, y=4,95, z=1072,08], EntitySlime['Schleim'/62, l='MpServer', x=-317,90, y=5,18, z=1080,59], EntitySlime['Schleim'/11327, l='MpServer', x=-427,10, y=4,00, z=929,63]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:453)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 658531856 bytes (628 MB) / 1053102080 bytes (1004 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 Optifine OptiFine_1.9_HD_U_B1 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.144} [Schematica] (Schematica-1.9-1.7.7.144-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0 NVIDIA 344.48' Renderer: 'GeForce GTX 760 (192-bit)/PCIe/SSE2'
	Launched Version: 1.9-forge1.9-12.16.0.1865-1.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 760 (192-bit)/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.9_HD_U_B1
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 NVIDIA 344.48
	OpenGlRenderer: GeForce GTX 760 (192-bit)/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by Fuxxii** [comment]
Me again.
I just found this here
https://github.com/Lunatrius/Schematica/issues/119

I've downgraded my forge version and everything works fine.

Sorry for the inconvenience.

**Comment by Lunatrius** [comment]
It has been fixed and the latest build (145) should work jsut fine with any Forge from 1850+.

**Comment by iStrqfez** [comment]
Hey there, I dont know what u mean can you explane? i do now have the Forge 1.9 and schematica etc. 1.9 pls explane error: The game crashed whilst updating screen events
Error: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getId(Ljava/lang/Object;)I

**Comment by Lunatrius** [comment]
You need to update Forge.
