### ISSUE TITLE
Crashing While saving/ loading in builds

### ISSUE THREAD

**Issue by GalaxyCloud** [Lunatrius/Schematica#130]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 18/04/16 15:41
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getObject(Lnet/minecraft/util/ResourceLocation;)Ljava/lang/Object;
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.schematic.SchematicUtil.getIconFromName(SchematicUtil.java:52)
	at com.github.lunatrius.schematica.proxy.CommonProxy.saveSchematic(CommonProxy.java:188)
	at com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave.func_146284_a(GuiSchematicSave.java:157)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.save.GuiSchematicSave

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['GalaxyCloud'/308, l='MpServer', x=-245.35, y=64.00, z=83.25]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-248,64,144), Chunk: (at 8,4,0 in -16,9; contains blocks -256,0,144 to -241,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 572 game time, 572 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['GalaxyCloud'/308, l='MpServer', x=-245.35, y=64.00, z=83.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 394012032 bytes (375 MB) / 756903936 bytes (721 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.144} [Schematica] (Schematica-1.9-1.7.7.144-universal.jar) 
	Loaded coremods (and transformers): 
	Launched Version: 1.9-forge1.9-12.16.0.1865-1.9
	LWJGL: 2.9.2
	OpenGL: ATI Radeon HD 2600 OpenGL Engine GL version 2.1 ATI-10.0.40, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Xeon(R) CPU E5462 @ 2.80GHz

This is the crash report it gives me whenever i save even a small area or try to load in a building, sorry if I'm being stupid and missing something clear but i am new to this. Thanks

**Comment by RedNesto** [comment]
> UCHIJAAAA LunatriusCore{1.1.2.33} LunatriusCore 
UCHIJAAAA Schematica{1.7.7.144} Schematica 

Update LunatriusCore and Schematica because this version of Schematica has a problem with versions of Forge newer than 1816. (reported in  #119)

**Comment by GalaxyCloud** [comment]
RedNesto, is the updated version of LunatriusCore and Schematica compatible with Mac OS?
Thanks for replying

**Comment by RedNesto** [comment]
There are no reasons Schematica and LunatriusCore updates are incompatible with Mac ^^.

**Comment by GalaxyCloud** [comment]
Okay thank you, lastly, whats the link to the updated schematic and lunatriuscore, I'm hopeless at this kind of stuff!

**Comment by RedNesto** [comment]
Direct download for LunatriusCore: http://minecraft.curseforge.com/projects/lunatriuscore/files/2294062/download
and for Schematica:
http://minecraft.curseforge.com/projects/schematica/files/2294072/download

**Comment by GalaxyCloud** [comment]
I can't thank you enough, you've helped a lot!

**Comment by RedNesto** [comment]
:3

**Comment by RedNesto** [comment]
If it fixes the problem, don't forget to close this issue

**Comment by GalaxyCloud** [comment]
Yes it fixes it! Thanks again
