### ISSUE TITLE
Game crash when trying to load schematic

### ISSUE THREAD

**Issue by Mozos** [Lunatrius/Schematica#137]
I was able to save a schematic, but when I try to load it, my game crash as soon as I click load. I'm using the latest forge version. I really don't know what I'm doing wrong.

Here's my crash log: https://gist.github.com/Mozos/c579eb0158e4a2078108c9ebfb2a871b

Here's my fml-client-latest: https://gist.github.com/Mozos/d7fb6d9c8f670c01cbb89b2d50130371

**Comment by Mozos** [comment]
I just saw another post about removing optifine and it fixed it. Any idea how I could make it work with optifine?

**Comment by Lunatrius** [comment]
This is up to Optifine to "fix" - there is a new Forge patch and Optifine has to account for that.

**Comment by Halle77** [comment]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2017-02-07 19:47
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getId(Ljava/lang/Object;)I
	at com.github.lunatrius.schematica.world.storage.Schematic.setBlockState(Schematic.java:63)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.storage.Schematic.setBlockState(Schematic.java:63)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Halle77'/19, l='MpServer', x=-1285,50, y=4,00, z=-1120,50]]
	Chunk stats: MultiplayerChunkCache: 550, 550
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1280,4,-1112), Chunk: (at 0,0,8 in -80,-70; contains blocks -1280,0,-1120 to -1265,255,-1105), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
	Level time: 270 game time, 270 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 11 total; [EntitySlime['Slime'/16, l='MpServer', x=-1255,05, y=4,09, z=-1083,36], EntitySlime['Slime'/17, l='MpServer', x=-1255,47, y=4,35, z=-1073,69], EntitySlime['Slime'/7, l='MpServer', x=-1356,78, y=4,50, z=-1188,09], EntitySlime['Slime'/8, l='MpServer', x=-1348,35, y=4,44, z=-1045,49], EntityPlayerSP['Halle77'/19, l='MpServer', x=-1285,50, y=4,00, z=-1120,50], EntitySlime['Slime'/9, l='MpServer', x=-1331,42, y=4,00, z=-1190,73], EntitySlime['Slime'/10, l='MpServer', x=-1320,04, y=4,21, z=-1063,35], EntitySlime['Slime'/11, l='MpServer', x=-1315,82, y=4,00, z=-1065,94], EntitySlime['Slime'/12, l='MpServer', x=-1315,38, y=4,35, z=-1063,44], EntitySlime['Slime'/14, l='MpServer', x=-1292,42, y=4,00, z=-1057,36], EntitySlime['Slime'/15, l='MpServer', x=-1275,12, y=4,00, z=-1061,23]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 248152520 bytes (236 MB) / 616677376 bytes (588 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1887 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1887.jar) 
	UCHIJAAAA	Forge{12.16.1.1887} [Minecraft Forge] (forge-1.9-12.16.1.1887.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9.jar) 
	UCHIJAAAA	Schematica{1.7.7.144} [Schematica] (Schematica-Mod-1.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.514' Renderer: 'AMD Radeon R9 200 Series'
	Launched Version: 1.9-forge1.9-12.16.1.1887
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.14008 Compatibility Profile Context 21.19.137.514, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor
