### ISSUE TITLE
Client crashes when loading a schematic in 1.7.7.146

### ISSUE THREAD

**Issue by Epicarseus** [Lunatrius/Schematica#140]
The client is decently modded, so it could be a cross-mod issue.
The client crashes when any schematic is loaded.
Here is the error message:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/14/16 9:19 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(I)V
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_72712_a(RenderSchematic.java:406)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.setWorldAndLoadRenderers(RenderSchematic.java:204)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:244)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_72712_a(RenderSchematic.java:406)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.setWorldAndLoadRenderers(RenderSchematic.java:204)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:244)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Epicarseus'/38, l='MpServer', x=626.31, y=56.00, z=1158.06]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (580,4,1141), Chunk: (at 4,0,5 in 36,71; contains blocks 576,0,1136 to 591,255,1151), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Level time: 144921 game time, 12664 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntitySkeleton['Skeleton'/0, l='MpServer', x=559.30, y=56.00, z=1148.33], EntityZombie['Zombie'/1, l='MpServer', x=560.76, y=56.00, z=1165.08], EntitySpider['Spider'/2, l='MpServer', x=563.73, y=56.00, z=1169.77], EntityItem['item.item.string'/3, l='MpServer', x=575.89, y=56.00, z=1133.36], EntitySkeleton['Skeleton'/4, l='MpServer', x=572.75, y=56.00, z=1143.35], EntitySkeleton['Skeleton'/5, l='MpServer', x=571.65, y=56.00, z=1141.45], EntityItem['item.item.string'/7, l='MpServer', x=563.61, y=56.00, z=1149.65], EntityItem['item.item.string'/8, l='MpServer', x=563.37, y=56.00, z=1150.78], EntitySpider['Spider'/9, l='MpServer', x=568.02, y=56.00, z=1144.02], EntityItem['item.item.string'/10, l='MpServer', x=566.17, y=56.00, z=1143.45], EntitySpider['Spider'/11, l='MpServer', x=562.15, y=56.00, z=1147.35], EntitySkeleton['Skeleton'/12, l='MpServer', x=565.30, y=56.00, z=1141.51], EntitySpider['Spider'/13, l='MpServer', x=570.13, y=56.00, z=1140.58], EntityItem['item.item.rottenFlesh'/14, l='MpServer', x=571.07, y=56.00, z=1156.04], EntityItem['item.item.string'/17, l='MpServer', x=570.56, y=56.00, z=1165.01], EntitySpider['Spider'/18, l='MpServer', x=565.36, y=56.00, z=1158.32], EntitySkeleton['Skeleton'/19, l='MpServer', x=564.33, y=56.00, z=1159.33], EntityZombie['Zombie'/20, l='MpServer', x=559.97, y=56.00, z=1148.93], EntityCreeper['Creeper'/21, l='MpServer', x=575.19, y=56.00, z=1174.33], EntityItem['item.item.string'/24, l='MpServer', x=564.04, y=56.00, z=1172.45], EntitySpider['Spider'/25, l='MpServer', x=579.92, y=56.00, z=1135.70], EntitySkeleton['Skeleton'/26, l='MpServer', x=580.65, y=56.00, z=1137.50], EntitySpider['Spider'/27, l='MpServer', x=580.59, y=56.00, z=1142.92], EntityItem['item.item.string'/28, l='MpServer', x=579.93, y=56.00, z=1142.42], EntityCreeper['Creeper'/29, l='MpServer', x=578.54, y=56.00, z=1150.27], EntityCreeper['Creeper'/32, l='MpServer', x=592.86, y=56.00, z=1160.55], EntitySkeleton['Skeleton'/33, l='MpServer', x=569.66, y=56.00, z=1173.50], EntitySkeleton['Skeleton'/34, l='MpServer', x=584.33, y=56.00, z=1171.50], EntityCreeper['Creeper'/35, l='MpServer', x=587.43, y=56.00, z=1161.46], EntityPlayerSP['Epicarseus'/38, l='MpServer', x=626.31, y=56.00, z=1158.06], EntityItem['item.item.string'/6073, l='MpServer', x=573.68, y=56.00, z=1158.46]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:478)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 623463272 bytes (594 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1904 Optifine OptiFine_1.9_HD_U_B3 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1904.jar) 
	UCHIJAAAA	Forge{12.16.1.1904} [Minecraft Forge] (forge-1.9-12.16.1.1904.jar) 
	UCHIJAAAA	actuallyadditions{1.9-r31} [Actually Additions] (ActuallyAdditions-1.9-r31.jar) 
	UCHIJAAAA	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCHIJAAAA	aura{593} [Aura Cascade] (Aura Cascade - Build 593.jar) 
	UCHIJAAAA	basemetals{2.2.2} [Base Metals] (BaseMetals_1.9-2.2.2.jar) 
	UCHIJAAAA	baublesstuff{2.0.8} [Baubles Stuff] (baublesstuff-2.0.8.jar) 
	UCHIJAAAA	bdlib{1.11.0.14} [BD Lib] (bdlib-1.11.0.14-mc1.9.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.0} [Better Builder's Wands] (BetterBuildersWands-0.6.0-1.9r124+c748dee.jar) 
	UCHIJAAAA	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCHIJAAAA	JEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
	UCHIJAAAA	BloodMagic{1.9-2.0.0-36} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-36.jar) 
	UCHIJAAAA	bookshelf{1.2.0.226} [Bookshelf] (Bookshelf-1.9-1.2.0.237.jar) 
	UCHIJAAAA	bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar) 
	UCHIJAAAA	Botania{r1.8-304} [Botania] (Botania-unofficial.r1.8-304.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCHIJAAAA	mcmultipart{1.1.1} [MCMultiPart] (MCMultiPart-1.1.1-universal.jar) 
	UCHIJAAAA	chiselsandbits{9.16} [Chisels & Bits] (chiselsandbits-9.16.jar) 
	UCHIJAAAA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9-rc.jar) 
	UCHIJAAAA	cyclopscore{0.5.8} [Cyclops Core] (CyclopsCore-1.9-0.5.8.jar) 
	UCHIJAAAA	ElecCore{1.4.270} [ElecCore] (ElecCore-1.9-1.4.270.jar) 
	UCHIJAAAA	deepresonance{1.1.4beta30} [DeepResonance] (deepresonance-1.9.0-1.1.4beta30.jar) 
	UCHIJAAAA	dldungeonsjdg{1.8.11} [Doomlike Dungeons] (DoomlikeDungeons-1.8.11-MC1.9.jar) 
	UCHIJAAAA	poweradvantage{2.1.1} [Power Advantage] (PowerAdvantage_1.9.0-2.1.1.jar) 
	UCHIJAAAA	electricadvantage{2.0.3} [Electric Advantage] (ElectricAdvantage_1.9-2.0.3.jar) 
	UCHIJAAAA	ezstorage{1.0} [EZ Storage] (ezstorage-1.9-1.2.1.jar) 
	UCHIJAAAA	pressure{1.3.1.13} [Pressure Pipes] (pressure-1.3.1.13-mc1.9.jar) 
	UCHIJAAAA	advgenerators{0.9.20.8} [Advanced Generators] (generators-0.9.20.8-mc1.9.jar) 
	UCHIJAAAA	integrateddynamics{0.3.8} [Integrated Dynamics] (IntegratedDynamics-1.9-0.3.8.jar) 
	UCHIJAAAA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJAAAA	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCHIJAAAA	fyberbackpack{1.0.1} [Just Backpacks] (justbackpacks-mc1.9-1.0.1.jar) 
	UCHIJAAAA	jet_packs{1.0.0} [Just JetPacks] (JustJetpacks-1.0.0.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.34} [LunatriusCore] (LunatriusCore-1.9-1.1.2.34-universal.jar) 
	UCHIJAAAA	malisiscore{1.9-3.0.6} [MalisisCore] (malisiscore-1.9-3.0.6.jar) 
	UCHIJAAAA	malisisdoors{1.9-4.0.1} [MalisisDoors] (malisisdoors-1.9-4.0.1.jar) 
	UCHIJAAAA	mantle{1.9-0.10.0.jenkins132} [Mantle] (Mantle-1.9-0.10.0.jar) 
	UCHIJAAAA	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCHIJAAAA	tconstruct{1.9-2.3.0.jenkins193} [Tinkers' Construct] (TConstruct-1.9-2.3.0.jar) 
	UCHIJAAAA	neotech{3.0.6} [NeoTech] (NeoTech-1.9-3.0.6.jar) 
	UCHIJAAAA	harvestcraft{1.9a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9a.jar) 
	UCHIJAAAA	progressiveautomation{1.6.42} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.42.jar) 
	UCHIJAAAA	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCHIJAAAA	quantumflux{2.0.6} [QuantumFlux] (quantumflux-1.9-2.0.6.jar) 
	UCHIJAAAA	Quark{beta-18} [Quark] (Quark-beta-18.jar) 
	UCHIJAAAA	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UCHIJAAAA	reborncore{2.1.0.53} [RebornCore] (RebornCore-1.9-2.1.0.53-universal.jar) 
	UCHIJAAAA	redstonepaste{1.7.3} [Redstone Paste] (redstonepaste-mc1.9-1.7.3.jar) 
	UCHIJAAAA	refinedstorage{0.5.6} [Refined Storage] (refinedstorage-0.5.6.jar) 
	UCHIJAAAA	xreliquary{1.9-1.3.1.342} [Reliquary] (Reliquary-1.9-1.3.1.342.jar) 
	UCHIJAAAA	rftools{4.46} [RFTools] (rftools-1.9.0-4.46.jar) 
	UCHIJAAAA	rftoolsdim{4.23beta37} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta37.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCHIJAAAA	routerreborn{1.9-4.0.1.11b_universal} [Router Reborn] (RouterReborn-1.9-4.0.1.11b_universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.146} [Schematica] (Schematica-1.9-1.7.7.146-universal.jar) 
	UCHIJAAAA	soulshardstow{1.9-2.3.9-25} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9-2.3.9-25.jar) 
	UCHIJAAAA	steamadvantage{2.0.3} [Steam Advantage] (SteamAdvantage_1.9-2.0.3.jar) 
	UCHIJAAAA	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UCHIJAAAA	techreborn{1.0.6.197} [TechReborn] (TechReborn-1.9-1.0.6.197-universal.jar) 
	UCHIJAAAA	terrainCrystals{1.0.8} [Terrain Crystals] (TerrainCrystals-1.0.8-universal.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4600'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (11) from ActuallyAdditions-1.9-r31.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-36.jar
		* BotaniaAPI (78) from Botania-unofficial.r1.8-304.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.16.jar
		* CoFHAPI (1.8.9R1.2.0B1) from RebornCore-1.9-2.1.0.53-universal.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from ActuallyAdditions-1.9-r31.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* commoncapabilities|api (0.0.1) from IntegratedDynamics-1.9-0.3.8.jar
		* compactstorage (v2.0.0a) from compactstorage-2.1-1.9-rc.jar
		* DLDungeonsAPI (1.1) from DoomlikeDungeons-1.8.11-MC1.9.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta30.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.270.jar
		* IC2API (1.0) from RebornCore-1.9-2.1.0.53-universal.jar
		* integrateddynamics|api (0.1.0) from IntegratedDynamics-1.9-0.3.8.jar
		* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.197.jar
		* McJtyLib (1.9.0-1.8.3) from mcjtylib-1.9.0-1.8.3.jar
		* pressureAPI (1.3.1.13) from pressure-1.3.1.13-mc1.9.jar
		* PsiAPI (2) from Psi-beta-31.jar
		* reborncoreAPI (2.1.0.53) from RebornCore-1.9-2.1.0.53-universal.jar
		* SchematicaAPI (1.1) from Schematica-1.9-1.7.7.146-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.9-1.7.7.146-universal.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9-2.3.9-25.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* techrebornAPI (1.0.6.197) from TechReborn-1.9-1.0.6.197-universal.jar
		* WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
	Launched Version: 1.9-forge1.9-12.16.1.1904
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4331, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.9_HD_U_B3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4331
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 8
```

**Comment by Lunatrius** [comment]
Remove Optifine until the dev releases an updated version. #137
