### ISSUE TITLE
Game crash when saving schematic

### ISSUE THREAD

**Issue by Algaart** [Lunatrius/Schematica#164]
My gmae keeps crashing when trying to save schematic. Even tried it with just 4 blocks
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10.07.16 10:38
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method net.minecraft.nbt.NBTTagCompound.func_150298_a(Ljava/lang/String;Lnet/minecraft/nbt/NBTBase;Ljava/io/DataOutput;)V from class com.github.lunatrius.schematica.world.schematic.SchematicFormat
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.writeToFile(SchematicFormat.java:61)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.writeToFileAndNotify(SchematicFormat.java:79)
	at com.github.lunatrius.schematica.handler.QueueTickHandler.processQueue(QueueTickHandler.java:71)
	at com.github.lunatrius.schematica.handler.QueueTickHandler.onServerTick(QueueTickHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_QueueTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:253)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:649)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 724360880 bytes (690 MB) / 1906356224 bytes (1818 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Algaart'/97, l='New World', x=902,72, y=5,00, z=806,12]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Lunatrius** [comment]
* What launcher do you use?
 * Have you tried updating Forge to the latest version (11.15.1.1902) for 1.8.9?
 * Is there **any** reason to still use a 1.8.9 version of the mod, when my mods are already released for 1.10.2 (and my mods seem to be the only ones that you're using)?

**Comment by Algaart** [comment]
Normal minecraft launcher. Yes i tried and i use 1.8.9 because i need it for a 1.8.9 server

**Comment by Lunatrius** [comment]
Try Forge `11.15.0.1656`

**Comment by Lunatrius** [comment]
Closing this as a non issue, if it still didn't/doesn't work feel free to re-open the issue.
