### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by vijaypabothu** [Lunatrius/Schematica#183]
Hi,
When  I am trying to push the data in to a topic from by kafka producer I am getting the below error. If any one familiar about this issue. Please suggest me. 

Error details:
```
[2016-11-15 00:05:02,897] ERROR [Replica Manager on Broker 0]: Error processing append operation on partition NP-0 (kafka.server.ReplicaManager)
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:693)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:174)
```
My producer code is below.
```
package com.examples;

import java.io.File;
import java.io.FileInputStream;
import java.util.Properties;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;

public class SimpleProducer {

	public static void main(String[] args) throws Exception{

		// Check arguments length value
		if(args.length == 0){
			System.out.println("Enter topic name");
			return;
		}

		//Assign topicName to string variable
		String topicName = args[0].toString();

		String runDeviceFullPath = "C:\\Users\\vpabothu\\Downloads\\configs\\ccn2.ser";
		File collectorData = new File(runDeviceFullPath);
		byte[] fileBytes = new byte[(int) collectorData.length()];

		try {
			FileInputStream is = new FileInputStream(collectorData);
			is.read(fileBytes);
			is.close();
		} catch (Exception e) {
			e.printStackTrace();
		}

		// create instance for properties to access producer configs   
		Properties props = new Properties();

		//Assign localhost id
		props.put("bootstrap.servers", "icx-lt-002:9092");

		//Set acknowledgements for producer requests.      
		// props.put("acks", "all");

		//If the request fails, the producer can automatically retry,
		//props.put("retries", 0);

		//Specify buffer size in config
		//props.put("batch.size", 16384);

		//Reduce the no of requests less than 0   
		//props.put("linger.ms", 1);

		//The buffer.memory controls the total amount of memory available to the producer for buffering.   
		props.put("buffer.memory", 500000000);
		
		props.put("max.request.size", "500000000");
		props.put("request.timeout.ms","1200000");

		props.put("key.serializer", 
				"org.apache.kafka.common.serialization.StringSerializer");

		props.put("value.serializer", 
				"org.apache.kafka.common.serialization.ByteArraySerializer");
		System.out.println(System.currentTimeMillis());

		Producer<String, byte[]> producer = new KafkaProducer<String, byte[]>(props);
		ProducerRecord<String, byte[]> data = new ProducerRecord<String, byte[]>("NP", "ccn2", fileBytes);     
		//producer.send(data);

		Future<RecordMetadata> rm = producer.send(data);
		try {
			RecordMetadata rmGet = rm.get();
			System.out.println("ACK-> Offset:"+rmGet.offset()+" Partition:"+rmGet.partition()+" Topic:"+rmGet.topic());
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println(System.currentTimeMillis());
		producer.close();
	}
}
```

**Comment by Lunatrius** [comment]
This issue is not even related to this project...
