### ISSUE TITLE
The game crashed whilst updating screen events

### ISSUE THREAD

**Issue by 14iCBi** [Lunatrius/Schematica#205]
"The game crashed whilst updating screen events: java.lang.NoClassDefFoundError: net/minecraft/world/WorldSettings$GameType"

When i try to load a schematic into both single player or multiplayer the game crashes, any advice as to how i can get this to work

running version 1.11.2 for forge, schematica and lunatrius

Outpt when i try to import into MCEdit if that helps

MCEdit version: 2.0.0-beta6
Python version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.14393
Processor: AMD64 Family 21 Model 1 Stepping 2, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 376.53 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 550 Ti/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 966, in import_ (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1106, in importSchematic (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 233, in __init__ (self is a WorldEditor)
  File "mceditlib\findadapter.py", line 62, in findAdapter  
  File "mceditlib\schematic.py", line 199, in __init__ (self is a SchematicFileAdapter)
  File "mceditlib\schematic.py", line 255, in getItemStackVersionFromEntities (self is a SchematicFileAdapter)
  File "src\mceditlib\nbt.pyx", line 445, in mceditlib.nbt._TAG_Compound.__getitem__ (src/mceditlib/nbt.c:9677)  
KeyError: 'Key TileEntities not found.'

**Comment by 14iCBi** [comment]
running version 1.11.2 for forge, schematica and lunatrius

**Comment by Lunatrius** [comment]
Upload the entire `fml-client-latest.log` to gist/pastebin and paste the link here.

**Comment by Lunatrius** [comment]
Closing this because you didn't post the log file. If you can provide the log file feel free to reopen the issue.
