### ISSUE TITLE
Crash no schematics work

### ISSUE THREAD

**Issue by Owennnnnn** [Lunatrius/Schematica#214]
```---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 4/21/17 4:24 AM
XRay version: 47
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraft.tileentity.TileEntity.func_189514_c(Lnet/minecraft/nbt/NBTTagCompound;)Lnet/minecraft/tileentity/TileEntity;
	at com.github.lunatrius.schematica.nbt.NBTHelper.readTileEntityFromCompound(NBTHelper.java:146)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:99)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:458)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:546)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.lunatrius.schematica.nbt.NBTHelper.readTileEntityFromCompound(NBTHelper.java:146)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:99)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:458)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:546)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['_Owenn'/7382, l='MpServer', x=-6150.53, y=69.00, z=-85.72]]
	Chunk stats: MultiplayerChunkCache: 50, 50
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-3632,63,-2661), Chunk: (at 0,3,11 in -227,-167; contains blocks -3632,0,-2672 to -3617,255,-2657), Region: (-8,-6; contains chunks -256,-192 to -225,-161, blocks -4096,0,-3072 to -3585,255,-2561)
	Level time: 85513 game time, 40789513 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityMinecartChest['Minecart with Chest'/2827833, l='MpServer', x=-6137.50, y=25.06, z=-92.50], EntityMinecartChest['Minecart with Chest'/374397, l='MpServer', x=-6174.50, y=20.06, z=-59.50], EntityPlayerSP['_Owenn'/7382, l='MpServer', x=-6150.53, y=69.00, z=-85.72]]
	Retry entities: 0 total; []
	Server brand: Travertine (git:Travertine-Bootstrap:1.11-SNAPSHOT:45932e7:unknown) <- Escargot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:519)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 274580152 bytes (261 MB) / 738664448 bytes (704 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: Minecraft 1.10 MCP 9.32 Powered by Forge 12.18.0.2000 Optifine OptiFine_1.10_HD_U_D7 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10-12.18.0.2000-1.10.0.jar) 
	UCHIJA	Forge{12.18.0.2000} [Minecraft Forge] (forge-1.10-12.18.0.2000-1.10.0.jar) 
	UCHIJA	bspkrsCore{7.1.1} [bspkrsCore] (bspkrsCore_mc1.9-1.10.2_v-client-7.1.1.jar) 
	UCHIJA	ArmorStatusHUD{1.31.1} [ArmorStatusHUD] (ArmorStatusHUD_mc1.9-1.10.2_v-client-1.31.1.jar) 
	UCHIJA	DirectionHUD{1.26.1} [DirectionHUD] (DirectionHUD_mc1.9-1.10.2_v-client-1.26.1.jar) 
	UCHIJA	IngameAccountSwitcher{7.0.1} [In-Game Account Switcher] (InGameAccountSwitcher-Forge-1.9.4-7.0.1.jar) 
	UCHIJA	JEI{3.7.1.219} [Just Enough Items] (jei_1.10-3.7.1.219.jar) 
	UCHIJA	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UCHIJA	Schematica{1.7.8.148} [Schematica] (Schematica-1.9.4-1.7.8.148-universal.jar) 
	UCHIJA	StatusEffectHUD{1.29.1} [StatusEffectHUD] (StatusEffectHUD_mc1.9-1.10.2_v-client-1.29.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	Launched Version: 1.10-forge1.10-12.18.0.2000-1.10.0
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.10_HD_U_D7
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.53
	OpenGlRenderer: GeForce GTX 660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12```


this is crashing on  multiplayer and singleplayer

**Comment by Lunatrius** [comment]
You're using the 1.9.4 version of the mod on Minecraft 1.10.

**Comment by Owennnnnn** [comment]
thanks
