### ISSUE TITLE
minecraft forge schematica not working 

### ISSUE THREAD

**Issue by firedragon895** [Lunatrius/Schematica#224]
i was trying to play shcematica to make minecraft cannons and schematica wont work 
crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PlayerAPIPlugin (PlayerAPI-1.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 6/3/17 4:29 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.OutOfMemoryError: Direct buffer memory
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:37)
	at net.minecraft.client.renderer.WorldRenderer.<init>(WorldRenderer.java:75)
	at net.minecraft.client.renderer.RegionRenderCacheBuilder.<init>(SourceFile:18)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(ChunkRenderDispatcher.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.OverlayRenderDispatcher.<init>(OverlayRenderDispatcher.java:15)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<init>(RenderSchematic.java:99)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<clinit>(RenderSchematic.java:68)
	at com.github.lunatrius.schematica.proxy.ClientProxy.init(ClientProxy.java:187)
	at com.github.lunatrius.schematica.Schematica.init(Schematica.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 34518560 bytes (32 MB) / 255066112 bytes (243 MB) up to 255066112 bytes (243 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 Optifine OptiFine_1.8_HD_U_H6 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHI	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHI	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHI	LunatriusCore{1.1.2.30} [LunatriusCore] (LunatriusCore-1.8-1.1.2.30-universal.jar) 
	UCHE	Schematica{1.7.7.140} [Schematica] (Schematica-1.8-1.7.7.140-universal.jar) 
	UCHI	ToggleSneak{3.1.0} [ToggleSneak] (ToggleSneak-(1.8)-v3.1.0.jar) 
	Loaded coremods (and transformers): 
PlayerAPIPlugin (PlayerAPI-1.8-1.4.jar)
  api.player.forge.PlayerAPITransformer
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2900' Renderer: 'Intel(R) HD Graphics'
	The 5zig Mod Version: 3.3.7
	OptiFine Version: OptiFine_1.8_HD_U_H6
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2900
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4```
can anyone help me

**Comment by firedragon895** [comment]
oh and i have 3.68 gb of ram

**Comment by Lunatrius** [comment]
You're running the game with 243 MB of RAM and with the built-in `Intel(R) HD Graphics` graphics card. If you have a dedicated graphics card you might want to set that as the default for java when running Minecraft.
