### ISSUE TITLE
Schematica crashes when i try to run it 

### ISSUE THREAD

**Issue by firedragon895** [Lunatrius/Schematica#226]
it doesent even open minecraft it just starts to run and crashes 
crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PlayerAPIPlugin (PlayerAPI-1.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 6/17/17 1:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.OutOfMemoryError: Direct buffer memory
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:37)
	at net.minecraft.client.renderer.WorldRenderer.<init>(WorldRenderer.java:75)
	at net.minecraft.client.renderer.RegionRenderCacheBuilder.<init>(SourceFile:18)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(ChunkRenderDispatcher.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.OverlayRenderDispatcher.<init>(OverlayRenderDispatcher.java:15)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<init>(RenderSchematic.java:99)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<clinit>(RenderSchematic.java:68)
	at com.github.lunatrius.schematica.proxy.ClientProxy.init(ClientProxy.java:187)
	at com.github.lunatrius.schematica.Schematica.init(Schematica.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 50487408 bytes (48 MB) / 255066112 bytes (243 MB) up to 255066112 bytes (243 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 Optifine OptiFine_1.8_HD_U_H6 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHI	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHI	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHI	LunatriusCore{1.1.2.30} [LunatriusCore] (LunatriusCore-1.8-1.1.2.30-universal.jar) 
	UCHI	MapWriter{1.5} [MapWriter] (MapWriter-1.8-1.5.jar) 
	UCHE	Schematica{1.7.7.140} [Schematica] (Schematica-1.8-1.7.7.140-universal.jar) 
	UCHI	ToggleSneak{3.1.0} [ToggleSneak] (ToggleSneak-(1.8)-v3.1.0.jar) 
	Loaded coremods (and transformers): 
PlayerAPIPlugin (PlayerAPI-1.8-1.4.jar)
  api.player.forge.PlayerAPITransformer
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2900' Renderer: 'Intel(R) HD Graphics'
	The 5zig Mod Version: 3.3.7
	OptiFine Version: OptiFine_1.8_HD_U_H6
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2900
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4
```

**Comment by Lunatrius** [comment]
Open up `Schematica.cfg` with Notepad (or any text editor) and change the schematic chunk render size to a lower value.

**Comment by firedragon895** [comment]
it wont even open.

**Comment by firedragon895** [comment]
its 
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 6/23/17 6:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.OutOfMemoryError: Direct buffer memory
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:37)
	at net.minecraft.client.renderer.WorldRenderer.<init>(WorldRenderer.java:75)
	at net.minecraft.client.renderer.RegionRenderCacheBuilder.<init>(SourceFile:15)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(ChunkRenderDispatcher.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.OverlayRenderDispatcher.<init>(OverlayRenderDispatcher.java:15)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<init>(RenderSchematic.java:99)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<clinit>(RenderSchematic.java:68)
	at com.github.lunatrius.schematica.proxy.ClientProxy.init(ClientProxy.java:187)
	at com.github.lunatrius.schematica.Schematica.init(Schematica.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 82686840 bytes (78 MB) / 239075328 bytes (228 MB) up to 239075328 bytes (228 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -Xmx256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 Optifine OptiFine_1.8_HD_U_H6 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHI	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHI	LunatriusCore{1.1.2.30} [LunatriusCore] (LunatriusCore-1.8-1.1.2.30-universal.jar) 
	UCHE	Schematica{1.7.7.140} [Schematica] (Schematica-1.8-1.7.7.140-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2900' Renderer: 'Intel(R) HD Graphics'
	The 5zig Mod Version: 3.3.7
	OptiFine Version: OptiFine_1.8_HD_U_H6
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2900
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4
now

**Comment by firedragon895** [comment]
i changed the render value to 1

**Comment by Lunatrius** [comment]
Try allocating more RAM to Minecraft. Just noticed that you're running the game with about 300MB of RAM, try to increase that to something like 1024MB.

**Comment by firedragon895** [comment]
under jvm  arguments? if so i added 2g and it still wont run.

**Comment by firedragon895** [comment]
crash report now 
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 6/24/17 2:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.OutOfMemoryError: Direct buffer memory
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:37)
	at net.minecraft.client.renderer.WorldRenderer.<init>(WorldRenderer.java:75)
	at net.minecraft.client.renderer.RegionRenderCacheBuilder.<init>(SourceFile:15)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(ChunkRenderDispatcher.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.OverlayRenderDispatcher.<init>(OverlayRenderDispatcher.java:15)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<init>(RenderSchematic.java:99)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<clinit>(RenderSchematic.java:68)
	at com.github.lunatrius.schematica.proxy.ClientProxy.init(ClientProxy.java:187)
	at com.github.lunatrius.schematica.Schematica.init(Schematica.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 94228872 bytes (89 MB) / 241631232 bytes (230 MB) up to 241631232 bytes (230 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn300M -Xmx256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 Optifine OptiFine_1.8_HD_U_H6 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHI	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHI	LunatriusCore{1.1.2.30} [LunatriusCore] (LunatriusCore-1.8-1.1.2.30-universal.jar) 
	UCHE	Schematica{1.7.7.140} [Schematica] (Schematica-1.8-1.7.7.140-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2900' Renderer: 'Intel(R) HD Graphics'
	The 5zig Mod Version: 3.3.7
	OptiFine Version: OptiFine_1.8_HD_U_H6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2900
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Kylebartaous** [comment]
maybe something your forgetting ? Don;t you need a core mod like lumatrius-core or something for it to work.

**Comment by PhoenixCodes** [comment]
Looks like Lunatrius Core is there from the crash report.

Roland Goldberg

**Comment by Lunatrius** [comment]
No, he's clearly running out of memory:
```net.minecraftforge.fml.common.LoaderException: java.lang.OutOfMemoryError: Direct buffer memory```

If you're adding JVM arguments, add these two:
```-Xms512m -Xmx1024m```

**Comment by firedragon895** [comment]
i added what you said to add and it wont even open minecraft its just
 the game has crashed. We're sorry for the inconvenience.
i added 
-Xms512m -Xmx1024m
to jvm arguments.

**Comment by GitHubLynx** [comment]
Have you tried starting it without Schematica enabled? I know...basic step, but just making sure.

**Comment by firedragon895** [comment]
no i have not tried how do i do it?

**Comment by firedragon895** [comment]
like disabling it and then enabling it?

**Comment by GitHubLynx** [comment]
Does it also crash when you remove the plugin from the mods folder and then start Minecraft?

**Comment by firedragon895** [comment]
it gets farther into the mod loading without it though it goes to 7/7 and then not responds and 
i have to close it.

**Comment by firedragon895** [comment]
i can run it with just like schematica or lunatruis core

**Comment by GitHubLynx** [comment]
Sounds like you're having issues with a different mod...

**Comment by firedragon895** [comment]
i ran schematica by itself and this is what happened
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/1/17 2:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.OutOfMemoryError: Direct buffer memory
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:37)
	at net.minecraft.client.renderer.WorldRenderer.<init>(WorldRenderer.java:45)
	at net.minecraft.client.renderer.RegionRenderCacheBuilder.<init>(SourceFile:15)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(SourceFile:46)
	at com.github.lunatrius.schematica.client.renderer.chunk.OverlayRenderDispatcher.<init>(OverlayRenderDispatcher.java:15)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<init>(RenderSchematic.java:99)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.<clinit>(RenderSchematic.java:68)
	at com.github.lunatrius.schematica.proxy.ClientProxy.init(ClientProxy.java:187)
	at com.github.lunatrius.schematica.Schematica.init(Schematica.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 92892944 bytes (88 MB) / 239075328 bytes (228 MB) up to 239075328 bytes (228 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xmx256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHI	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHI	LunatriusCore{1.1.2.30} [LunatriusCore] (LunatriusCore-1.8-1.1.2.30-universal.jar) 
	UCHE	Schematica{1.7.7.140} [Schematica] (Schematica-1.8-1.7.7.140-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2900' Renderer: 'Intel(R) HD Graphics'

**Comment by GitHubLynx** [comment]
Guess I'm wrong. Weird thing is that is mentions 2 different versions of mcp.

**Comment by Lunatrius** [comment]
You still didn't add the flag to the proper place, can you provide a screenshot?
```
	Memory: 92892944 bytes (88 MB) / 239075328 bytes (228 MB) up to 239075328 bytes (228 MB)
```
