### ISSUE TITLE
Why do my minecraft keep crashing

### ISSUE THREAD

**Issue by Notebola** [Lunatrius/Schematica#230]
```
2017-07-02 20:11:02,467 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-07-02 20:11:02,469 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[20:11:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:11:02] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:11:02] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[20:11:02] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[20:11:02] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_D8.jar
[20:11:02] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.0_HD_U_H6 (1).jar
[20:11:02] [main/INFO] [FML]: Loading tweaker eu.the5zig.mod.asm.ClassTweaker from The 5zig Mod v3.11.3 for Minecraft 1.7.10.jar
[20:11:02] [main/INFO] [FML]: Loading tweaker eu.the5zig.mod.asm.ClassTweaker from The 5zig Mod v3.9.20 for Minecraft 1.8.jar
[20:11:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:11:02] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[20:11:02] [main/WARN] [LaunchWrapper]: Tweak class name optifine.OptiFineForgeTweaker has already been visited -- skipping
[20:11:02] [main/INFO] [LaunchWrapper]: Loading tweak class name eu.the5zig.mod.asm.ClassTweaker
[20:11:02] [main/WARN] [LaunchWrapper]: Tweak class name eu.the5zig.mod.asm.ClassTweaker has already been visited -- skipping
[20:11:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[20:11:02] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[20:11:02] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[20:11:02] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[20:11:02] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/C:/Users/duran/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_U_D8.jar
[20:11:02] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: C:\Users\duran\AppData\Roaming\.minecraft\mods\OptiFine_1.7.10_HD_U_D8.jar
[20:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class eu.the5zig.mod.asm.ClassTweaker
[20:11:02] [main/INFO] [LaunchWrapper]: Minecraft Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
[20:11:03] [main/INFO] [LaunchWrapper]: Forge detected!
[20:11:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:11:06] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:11:06] [main/INFO] [STDOUT]: [com.squidhq.brander.Agent:transform:39]: SquidHQ: Branded
[20:11:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:11:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:11:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:11:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:11:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:11:08] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[20:11:09] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: java.io.IOException: MD5 not matching, name: e.class, saved: 4920cc36f63225ac632e28f0644f1dd9, patched: b3e36544051afb705a4ec9ad508177de
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:229)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:153)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:117)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.client.main.Main.main(SourceFile:41)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: java.io.IOException: MD5 not matching, name: bqm.class, saved: f2ae6f2635d58ed825d4cf10ab099936, patched: 53448f042736c7bf911bfea529d9d307
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:229)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:153)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:117)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.client.main.Main.main(SourceFile:41)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: optifine.xdelta.PatchException: truncated source file, aborting
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.xdelta.GDiffPatcher.copy(GDiffPatcher.java:181)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.xdelta.GDiffPatcher.runPatch(GDiffPatcher.java:125)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:67)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:63)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.Patcher.applyPatch(Patcher.java:149)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:218)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:153)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:117)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.client.main.Main.main(SourceFile:41)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
2017-07-02 20:11:09,922 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-07-02 20:11:09,937 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-07-02 20:11:09,939 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: java.io.IOException: MD5 not matching, name: g.class, saved: a0e53e709dec296ad3bd48f3721f23f1, patched: d9d5dbae323d768bd67fd5f6a52dc2d7
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:229)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:153)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:117)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.client.Minecraft.<clinit>(Minecraft.java:195)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.client.main.Main.main(SourceFile:41)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:11:09] [main/INFO] [STDERR]: [optifine.OptiFineClassTransformer:getOptiFineResourcePatched:236]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:11:10] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.resources.ResourceIndex.<init>(Ljava/io/File;Ljava/lang/String;)V
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:299) ~[ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [20:11:10] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:11:10] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[20:11:10] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:11:10] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[20:11:10] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[20:11:10] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:11:10] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

what do i have to do

**Comment by Lunatrius** [comment]
You have directly edited the jar file, which is no longer supported by Mojang. Start with a fresh profile and install Optifine by using their install instructions.
