### ISSUE TITLE
[1.12] Game crashes while initializing

### ISSUE THREAD

**Issue by Arkayox** [Lunatrius/Schematica#238]
```
# Here is the crash report I got.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/19/17 4:36 PM
Description: Initializing game

java.lang.AbstractMethodError
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:785)
	at net.minecraftforge.client.model.ModelLoader$MultipartModel.bake(ModelLoader.java:1268)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:785)
	at net.minecraftforge.client.model.ModelLoader$MultipartModel.bake(ModelLoader.java:1268)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 807855080 bytes (770 MB) / 1265631232 bytes (1207 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.0.2373 Optifine OptiFine_1.12_HD_U_C2 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2373.jar) 
	UCH	forge{14.21.0.2373} [Minecraft Forge] (forge-1.12-14.21.0.2373.jar) 
	UCH	journeymap{1.12-5.4.7b3} [JourneyMap] (journeymap-1.12-5.4.7b3.jar) 
	UCH	lunatriuscore{1.1.3.git} [LunatriusCore] (LunatriusCore-1.12-1.1.3.git-universal.jar) 
	UCH	schematica{1.7.8.git} [Schematica] (Schematica-1.12-1.7.8.git-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12-forge1.12-14.21.0.2373
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Arkayox's Faithful, Arkayox's Faithful +
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.12_HD_U_C2
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.33
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by Lunatrius** [comment]
You're not using an official release and I can't treat this issue as a valid bug report.

It looks like a Forge issue, I'll make sure to look into this while updating to 1.12.

**Comment by Lunatrius** [comment]
Test it again using the official version.

**Comment by William2oI** [comment]
What do you mean by "official version" ??

**Comment by Lunatrius** [comment]
Download the latest version (1.7.8.162) of the mod from curse, mods.io or mc.lunatri.us.

**Comment by William2oI** [comment]
It does not work with the official version

**Comment by Lunatrius** [comment]
Post the new crash log.

The crash log that's currently attached to the issue uses the Schematica build from https://github.com/Lunatrius/Schematica/pull/229#issuecomment-311338644

**Comment by Lunatrius** [comment]
This might be also the reason why it doesn't work: https://github.com/Lunatrius/Schematica/pull/229#issuecomment-311560755

**Comment by William2oI** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (replaymod-1.12-2.0.0-b7.jar)
  OpenEyePlugin (OpenEye.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 7/9/17 5:47 PM
Description: Initializing game

java.lang.AbstractMethodError
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:779)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:779)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 107359064 bytes (102 MB) / 395182080 bytes (376 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 Optifine OptiFine_1.12_HD_U_A0_pre 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UCH	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UCH	OpenEye{0.8} [OpenEye] (OpenEye.jar) 
	UCH	replaymod-compat{1.12-2.0.0-b7} [Replay Mod - Compatibility] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod-render{1.12-2.0.0-b7} [Replay Mod - Render] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod-replay{1.12-2.0.0-b7} [Replay Mod - Replay] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod{1.12-2.0.0-b7} [Replay Mod] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod-editor{1.12-2.0.0-b7} [Replay Mod - Replay Editor] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod-extras{1.12-2.0.0-b7} [Replay Mod - Extras] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod-online{1.12-2.0.0-b7} [Replay Mod - Online] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod-recording{1.12-2.0.0-b7} [Replay Mod - Recording] (replaymod-1.12-2.0.0-b7.jar) 
	UCH	replaymod-simplepathing{1.12-2.0.0-b7} [Replay Mod - Simple Pathing] (replaymod-1.12-2.0.0-b7.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (replaymod-1.12-2.0.0-b7.jar)
  
OpenEyePlugin (OpenEye.jar)
  openeye.asm.MultiTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4474' Renderer: 'Intel(R) HD Graphics 530'
	Launched Version: 1.12-forge1.12-14.21.1.2387
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 20.19.15.4474, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.12-rv1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12_HD_U_A0_pre
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4474
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by William2oI** [comment]
I believe it is because of optifine

**Comment by William2oI** [comment]
![image](https://user-images.githubusercontent.com/30462695/28662805-ac6e12ca-72bb-11e7-9ca9-9cafafab5e65.png)

The game tells me this

**Comment by William2oI** [comment]
![image](https://user-images.githubusercontent.com/30462695/28662880-ec8486fa-72bb-11e7-86f2-ee8d766e6a20.png)

The game tells me this

**Comment by Lunatrius** [comment]
Schematica only supports Forge 2387 or above. Earlier versions are not supported.

**Comment by Pervengue** [comment]
Hi Lunatrius,

First off all I want to thank you for all the great job you do.


I have an issue by game start with the latest version of schematica.

Here the version of add ons I use:

FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2426.jar)
forge{14.21.1.2426} [Minecraft Forge] (forge-1.12-14.21.1.2426.jar) 
lunatriuscore{1.2.0.40} [LunatriusCore] (LunatriusCore-1.12-1.2.0.40-universal.jar) 
schematica{1.7.8.162} [Schematica] (Schematica-1.12-1.7.8.162-universal.jar) 


Error log is attached to the post :)


[fml-client-3.zip](https://github.com/Lunatrius/Schematica/files/1182492/fml-client-3.zip)

**Comment by William2oI** [comment]
j'ai essayer plusieur version et aucune ne fonctionne

**Comment by William2oI** [comment]
I try several versions and none works

**Comment by Lunatrius** [comment]
Try to run the game with only Forge, LunatriusCore and Schematica. Also post the new crash log.

**Comment by Lunatrius** [comment]
The crash log in https://github.com/Lunatrius/Schematica/issues/238#issuecomment-318303174 does not even have Schematica/LunatriusCore installed and the crash is the same.

You'll have to **remove Optifine** and **update to a more recent version of Forge** or keep playing without Schematica until Optifine gets updated.
