### ISSUE TITLE
[1.12] Crash at game start 

### ISSUE THREAD

**Issue by Pervengue** [Lunatrius/Schematica#243]
Hi Lunatrius,

First off all I want to thank you for all the great job you do.

I have an issue by game start with the latest version of schematica. (I think it's a different one then the one with optifine :))

Here the version of add ons I use:

FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2426.jar)
forge{14.21.1.2426} [Minecraft Forge] (forge-1.12-14.21.1.2426.jar)
lunatriuscore{1.2.0.40} [LunatriusCore] (LunatriusCore-1.12-1.2.0.40-universal.jar)
schematica{1.7.8.162} [Schematica] (Schematica-1.12-1.7.8.162-universal.jar)

Error log is attached to the post :)

[fml-client-3.zip](https://github.com/Lunatrius/Schematica/files/1182685/fml-client-3.zip)

**Comment by Pervengue** [comment]
Any idea ?

**Comment by Lunatrius** [comment]
```
[10:23:14] [main/ERROR] [FML/]: Caught exception from schematica (java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    com/github/lunatrius/schematica/client/renderer/RenderSchematic.renderWorld(FJ)V @210: aload
  Reason:
    Type top (current frame, locals[5]) is not assignable to reference type
  Current Frame:
    bci: @210
    flags: { }
    locals: { 'com/github/lunatrius/schematica/client/renderer/RenderSchematic', float, long, long_2nd }
    stack: { 'com/github/lunatrius/schematica/client/renderer/RenderSchematic', 'net/minecraft/util/BlockRenderLayer', double, double_2nd, integer }
  Bytecode:
    0x0000000: b802 132a b400 af13 0215 b601 46bb 0217
    0x0000010: 59b7 0218 3a04 2ab4 00a8 b602 1c3a 05b2
    0x0000020: 0156 b401 c039 06b2 0156 b401 c339 08b2
    0x0000030: 0156 b401 c639 0a19 0418 0618 0818 0ab6
    0x0000040: 021f 111d 01b8 0222 2ab4 00af 1302 24b6
    0x0000050: 0146 2ab4 00a8 b602 28b2 022e b602 34b8
    0x0000060: 0239 2ab4 00af 1302 3bb6 0146 2a19 0523
    0x0000070: 8d19 042a 59b4 00a6 5a04 60b5 00a6 2a18
    0x0000080: 0618 0818 0ab7 023f b602 432a b400 af13
    0x0000090: 0245 b601 462a 2014 0246 6db6 024b 2ab4
    0x00000a0: 00af 1302 4db6 0146 b202 5299 0009 110b
    0x00000b0: 60b8 0208 1117 00b8 0255 b801 3ab8 01ae
    0x00000c0: 1103 0211 0303 0403 b801 b22a b202 5b23
    0x00000d0: 8d05 1905 b602 5f57 2ab2 0262 238d 0519
    0x00000e0: 05b6 025f 572a b400 a8b6 0228 b202 2eb6
    0x00000f0: 0266 0303 b902 6c03 002a b202 6f23 8d05
    0x0000100: 1905 b602 5f57 2ab4 00a8 b602 28b2 022e
    0x0000110: b602 66b9 0272 0100 b802 0b11 1d00 b802
    0x0000120: 2211 0204 1302 73b8 0276 1117 00b8 0255
    0x0000130: b801 41b8 013a 2ab4 00af 1302 78b6 0146
    0x0000140: b802 7bb8 01ae 1103 0211 0303 0403 b801
    0x0000150: b22a 1905 1904 23b6 027f b802 0bb8 0239
    0x0000160: 2ab7 0282 1117 00b8 0255 b801 41b8 0213
    0x0000170: 1102 0413 0273 b802 762a b400 a8b6 0228
    0x0000180: b202 2eb6 0234 111d 01b8 0222 03b8 0201
    0x0000190: b801 3a2a b400 af13 0284 b601 46b8 01ae
    0x00001a0: 1103 0211 0303 0403 b801 b22a b202 8723
    0x00001b0: 8d05 1905 b602 5f57 b802 0bb8 0141 04b8
    0x00001c0: 0201 111d 00b8 0222 b802 13b1          
  Stackmap Table:
    same_frame_extended(@180)
)
[10:23:14] [main/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/28/17 10:23 AM
XRay version: 51
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Schematica (schematica)
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    com/github/lunatrius/schematica/client/renderer/RenderSchematic.renderWorld(FJ)V @210: aload
  Reason:
    Type top (current frame, locals[5]) is not assignable to reference type
  Current Frame:
    bci: @210
    flags: { }
    locals: { 'com/github/lunatrius/schematica/client/renderer/RenderSchematic', float, long, long_2nd }
    stack: { 'com/github/lunatrius/schematica/client/renderer/RenderSchematic', 'net/minecraft/util/BlockRenderLayer', double, double_2nd, integer }
  Bytecode:
    0x0000000: b802 132a b400 af13 0215 b601 46bb 0217
    0x0000010: 59b7 0218 3a04 2ab4 00a8 b602 1c3a 05b2
    0x0000020: 0156 b401 c039 06b2 0156 b401 c339 08b2
    0x0000030: 0156 b401 c639 0a19 0418 0618 0818 0ab6
    0x0000040: 021f 111d 01b8 0222 2ab4 00af 1302 24b6
    0x0000050: 0146 2ab4 00a8 b602 28b2 022e b602 34b8
    0x0000060: 0239 2ab4 00af 1302 3bb6 0146 2a19 0523
    0x0000070: 8d19 042a 59b4 00a6 5a04 60b5 00a6 2a18
    0x0000080: 0618 0818 0ab7 023f b602 432a b400 af13
    0x0000090: 0245 b601 462a 2014 0246 6db6 024b 2ab4
    0x00000a0: 00af 1302 4db6 0146 b202 5299 0009 110b
    0x00000b0: 60b8 0208 1117 00b8 0255 b801 3ab8 01ae
    0x00000c0: 1103 0211 0303 0403 b801 b22a b202 5b23
    0x00000d0: 8d05 1905 b602 5f57 2ab2 0262 238d 0519
    0x00000e0: 05b6 025f 572a b400 a8b6 0228 b202 2eb6
    0x00000f0: 0266 0303 b902 6c03 002a b202 6f23 8d05
    0x0000100: 1905 b602 5f57 2ab4 00a8 b602 28b2 022e
    0x0000110: b602 66b9 0272 0100 b802 0b11 1d00 b802
    0x0000120: 2211 0204 1302 73b8 0276 1117 00b8 0255
    0x0000130: b801 41b8 013a 2ab4 00af 1302 78b6 0146
    0x0000140: b802 7bb8 01ae 1103 0211 0303 0403 b801
    0x0000150: b22a 1905 1904 23b6 027f b802 0bb8 0239
    0x0000160: 2ab7 0282 1117 00b8 0255 b801 41b8 0213
    0x0000170: 1102 0413 0273 b802 762a b400 a8b6 0228
    0x0000180: b202 2eb6 0234 111d 01b8 0222 03b8 0201
    0x0000190: b801 3a2a b400 af13 0284 b601 46b8 01ae
    0x00001a0: 1103 0211 0303 0403 b801 b22a b202 8723
    0x00001b0: 8d05 1905 b602 5f57 b802 0bb8 0141 04b8
    0x00001c0: 0201 111d 00b8 0222 b802 13b1          
  Stackmap Table:
    same_frame_extended(@180)

	at com.github.lunatrius.schematica.proxy.ClientProxy.init(ClientProxy.java:182)
	at com.github.lunatrius.schematica.Schematica.init(Schematica.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3916877760 bytes (3735 MB) / 4281597952 bytes (4083 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms4096m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2426 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2426.jar) 
	UCHI	forge{14.21.1.2426} [Minecraft Forge] (forge-1.12-14.21.1.2426.jar) 
	UCHI	llor{1.1.4-mc1.12} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.4-mc1.12.jar) 
	UCHI	lunatriuscore{1.2.0.40} [LunatriusCore] (LunatriusCore-1.12-1.2.0.40-universal.jar) 
	UCHE	schematica{1.7.8.162} [Schematica] (Schematica-1.12-1.7.8.162-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.94' Renderer: 'GeForce GTX 765M/PCIe/SSE2'
```

**Comment by Lunatrius** [comment]
I'm not entirely sure what's going on. It looks almost like some kind of transformer failed.

Could you try running the game with a fresh Forge instance and only LunatriusCore and Schematica in the mods folder?

**Comment by Pervengue** [comment]
It's an compatibility issue... Forge bug when x-ray anschematica are present in the same file. The weird thing is that I tested bere posting (isolate mods, etc) but it still bugged... 

Dont bother you with it I will simply isate x-ray every time I want to use schematica...

**Comment by Lunatrius** [comment]
x-ray? There is no x-ray on the list of mods:
```
	UCHI	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2426.jar) 
	UCHI	forge{14.21.1.2426} [Minecraft Forge] (forge-1.12-14.21.1.2426.jar) 
	UCHI	llor{1.1.4-mc1.12} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.4-mc1.12.jar) 
	UCHI	lunatriuscore{1.2.0.40} [LunatriusCore] (LunatriusCore-1.12-1.2.0.40-universal.jar) 
	UCHE	schematica{1.7.8.162} [Schematica] (Schematica-1.12-1.7.8.162-universal.jar) 
```

**Comment by Lunatrius** [comment]
Oh, I see now, it's actually a tweaker.

I'd suggest reporting the issue to the author of the tweaker. My mod is probably just one of many that crash when installed together with that tweaker.
