### ISSUE TITLE
Schematica Causing Crashes

### ISSUE THREAD

**Issue by supermariojacob** [Lunatrius/Schematica#257]
Today I downloaded Forge, LunatriusCore, and Schematica for 1.12.1. I tried to start my Minecraft, but it keeps crashing and I believe it is because of Schematica. I have removed Schematica from my mods folder and when I do that, my Minecraft (with Forge and LunatriusCore) runs normally. 
If it helps with the problem, I am on a Mac.
Any help would be much appreciated! ^_^

```
Here is the crash report:
---- Minecraft Crash Report ----
// Don't do that.

Time: 8/27/17 8:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Schematica (schematica)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/GameData
	at com.github.lunatrius.schematica.handler.ConfigurationHandler.<clinit>(ConfigurationHandler.java:26)
	at com.github.lunatrius.schematica.proxy.CommonProxy.preInit(CommonProxy.java:44)
	at com.github.lunatrius.schematica.proxy.ClientProxy.preInit(ClientProxy.java:156)
	at com.github.lunatrius.schematica.Schematica.preInit(Schematica.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.GameData
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 162429144 bytes (154 MB) / 305086464 bytes (290 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.0.2463 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                        | Signature                                |
	|:----- |:----------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.1       | minecraft.jar                                 | None                                     |
	| UCH   | mcp               | 9.19         | minecraft.jar                                 | None                                     |
	| UCH   | FML               | 8.0.99.99    | forge-1.12.1-14.22.0.2463.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.22.0.2463 | forge-1.12.1-14.22.0.2463.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater | 1.0          | MercuriusUpdater-1.12.1.jar                   | None                                     |
	| UCH   | lunatriuscore     | 1.2.0.41     | LunatriusCore-1.12.1-1.2.0.41-universal.jar   | None                                     |
	| UCE   | schematica        | 1.8.0.164    | Schematica-1.12.1-1.8.0.164-universal (3).jar | None                                     |

```

**Comment by Pokechu22** [comment]
That crash doesn't seem to make any sense to me.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Schematica (schematica)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/GameData
	at com.github.lunatrius.schematica.handler.ConfigurationHandler.<clinit>(ConfigurationHandler.java:26)
	... more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.GameData
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
```

I don't get why the static initializer (`<clinit>`) for `ConfigurationHandler` would try to load `net/minecraftforge/fml/common/registry/GameData`.  That class was removed in MinecraftForge/MinecraftForge@a26d89c876d1cbfee31825354b40f67c6e6f6b0f (replaced with `net/minecraftforge/registries/GameData.java`).  But schematica doesn't reference either of them as far as I can tell.  I don't have any advice.

**Comment by Lunatrius** [comment]
Check your mod folder. You most likely have two version of Schematica in the mod folder.

**Comment by supermariojacob** [comment]
Looks like that was the problem! I also had a 1.9 Schematica in my mods folder, I took it out, started my game, and it started like normal!

Thank you so much for your help Lunatrius, I really appreciate it! Keep up the awesome work on Schematica! :)
