### ISSUE TITLE
Schematica Crashing

### ISSUE THREAD

**Issue by ChezThunderDash** [Lunatrius/Schematica#267]
At first, I was trying to load a schematic and as it was loading it crashed. 
After a few trys it started to act up trying to make a schematic, to the point I can't save a 1x1 block. 
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/25/17 5:02 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.ViewFrustum.func_178161_a(Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/client/renderer/chunk/RenderChunk; from class com.github.lunatrius.schematica.client.renderer.RenderSchematic
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174970_a(RenderSchematic.java:574)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:341)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:160)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1425)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1057)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174970_a(RenderSchematic.java:574)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:341)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:160)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1425)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ChezThunderDash'/0, l='MpServer', x=265.54, y=77.61, z=783.51]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (358,4,793), Chunk: (at 6,0,9 in 22,49; contains blocks 352,0,784 to 367,255,799), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 87501 game time, 87501 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['ChezThunderDash'/0, l='MpServer', x=265.54, y=77.61, z=783.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 153937696 bytes (146 MB) / 591921152 bytes (564 MB) up to 954728448 bytes (910 MB)
	LiteLoader Brand: 1.12.1-SNAPSHOT-r98DC04C-b3-3
	LiteLoader Mods: none
	LaunchWrapper: 22 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.0.2462 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID            | Version      | Source                                  | Signature                                |
	|:--------- |:------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft     | 1.12.1       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp           | 9.19         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML           | 8.0.99.99    | forge-1.12.1-14.22.0.2462-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge         | 14.22.0.2462 | forge-1.12.1-14.22.0.2462-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | lunatriuscore | 1.2.0.41     | minecraft.jar                           | None                                     |
	| UCHIJAAAA | schematica    | 1.8.0.164    | minecraft.jar                           | None                                     |
	| UCHIJAAAA | worldedit     | 6.1.8        | minecraft.jar                           | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
```
I'm sure it's probably a common error that can be fixed, but keep in mind I'm using MultiMC since the regular launcher doesn't launch correctly.

**Comment by Pokechu22** [comment]
Looks like access transformers failed to apply.

> ```
> | UCHIJAAAA | lunatriuscore | 1.2.0.41     | minecraft.jar                           | None                                     |
> | UCHIJAAAA | schematica    | 1.8.0.164    | minecraft.jar                           | None                                     |
> | UCHIJAAAA | worldedit     | 6.1.8        | minecraft.jar                           | None                                     |
> ```

Did you add the mod via "add jar mod" in multimc?  That's the wrong option to use (it's intended for base edits, which are relatively rare nowadays); you want the normal add mod option.

**Comment by ChezThunderDash** [comment]
Ok, thank you

**Comment by Lunatrius** [comment]
Adding the mods via the `Install mods` buttons should have fixed the issue. If it didn't feel free to re-open the issue.
