### ISSUE TITLE
CRASH: Game crashes when closing a world with a Schematic loaded.

### ISSUE THREAD

**Issue by isaiahshiner** [Lunatrius/Schematica#278]
Minecraft 1.12.2
Forge 14.23.0.2491

Saved a fairly large 300x300 schematic. Tried to print parts of it so that I could modify it and save it again. Loading and moving the schematic was fine, and rendering was fine, though a bit slow. Printer did not work at all, even for simple blocks. Upon closing the world, the game crashed.

java.lang.NullPointerException: Batching chunks
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:41)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:65)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

[Full Crash Report Here](https://pastebin.com/UbDqyKmy)

**Comment by Pokechu22** [comment]
Interesting.  Same stack trace as in #266 (barring a line number difference probably from different MC versions)

**Comment by Lunatrius** [comment]
Interesting. If rendering was slow and the printer didn't work at all the game was most likely overloaded with something. Once you closed the game, the rendering was still running, but the schematic itself unloads on a "world close", so the stacktrace makes sense in this case: the schematic is no longer loaded, which is why it's getting a null `BlockPos`.

Have to check if it's the schematic size that's making the mod/game run slow or if there's a bug.

**Comment by isaiahshiner** [comment]
Ah, well to be more specific about the schematic. Its about 300x300 blocks wide, and includes about 20 blocks of natural terrain, and, most importantly... my entire base, including all chests and the witch farm. those things do NOT need to be in the final schematic, and a way to not include them would be helpful. But I do need things at the same y level so I can't just go above them.

[301x301 Scaffolding.zip](https://github.com/Lunatrius/Schematica/files/1384730/301x301.Scaffolding.zip)

The whole schematic is basically just scaffolding for building [this machine](https://youtu.be/cN8xdCCyl4o). The Netherrack represents where exactly the different parts should be built, and the top facing slabs at the very edges represent the edges of the 301x301 perimeter.

**Comment by isaiahshiner** [comment]
Problem is more or less fixed. I was able to select higher up by adding additional marker blocks, which skipped the chests. The game no longer crashed and the printer worked fine. 

I guess the answer to this bug then is: Works as intended, don't select lots of chests with complex NBT Data and expect it to run smoothly. Some kind of warning would be nice, or rather, when chests are copied, have an option to ignore NBT data or skip the chests altogether.

**Comment by Lunatrius** [comment]
That's not it. Schematica doesn't and can't save chest contents. I'll try to investigate it as soon as I have the time.

**Comment by isaiahshiner** [comment]
Hmmmm... Well I'm sure you're busy, so I'll try to reproduce it and get more specific results about what it was.

**Comment by MokahTGS** [comment]
I got a crash when unloading a larger schematic:  https://pastebin.com/K39jFPAq

Not sure if this is the same thing.

**Comment by Pokechu22** [comment]
That appears to be the same crash as #266, which is related to this.

**Comment by Lunatrius** [comment]
What really sticks out in the crash log is the following line
```
    at ChunkCacheOF.func_180495_p(ChunkCacheOF.java:144)
```

Which makes me believe that it's Optifine doing something weird (because of the "OF" in the name, could be just a coincidence).
