### ISSUE TITLE
FTB Crashes upon loading Schematic

### ISSUE THREAD

**Issue by IMaxwellI** [Lunatrius/Schematica#286]
Hey. I got a slight problem.
I have made a schematic which covers 9 chunks which actually shouldn't be a problem considering that there wasn't meantioned a maximum size.
So, the Errorlog is a bit large and I don't quite know what to do about it. I hope you / someone can help me.
Thanks and take care!

Error Log on Pastebin, because it was too large for this thread.
https://pastebin.com/Va58Xbvg

**Comment by IMaxwellI** [comment]
Maybe I should add that it only happens with larger Schematics. Schematics covering only like 2 chunks, it works completely fine.

**Comment by IMaxwellI** [comment]
UPDATE:
I maybe found the problem... I think schematics lets minecraft crash, if you have too many blocks in them, that aren't vanilla blocks. My schematic with 4 carpenter blocks loads but if I want to load a schematic with 16x16 carpenterblocks, it crashed already after pressing "load", it doesn't even load something (which it at least does with my problem schematic mentioned in ym first thread up there

**Comment by IMaxwellI** [comment]
UPDATE 2:
It seems like that was the problem. Schematica seems not crash when it has to handle too many carpenter blocks. 4 seem to be ok, but with a square of 16x16, it crahses. You can already see it, because if you set your markers for saving the square, the red and blue point don't have colors anymore, but are matt grey.

**Comment by Lunatrius** [comment]
The game eventually crashes with "already tessellating", but before that, there's a LOT of these errors (stack traces get suppressed after a while):

```
[14:03:15] [Client thread/ERROR] [Schematica]: Failed to render block!
java.lang.NullPointerException
    at net.minecraft.world.World.func_147463_c(World.java:3047) ~[ahb.class:?]
    at net.minecraft.world.World.func_147451_t(World.java:2974) ~[ahb.class:?]
    at com.carpentersblocks.tileentity.TEBase.updateCachedLighting(TEBase.java:570) ~[TEBase.class:?]
    at com.carpentersblocks.tileentity.TEBase.getLightValue(TEBase.java:511) ~[TEBase.class:?]
    at com.carpentersblocks.block.BlockCoverable.getLightValue(BlockCoverable.java:741) ~[BlockCoverable.class:?]
    at net.minecraft.block.Block.func_149677_c(Block.java:528) ~[aji.class:?]
    at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6025) ~[blm.class:?]
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247) ~[blm.class:?]
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255) ~[blm.class:?]
    at com.github.lunatrius.schematica.client.renderer.RendererSchematicChunk.renderBlocks(RendererSchematicChunk.java:323) [RendererSchematicChunk.class:?]
    at com.github.lunatrius.schematica.client.renderer.RendererSchematicChunk.updateRenderer(RendererSchematicChunk.java:139) [RendererSchematicChunk.class:?]
    at com.github.lunatrius.schematica.client.renderer.RendererSchematicGlobal.sortAndUpdate(RendererSchematicGlobal.java:164) [RendererSchematicGlobal.class:?]
    at com.github.lunatrius.schematica.client.renderer.RendererSchematicGlobal.render(RendererSchematicGlobal.java:70) [RendererSchematicGlobal.class:?]
    at com.github.lunatrius.schematica.client.renderer.RendererSchematicGlobal.onRender(RendererSchematicGlobal.java:42) [RendererSchematicGlobal.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1209_RendererSchematicGlobal_onRender_RenderWorldLastEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261) [ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1354) [blt.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015) [blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

I'm not entirely sure what's going on there. Carpenter blocks most likely expect something to be initialized that's not in the context of the schematic.

Since this is 1.7.10 I won't be trying to fix it. The codebase changed too much between the versions.

**Comment by IMaxwellI** [comment]
Noticed that I forgot to mention the Version, sorry for that.
Still thank you very much for looking through this issue! 
I'll just use less to none Carpenter Blocks in my schematics now since that seems to be the only issue.

Thank you very much again and have a great day!
