### ISSUE TITLE
Factions Server Printing Crash

### ISSUE THREAD

**Issue by FoamyTheFag** [Lunatrius/Schematica#305]
I know that printer is supported on the server, as it plays a major role in factions and the administration is aware of it. When printing in a cactus farm, I got this error code:
`The game crashed whilst tesselating block in world
The game crashed whilst tesselating block in world
Error: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockState{block=minecraft:air, properties=[]}`
Thanks in advance, Foamy.

**Comment by Lunatrius** [comment]
Do you have any other mods installed?

**Comment by FoamyTheFag** [comment]
Map Writer, Chunkborders, Lighting fix, Macro mod, World Downloader, Mouse Delay Fix, Optifine.
Using Forge+Liteloader

**Comment by Pokechu22** [comment]
Please upload the full crash report.

**Comment by FoamyTheFag** [comment]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (MouseDelayFix-1.0.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 2/10/18 10:00 PM
Description: Tesselating block in world

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
	at net.minecraft.block.BlockTripWire.func_180654_a(SourceFile:94)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:60)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:259)
	at com.github.lunatrius.schematica.client.renderer.chunk.proxy.SchematicRenderChunkList.func_178581_b(SchematicRenderChunkList.java:46)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
	at net.minecraft.block.BlockTripWire.func_180654_a(SourceFile:94)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:60)

-- Block being tesselated --
Details:
	Block type: ID #132 (tile.tripWire // net.minecraft.block.BlockTripWire)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (12,83,10), Chunk: (at 12,5,10 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Foamy'/26563043, l='MpServer', x=9865.50, y=99.86, z=-9857.56], EntityOtherPlayerMP['CaptainScoobs'/28555094, l='MpServer', x=9873.29, y=201.18, z=-9856.70]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 9992.00,57.00,-9990.00 - World: (9992,57,-9990), Chunk: (at 8,3,10 in 624,-625; contains blocks 9984,0,-10000 to 9999,255,-9985), Region: (19,-20; contains chunks 608,-640 to 639,-609, blocks 9728,0,-10240 to 10239,255,-9729)
	Level time: 3227137 game time, 3307503 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityPlayerSP['Foamy'/26563043, l='MpServer', x=9865.50, y=99.86, z=-9857.56], EntityItem['item.tile.cactus'/29385600, l='MpServer', x=9877.47, y=191.22, z=-9865.49], EntityItem['item.tile.cactus'/29376385, l='MpServer', x=9877.88, y=20.00, z=-9865.13], EntityItem['item.tile.cactus'/29378626, l='MpServer', x=9884.84, y=20.00, z=-9861.28], EntityItem['item.tile.cactus'/29385474, l='MpServer', x=9872.13, y=105.24, z=-9869.60], EntityItem['item.tile.cactus'/29385602, l='MpServer', x=9869.41, y=125.25, z=-9866.88], EntityItem['item.tile.cactus'/29305083, l='MpServer', x=9883.88, y=20.00, z=-9852.03], EntityItem['item.item.spiderEye'/29271152, l='MpServer', x=9873.84, y=21.00, z=-9857.56], EntityItem['item.tile.cactus'/29300720, l='MpServer', x=9867.00, y=21.00, z=-9862.72], EntityItem['item.tile.cactus'/29360110, l='MpServer', x=9871.09, y=20.00, z=-9885.88], EntityItem['item.tile.cactus'/29286829, l='MpServer', x=9879.28, y=20.00, z=-9869.13], EntityItem['item.tile.cactus'/29385235, l='MpServer', x=9868.87, y=156.16, z=-9879.25], EntityItem['item.tile.cactus'/29380372, l='MpServer', x=9868.41, y=20.00, z=-9876.09], EntityItem['item.tile.cactus'/29354154, l='MpServer', x=9869.88, y=20.00, z=-9869.13], EntityItem['item.tile.cactus'/29267237, l='MpServer', x=9866.41, y=20.00, z=-9884.41], EntityItem['item.tile.cactus'/29291234, l='MpServer', x=9885.88, y=20.00, z=-9857.13], EntityItem['item.tile.cactus'/29385948, l='MpServer', x=9883.34, y=186.01, z=-9863.51], EntityItem['item.tile.cactus'/29385949, l='MpServer', x=9871.88, y=28.07, z=-9864.43], EntityItem['item.tile.cactus'/29377952, l='MpServer', x=9878.88, y=20.00, z=-9861.13], EntityItem['item.tile.cactus'/29385892, l='MpServer', x=9879.13, y=115.94, z=-9868.92], EntityOtherPlayerMP['CaptainScoobs'/28555094, l='MpServer', x=9873.29, y=201.18, z=-9856.70], EntityItem['item.tile.cactus'/29386344, l='MpServer', x=9873.13, y=96.71, z=-9870.58], EntityItem['item.tile.cactus'/29370988, l='MpServer', x=9877.00, y=20.00, z=-9851.31], EntityItem['item.tile.cactus'/29371692, l='MpServer', x=9880.88, y=20.00, z=-9850.75], EntityOtherPlayerMP['CaptainScoobs'/28555094, l='MpServer', x=9873.29, y=201.18, z=-9856.70], EntityItem['item.tile.cactus'/29382765, l='MpServer', x=9873.13, y=21.00, z=-9857.13], EntityItem['item.tile.cactus'/29374897, l='MpServer', x=9868.47, y=20.00, z=-9878.88], EntityItem['item.tile.cactus'/29386033, l='MpServer', x=9872.80, y=56.56, z=-9871.40], EntityItem['item.tile.cactus'/29383026, l='MpServer', x=9885.88, y=20.00, z=-9871.94], EntityItem['item.tile.cactus'/29386034, l='MpServer', x=9885.17, y=106.56, z=-9860.90], EntityItem['item.tile.cactus'/29353610, l='MpServer', x=9882.53, y=20.00, z=-9869.53], EntityItem['item.tile.cactus'/29282502, l='MpServer', x=9885.88, y=20.00, z=-9867.13]]
	Retry entities: 0 total; []
	Server brand: ApplePie
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 375072704 bytes (357 MB) / 1611190272 bytes (1536 MB) up to 2040135680 bytes (1945 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 Optifine OptiFine_1.8_HD_U_I3 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJA	mousedelayfix{1.0} [MouseDelayFix] (minecraft.jar) 
	UCHIJA	LunatriusCore{1.1.2.30} [LunatriusCore] (LunatriusCore-1.8-1.1.2.30-universal.jar) 
	UCHIJA	MapWriter{2.2.11} [MapWriter] (Mapwriter-2-Mod-1.8.jar) 
	UCHIJA	Schematica{1.7.7.140} [Schematica] (Schematica-1.8-1.7.7.140-universal (1).jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  io.prplz.mousedelayfix.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Aqumms Rose Gold Texture Pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	OptiFine Version: OptiFine_1.8_HD_U_I3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by Pokechu22** [comment]
Minecraft 1.8 is no longer supported.  Please update to a supported version (namely, 1.12.2); at minimum use 1.8.9 instead because there are a number of important bugfixes in between.  This goes for both Schematica and WDL.

My immediate guess is that this is the same issue as #295, namely the forge issue MinecraftForge/MinecraftForge#3924.  The only fix is to update forge.  There is no updated forge for horribly outdated MC versions such as 1.8; only for 1.12.
