### ISSUE TITLE
Minecraft crashing when loading a schematic underground

### ISSUE THREAD

**Issue by admadmax** [Lunatrius/Schematica#309]
Hi, here is the bug report : on the surface, the shematic works well but when I'm trying to put it underground, my minecraft crashes :/ I'm using the 1.7.7.143 version of schematica. I created the schematic with world edit (about 20000 blocks), and when I'm using another schematic it doesn't crash

Thank you for your help <3

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 22/02/18 11:53
Description: Batching chunks

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.putFloat(Unknown Source)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:134)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)
	at com.github.lunatrius.schematica.client.renderer.chunk.overlay.RenderOverlay.func_178581_b(RenderOverlay.java:136)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.putFloat(Unknown Source)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:134)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Morgenstern'/5256689, l='MpServer', x=16300,33, y=8,00, z=-9452,72]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 16286,00,6,00,-9435,00 - World: (16286,6,-9435), Chunk: (at 14,0,5 in 1017,-590; contains blocks 16272,0,-9440 to 16287,255,-9425), Region: (31,-19; contains chunks 992,-608 to 1023,-577, blocks 15872,0,-9728 to 16383,255,-9217)
	Level time: 39311131 game time, 40360041 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 10 total; [EntityZombie['Zombie'/24417104, l='MpServer', x=16286,50, y=43,00, z=-9422,50], EntitySpider['Spider'/24430320, l='MpServer', x=16316,50, y=71,00, z=-9437,50], EntityCow['Cow'/24417107, l='MpServer', x=16316,97, y=74,00, z=-9474,94], EntityCow['Cow'/24417100, l='MpServer', x=16292,59, y=6,00, z=-9467,47], EntityZombie['Zombie'/24417101, l='MpServer', x=16285,50, y=43,00, z=-9426,50], EntitySkeleton['Skeleton'/24417102, l='MpServer', x=16311,50, y=11,00, z=-9428,50], EntityZombie['Zombie'/24417103, l='MpServer', x=16287,50, y=43,00, z=-9420,50], EntityHorse['Horse'/24417112, l='MpServer', x=16330,41, y=74,00, z=-9471,50], EntityPlayerSP['Morgenstern'/5256689, l='MpServer', x=16300,33, y=8,00, z=-9452,72], EntityCow['Cow'/24417099, l='MpServer', x=16275,97, y=72,00, z=-9450,09]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.9-SNAPSHOT:ec48077:1157) <- PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 262478712 bytes (250 MB) / 439726080 bytes (419 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1744 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1744.jar) 
	UCHIJA	Forge{11.15.1.1744} [Minecraft Forge] (forge-1.8.9-11.15.1.1744.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJA	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	UCHIJA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1744
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
```

**Comment by admadmax** [comment]
xD
Update : it worked
I think the chunk wasn't loaded so it crashed
Thank your for your work anyway <3

**Comment by Lunatrius** [comment]
This bug was fixed in a later version of the mod. Moving huge schematics into huge masses of lands caused this crash.
