### ISSUE TITLE
[1.12.2] Crash Pressing Materials Button in GUI

### ISSUE THREAD

**Issue by MokahTGS** [Lunatrius/Schematica#310]
We are getting a crash when the Materials button is pressed.

https://pastebin.com/vZk7rhX0

Schematica 1.8.0.1.6.8
LunatrisCore 1.2.0.4.2
Forge 2611

**Comment by Pokechu22** [comment]
Looks like a mod returned a null itemstack for `block.getPickBlock`, when it should have returned `ItemStack.EMPTY`.  Unfortunately it's not clear which one did that.

**Comment by Lunatrius** [comment]
Upload the schematic, it contains the pallette of all blocks in the schematic, so we can narrow down the list of mods significantly.

**Comment by MokahTGS** [comment]
Ah well I can tell you its either chisel or biomes o plenty since those were the only mod blocks in the schematic.

**Comment by MokahTGS** [comment]
So this happens with any schematic when the materials button is pressed.  Has nothing to do with modded blocks.

**Comment by Lunatrius** [comment]
If it happens with vanilla blocks only it's most likely a core mod doing something that it shouldn't be doing.

**Comment by Darkkender** [comment]
This is not just a limited instance.  I have been having these errors all day today.  No matter which Schematic I load if I click on the Materials button it crashes my game.

[crash-2018-03-25_21.05.58-client.txt](https://github.com/Lunatrius/Schematica/files/1846293/crash-2018-03-25_21.05.58-client.txt)

**Comment by Lunatrius** [comment]
Please remove all core mods and the mods that depend on them, then try again. I am almost 100% sure that this is a (core) mod doing stuff wrong (returning `null` instead of `ItemStack.EMPTY`).

**Comment by Darkkender** [comment]
So over the course of the last 2 days I have isolated numerous core mod packs that are generating this crash.  FTB, JAOPCA, JEI, & Mekanism I have consistently being having this result on.  However there has even been points where the only thing I had running was Biomes O' Plenty and Journey Map.  

Among the other fatal crashes that have been happening have also been crashes when attempting to unload the schematics. 

snipped from error log:
Description: Batching chunks

java.lang.NullPointerException: Batching chunks
	at com.github.lunatrius.schematica.client.renderer.SchematicRenderCache.func_180495_p(SchematicRenderCache.java:21)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:157)
	at com.github.lunatrius.schematica.client.renderer.chunk.proxy.SchematicRenderChunkVbo.func_178581_b(SchematicRenderChunkVbo.java:51)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

I cannot disagree that there are some incompatibilities with other mods.  However with as many mods are encountering this as well as players there might be a enough of a change in the recent 1.12.2 for you to double check that your code doesn't have a few holes or at least can handle null pointer references better.

**Comment by Lunatrius** [comment]
I'll try to add some additional checks for null values this weekend, where things might actually be null under special conditions.

**Comment by Darkkender** [comment]
Awesome, thank you.

**Comment by GreenGhost21** [comment]
Has any progress been made on this? I too am getting the same issue.
