### ISSUE TITLE
Game Crashes ~4 seconds after Loading a schematic

### ISSUE THREAD

**Issue by TheSaltyPug** [Lunatrius/Schematica#348]
**Mod version:** 1.12.2-1.8.0.169
**Forge version:** 14.23.4.2707
**Operating system:** Windows 10
**Mod list:**
     - AppleSkin
     - Inventory Tweaks
     - JEI Villagers
     - JEI
     - JourneyMap
     - Light Level Overlay Reloaded
     - LunatriusCore
     - Mouse Tweaks
     - Optifine (1.12.2 HD U D3)
     - Schematica

**Crash Report**
[https://pastebin.com/GgctTL4G](url)

Titles says it-- I load a schematic, I see the ghost blocks, I move around a bit, and the game crashes after 3-5 seconds. Can replicate.

**Comment by Lunatrius** [comment]
That is just the crash log, not the complete log file.

First I would suggest to try removing Optifine to see whether or not the issue persists. If that doesn't work, try using it in a separate instance with just LunatriusCore and Schematica installed.

**Comment by AmyMialee** [comment]
I had the same problem, removed Optifine, didn't crash.
I'll try messing around with specific graphics settings tomorrow.

One thing I noticed is that I have the mod Chunk Animator installed, and that didn't show up with optifine, and when optifine was removed it did. However, chunk animator did affect the schematic before the crash when optifine was still installed. Not sure if this matters but might as well mention it.

**Comment by Lunatrius** [comment]
Also, what is the size of the schematic that you're loading (assuming that it's the same error)?

**Comment by AmyMialee** [comment]
I tried a pretty big one and a small one, same problem.
However, I found out that the specific option in optifine causing the crash was render regions, as when it was disabled there was no crash. But now I have a new problem, as seen in the screenshot, where the textures on the schematic were very messed up
![2018-07-03_12 18 57](https://user-images.githubusercontent.com/10999535/42216912-50330e2c-7ebb-11e8-929e-1039e8369620.png)
This also was not present without Optifine, and effected schematics of all sizes.
.

**Comment by Lunatrius** [comment]
That one happens because Optifine changes the vertex format without changing the data itself.

**Comment by AmyMialee** [comment]
is there any way to fix it without removing either mod?

**Comment by Lunatrius** [comment]
Try turning VBOs on/off in the settings, it might help in this case.

**Comment by AmyMialee** [comment]
I turned off VBOs and now everything is working fine, thanks a ton

**Comment by Lunatrius** [comment]
I'm still not sure what could possibly cause this issue with Optifine present... I'm not changing any of the vertex formats at any point and I'm using vanilla rendering. Sigh...

**Comment by AmyMialee** [comment]
atleast you know its VBOs and Render Regions causing the issue between
optifine and schematica

**Comment by repairmant** [comment]
Thanx aton guys this helped me aton.

**Comment by pyrogcode** [comment]
ty helped me a lot

**Comment by taykomaisle2** [comment]
hi my logs : ---- Minecraft Crash Report ----

WARNING: coremods are present:
Plugin (NotEnoughIDs-1.5.4.4.jar)
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/15/22 4:25 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 0
at com.dyn.schematics.Schematic.readFromNBT(Schematic.java:445)
at com.dyn.schematics.registry.SchematicRegistry.load(SchematicRegistry.java:51)
at com.dyn.schematics.item.ItemSchematic.func_150895_a(ItemSchematic.java:121)
at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:587)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at com.dyn.schematics.Schematic.readFromNBT(Schematic.java:445)
at com.dyn.schematics.registry.SchematicRegistry.load(SchematicRegistry.java:51)
at com.dyn.schematics.item.ItemSchematic.func_150895_a(ItemSchematic.java:121)
at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:587)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 535507320 bytes (510 MB) / 2986344448 bytes (2848 MB) up to 4294967296 bytes (4096 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 17 mods loaded, 17 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID                               | Version      | Source                                      | Signature                                |
|:----- |:-------------------------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
| LCH   | minecraft                        | 1.12.2       | minecraft.jar                               | None                                     |
| LCH   | mcp                              | 9.42         | minecraft.jar                               | None                                     |
| LCH   | FML                              | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCH   | forge                            | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCH   | cocricotmod                      | 1.10.3       | cocricotMOD for 1.12.2 v1.10.3.jar          | None                                     |
| LCH   | ptrmodellib                      | 1.0.5        | PTRLib-1.0.5.jar                            | None                                     |
| LCH   | props                            | 2.6.3.7      | Decocraft-2.6.3.7_1.12.2.jar                | None                                     |
| LCH   | effortlessbuilding               | 1.12.2-2.13  | effortlessbuilding-1.12.2-2.13.jar          | None                                     |
| LCH   | essensialmodernconstructionblock | 1.1.0        | EMCB+HD+1.12.2+v1.1.0.jar                   | None                                     |
| LCH   | jei                              | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar                   | None                                     |
| LCH   | lunatriuscore                    | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
| LCH   | mcef                             | 0.9          | MCEF-1.12.2.jar                             | None                                     |
| LCH   | neid                             | 1.5.4.4      | NotEnoughIDs-1.5.4.4.jar                    | None                                     |
| LCH   | schematica                       | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |
| LCH   | schematics                       | 1.12.2.12    | Schematics-1.12.2.12.jar                    | None                                     |
| LCH   | webdisplays                      | 1.0          | Web-Displays-Mod-1.12.2 (1).jar             | None                                     |
| LCH   | worldedit                        | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar       | None                                     |

Loaded coremods (and transformers): 
Plugin (NotEnoughIDs-1.5.4.4.jar)
ru.fewizz.neid.asm.Transformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
net.montoyo.mcef.coremod.ShutdownPatcher
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.10.2 30.0.13025.5005' Renderer: 'Radeon RX 580 Series'
Launched Version: 1.12.2-forge-14.23.5.2860
LWJGL: 2.9.4
OpenGL: Radeon RX 580 Series GL version 4.6.14761 Compatibility Profile Context 21.10.2 30.0.13025.5005, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: cocricot
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 6x AMD Ryzen 5 3500X 6-Core Processor 
OptiFine Version: OptiFine_1.12.2_HD_U_G5
OptiFine Build: 20210124-142939
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: Sildur's+Vibrant+Shaders+v1.32+High-MB (1).zip
OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.10.2 30.0.13025.5005
OpenGlRenderer: Radeon RX 580 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 6

**Comment by AmyMialee** [comment]
My rec is uninstall optifine.

**Comment by MoodDQ32614** [comment]
У меня при загрузке схематики не вылетает, но как только я пытаюсь её разместить, то Майнкрафт моментально крашит, подскажите в чём проблема
Вот краш лог
|Kotlin For Forge |kotlinforforge |3.12.0 |DONE |Manifest: NOSIGNATURE 
  forge-1.18.2-40.2.4-universal.jar |Forge |forge |40.2.4 |DONE |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 
  appleskin-forge-mc1.18.2-2.4.1.jar |AppleSkin |appleskin |2.4.1+mc1.18.2 |DONE |Manifest: NOSIGNATURE 
  tl_skin_cape_forge_1.18_1.18.2-1.25.jar |TLSkinCape |tlskincape |1.25 |DONE |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a 
  Mantle-1.18.2-1.9.45.jar |Mantle |mantle |1.9.45 |DONE |Manifest: NOSIGNATURE 
  journeymap-1.18.2-5.9.7-forge.jar |Journeymap |journeymap |5.9.7 |DONE |Manifest: NOSIGNATURE 
 Crash Report UUID: 65c538b2-f8e2-4b7e-bc13-08047e1c20b9 
 FML: 40.2 
 Forge: net.minecraftforge:40.2.4 
[19:16:83] [Render thread/FATAL]: Preparing crash report with UUID 38c8dd9e-f4a8-440c-9a71-d248d8508d42 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\пїЅпїЅпїЅ\AppData\Roaming\.minecraft\versions\hhhhh\crash-reports\crash-2023-06-10_19.16.44-client.txt 
AL lib: (EE) alc_cleanup: 1 device not closed 
Here I am! 
[VersionManager] Refreshing versions locally... 
[VersionManager] Versions has been refreshed (11828 ms) 
[Launcher] Minecraft closed with exit code: -1 
flush now 
[Launcher] Launcher exited. 
[Launcher] [Crash] Found crash report file: C:\Users\РїС—Р…РїС—Р…РїС—Р…\AppData\Roaming\.minecraft\versions\hhhhh\crash-reports\crash-2023-06-10_19.05.56-client.txt 
[Crash] Found crash report file: C:\Users\РїС—Р…РїС—Р…РїС—Р…\AppData\Roaming\.minecraft\versions\hhhhh\crash-reports\crash-2023-06-10_19.05.56-client.txt 
[Launcher] [Crash] Found crash report file: C:\Users\РїС—Р…РїС—Р…РїС—Р…\AppData\Roaming\.minecraft\versions\hhhhh\crash-reports\crash-2023-06-10_19.16.44-client.txt 
[Crash] Found crash report file: C:\Users\РїС—Р…РїС—Р…РїС—Р…\AppData\Roaming\.minecraft\versions\hhhhh\crash-reports\crash-2023-06-10_19.16.44-client.txt 
flush now
[Ссылка]
TLauncher — Скачать лаунчер Майнкрафт
https://tlauncher.org/
