### ISSUE TITLE
Everytime I load a schematic, it crashes and says "The game crashed whilst tesselating block model" SP and MP

### ISSUE THREAD

**Issue by Scorpiee** [Lunatrius/Schematica#370]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 8/3/18 3:26 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at net.minecraft.block.BlockShulkerBox.func_193383_a(SourceFile:345)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_193401_d(BlockStateContainer.java:535)
	at net.minecraft.block.BlockPane.func_193393_b(BlockPane.java:145)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:216)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:116)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:427)
	at ConnectedTextures.skipConnectedTexture(ConnectedTextures.java:147)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:105)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:107)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:61)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:162)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:68)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:78)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:57)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:327)
	at com.github.lunatrius.schematica.client.renderer.chunk.proxy.SchematicRenderChunkVbo.func_178581_b(SchematicRenderChunkVbo.java:51)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.BlockShulkerBox.func_193383_a(SourceFile:345)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_193401_d(BlockStateContainer.java:535)
	at net.minecraft.block.BlockPane.func_193393_b(BlockPane.java:145)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:216)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:116)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:427)
	at ConnectedTextures.skipConnectedTexture(ConnectedTextures.java:147)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:105)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:107)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:61)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:162)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:68)

-- Block model being tesselated --
Details:
	Block: minecraft:glass_pane[east=true,north=false,south=false,west=true]
	Block location: World: (86,14,20), Chunk: (at 6,0,4 in 5,1; contains blocks 80,0,16 to 95,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:78)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:57)

-- Block being tesselated --
Details:
	Block type: ID #102 (tile.thinGlass // net.minecraft.block.BlockPane // minecraft:glass_pane)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (86,14,20), Chunk: (at 6,0,4 in 5,1; contains blocks 80,0,16 to 95,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:327)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Scorpie'/503698, l='MpServer', x=1670.26, y=64.00, z=-3399.74]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (3314,73,-373), Chunk: (at 2,4,11 in 207,-24; contains blocks 3312,0,-384 to 3327,255,-369), Region: (6,-1; contains chunks 192,-32 to 223,-1, blocks 3072,0,-512 to 3583,255,-1)
	Level time: 1297294642 game time, 1148382789 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityPlayerSP['Scorpie'/503698, l='MpServer', x=1670.26, y=64.00, z=-3399.74], EntityXPOrb['Experience Orb'/503702, l='MpServer', x=1658.09, y=64.00, z=-3396.34], EntitySquid['Squid'/503699, l='MpServer', x=1683.90, y=55.35, z=-3397.19]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 407280016 bytes (388 MB) / 889192448 bytes (848 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2747 Optifine OptiFine_1.12.2_HD_U_D3 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                          | Signature                                |
	|:------ |:------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft     | 1.12.2       | minecraft.jar                                   | None                                     |
	| UCHIJA | mcp           | 9.42         | minecraft.jar                                   | None                                     |
	| UCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.4.2747.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge         | 14.23.4.2747 | forge-1.12.2-14.23.4.2747.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | lunatriuscore | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal (1).jar | None                                     |
	| UCHIJA | schematica    | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal (2).jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2747
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Modern HD 1.12.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4703
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4
```
This is the error log for what happens whenever I try to load a schematic, I am running the newest version of forge for 1.12.2.

**Comment by Lunatrius** [comment]
Are you using a mod for connected textures? If so, please try removing it.

**Comment by Scorpiee** [comment]
Okay, that worked. Thank you, and sorry for the inconvenience.
