### ISSUE TITLE
Crashing on done

### ISSUE THREAD

**Issue by McMemer** [Lunatrius/Schematica#386]
Whenever I load a schematic and press done my screen freezes then after 2 seconds my screen goes to the loading a world screen and takes me back to my launcher where I am shown the crash report

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 9/18/18 4:42 PM
Description: Updating screen events

java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.BufferBuilder.<init>(BufferBuilder.java:81)
	at net.minecraft.client.renderer.RegionRenderCacheBuilder.<init>(SourceFile:19)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(ChunkRenderDispatcher.java:75)
	at com.github.lunatrius.schematica.client.renderer.chunk.OverlayRenderDispatcher.<init>(OverlayRenderDispatcher.java:25)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_72712_a(RenderSchematic.java:415)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.setWorldAndLoadRenderers(RenderSchematic.java:209)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:245)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:176)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:88)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:64)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:33)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.BufferBuilder.<init>(BufferBuilder.java:81)
	at net.minecraft.client.renderer.RegionRenderCacheBuilder.<init>(SourceFile:19)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.<init>(ChunkRenderDispatcher.java:75)
	at com.github.lunatrius.schematica.client.renderer.chunk.OverlayRenderDispatcher.<init>(OverlayRenderDispatcher.java:25)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_72712_a(RenderSchematic.java:415)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.setWorldAndLoadRenderers(RenderSchematic.java:209)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:245)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:176)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:88)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:64)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['McMemer'/20084, l='MpServer', x=-48998.54, y=117.00, z=-33999.16]]
	Chunk stats: MultiplayerChunkCache: 170, 170
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-49001,116,-34002), Chunk: (at 7,7,14 in -3063,-2126; contains blocks -49008,0,-34016 to -48993,255,-34001), Region: (-96,-67; contains chunks -3072,-2144 to -3041,-2113, blocks -49152,0,-34304 to -48641,255,-33793)
	Level time: 185587 game time, 100025587 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntitySkeleton['§fSkeleton§r§f§r: [§a||||||§c||||§f]'/1868665, l='MpServer', x=-48989.30, y=112.00, z=-33960.50], EntityPlayerSP['McMemer'/20084, l='MpServer', x=-48998.54, y=117.00, z=-33999.16], EntityChicken['Chicken'/1868660, l='MpServer', x=-49009.10, y=121.03, z=-33999.10], EntityChicken['§fChicken§r§f§r: [§a||||||||||§c§f]'/1868658, l='MpServer', x=-49009.10, y=120.96, z=-33999.10], EntityChicken['§fChicken§r§f§r: [§a||||||||||§c§f]'/1868659, l='MpServer', x=-49009.10, y=121.04, z=-33999.10]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.13-SNAPSHOT:9886021:1356) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:33)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 276142152 bytes (263 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_E2 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                      | Signature                                |
	|:------ |:------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft     | 1.12.2       | minecraft.jar                               | None                                     |
	| UCHIJA | mcp           | 9.42         | minecraft.jar                               | None                                     |
	| UCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge         | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | lunatriuscore | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| UCHIJA | schematica    | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13418 Compatibility Profile Context 15.301.2301.1002' Renderer: 'AMD Radeon(TM) R4 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.5.13418 Compatibility Profile Context 15.301.2301.1002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful+1.12.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-7310 APU with AMD Radeon R4 Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.13418 Compatibility Profile Context 15.301.2301.1002
	OpenGlRenderer: AMD Radeon(TM) R4 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```
HEEAPL ME

**Comment by Lunatrius** [comment]
You are running the game with 512 MB of RAM. Try increasing the amount of RAM for the game (1GB or 2 GB are more than sufficient) or lower the rendering distance.

**Comment by McMemer** [comment]
How do i do that...?

**Comment by Lunatrius** [comment]
It depends on the launcher that you're using. This video shows how to do it in the new launcher: https://youtu.be/zkoFuP8kKEs

**Comment by McMemer** [comment]
I use the old one just because i think its easier

**Comment by Lunatrius** [comment]
Which old one?

**Comment by McMemer** [comment]
One right before the new one

**Comment by Lunatrius** [comment]
In that case it should be in the `Options` menu if I remember the correct one.
