### ISSUE TITLE
Every time i tried to load a schem i crashed

### ISSUE THREAD

**Issue by fireworksmaniac** [Lunatrius/Schematica#397]
```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 30-10-18 11:12
Description: Batching chunks

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:120)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)
	at com.github.lunatrius.schematica.client.renderer.chunk.overlay.RenderOverlay.func_178581_b(RenderOverlay.java:136)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:120)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['fireworksmaniac'/5257, l='MpServer', x=1185,90, y=1,00, z=-4830,54]]
	Chunk stats: MultiplayerChunkCache: 82, 82
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 1196,00,116,00,-4800,00 - World: (1196,116,-4800), Chunk: (at 12,7,0 in 74,-300; contains blocks 1184,0,-4800 to 1199,255,-4785), Region: (2,-10; contains chunks 64,-320 to 95,-289, blocks 1024,0,-5120 to 1535,255,-4609)
	Level time: 182822 game time, 42054431 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 11 total; [EntityArmorStand['§d§l5x Spawner'/3312994, l='MpServer', x=1192,50, y=118,75, z=-4809,50], EntityPlayerSP['fireworksmaniac'/5257, l='MpServer', x=1185,90, y=1,00, z=-4830,54], EntityArmorStand['§d§l5x Spawner'/3312995, l='MpServer', x=1192,50, y=119,75, z=-4809,50], EntityArmorStand['§d§l5x Spawner'/3312992, l='MpServer', x=1192,50, y=116,75, z=-4809,50], EntityArmorStand['§d§l5x Spawner'/3312993, l='MpServer', x=1192,50, y=117,75, z=-4809,50], EntityArmorStand['§fLevel 0 §7- §bDiamond Generator'/3312998, l='MpServer', x=1210,50, y=117,06, z=-4799,50], EntityArmorStand['§7Cobblestone Generator'/3312996, l='MpServer', x=1210,50, y=117,06, z=-4801,50], EntityArmorStand['§fLevel 0 §7- §3Iron Generator'/3312997, l='MpServer', x=1212,50, y=117,06, z=-4801,50], EntityArmorStand['§7Cobblestone Generator'/3313002, l='MpServer', x=1212,50, y=117,06, z=-4799,50], EntityArmorStand['§fLevel 0 §7- §6Gold Generator'/3313000, l='MpServer', x=1208,50, y=117,06, z=-4799,50], EntityItem['item.tile.cactus'/3312991, l='MpServer', x=1174,47, y=134,00, z=-4805,03]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 200560776 bytes (191 MB) / 637534208 bytes (608 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal (1).jar) 
	UCHIJA	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal (1).jar) 
	Loaded coremods (and transformers): 
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
```

I tried changing the splash.properties to false, i tried turning off VBO, lowered framerate but everytime i login and try to load it still crashes. Please help.

**Comment by fireworksmaniac** [comment]
I tried it on multiple servers and they all crash

**Comment by Lunatrius** [comment]
What is the size of the schematic?

Where are you trying to load the schematic?

Does it load smaller schematics?

**Comment by fireworksmaniac** [comment]
It's one chunk, from 0 to 256, a cactusfarm. It is on a skyblock server. It worked before and it did not change anything. Also does not work in single player. Does also crash with smaller schematics.

**Comment by Lunatrius** [comment]
What are your surroundings that you are trying to load the schematic into? There was a bug where the mod crashed if you tried to load a schematic under water or other blocks (can't remember which ones exactly, could be glass).

**Comment by fireworksmaniac** [comment]
I skyblock island with a decent size cactusfarm of 3 chunks already. I downloaded a newer version on 1.9 and that's working so far. But because I like 1.8.9 more I would like to go back to that.

**Comment by Lunatrius** [comment]
Try turning on VBOs in the settings, to see if that improves anything.
