### ISSUE TITLE
When I load any schematic if I'm right I will crash

### ISSUE THREAD

**Issue by nicholascheam** [Lunatrius/Schematica#405]
This is the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (MemoryFix-0.3.jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  FMLLoadingPlugin (MouseDelayFix-1.0.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 11/29/18 10:35 AM
Description: Batching chunks

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:599)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:134)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)
	at com.github.lunatrius.schematica.client.renderer.chunk.overlay.RenderOverlay.func_178581_b(RenderOverlay.java:136)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:599)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:134)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['GoldAtom'/73036376, l='MpServer', x=4910.30, y=1.00, z=4848.30]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -2587.00,34.00,2111.00 - World: (-2587,34,2111), Chunk: (at 5,2,15 in -162,131; contains blocks -2592,0,2096 to -2577,255,2111), Region: (-6,4; contains chunks -192,128 to -161,159, blocks -3072,0,2048 to -2561,255,2559)
	Level time: 87375121 game time, 558217 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['GoldAtom'/73036376, l='MpServer', x=4910.30, y=1.00, z=4848.30]]
	Retry entities: 0 total; []
	Server brand: FrostSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:417)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2139773904 bytes (2040 MB) / 3140747264 bytes (2995 MB) up to 3140747264 bytes (2995 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I7 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	mousedelayfix{1.0} [MouseDelayFix] (minecraft.jar) 
	UCHIJA	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCHIJA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJA	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	UCHIJA	fpsdisplaymod{1.0} [FPSDisplayMod] ([1.8.9] CheatBreakerHUD v3.jar) 
	UCHIJA	cpsmod{1.0} [CPSMod] ([1.8.9] CheatBreakerHUD v3.jar) 
	UCHIJA	keystrokesmod{0.1} [KeystrokesMod] ([1.8.9] CheatBreakerHUD v3.jar) 
	UCHIJA	examplem0d{1.0} [Example Mod] ([1.8.9] KeystrokesMod v4 (1).jar) 
	UCHIJA	reachdisplaymod{1.0} [Reach Display Mod] ([1.8.9]ReachDisplayMod-1.0.jar) 
	UCHIJA	sidebarmod{1.01} [SidebarMod] ([1.8.9]SidebarMod-1.01.jar) 
	UCHIJA	autogg{2.0.4} [Auto GG] (AutoGG-2.0.4 (1.8.9).jar) 
	UCHIJA	autotip{2.0.3} [Autotip] (Autotip-2.0.3 [1.8-1.11.2].jar) 
	UCHIJA	customcrosshairmod{0.2.1-Forge} [Custom Crosshair Mod] (Custom-Crosshair-Mod-1.8.9.jar) 
	UCHIJA	memoryfix{0.3} [MemoryFix] (MemoryFix-0.3.jar) 
	UCHIJA	orangesimplemod{1.0} [orangesimplemod] (Orange's Simple Mods-1.2.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (MemoryFix-0.3.jar)
  io.prplz.memoryfix.ClassTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  io.prplz.mousedelayfix.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §3Aquatic 32x.zip
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4252
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by nicholascheam** [comment]
I have tried fixing it from another post but I just have no clue what I'm doing

**Comment by LewisYoYoYo** [comment]
i have the same issue
