### ISSUE TITLE
Crashing and Leading schematics issue

### ISSUE THREAD

**Issue by ckeeze** [Lunatrius/Schematica#408]
Whenever I try to load a schematic only colors ar shown and no block textures then after a minute or so it always crashes like this.
I tried re installing java, forge, minecraft, and the mods aswell several times. It works for 1 day then next they it starts to do this again.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 12/7/18 8:16 PM
Description: Unexpected error

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:384)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:181)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:384)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:181)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ckeeze'/251, l='MpServer', x=-125.78, y=5.17, z=634.26]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-90,4,623), Chunk: (at 6,0,15 in -6,38; contains blocks -96,0,608 to -81,255,623), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 349497 game time, 17734 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 79 total; [EntitySpider['Spider'/144, l='MpServer', x=-188.50, y=4.00, z=565.50], EntityCreeper['Creeper'/145, l='MpServer', x=-183.24, y=4.00, z=566.62], EntityCreeper['Creeper'/146, l='MpServer', x=-183.81, y=4.00, z=596.50], EntityCreeper['Creeper'/147, l='MpServer', x=-190.50, y=4.00, z=598.50], EntityCow['Cow'/148, l='MpServer', x=-182.15, y=4.00, z=631.78], EntityCreeper['Creeper'/149, l='MpServer', x=-187.50, y=4.00, z=637.50], EntitySpider['Spider'/150, l='MpServer', x=-175.99, y=4.00, z=641.44], EntitySkeleton['Skeleton'/151, l='MpServer', x=-195.17, y=4.00, z=649.83], EntityItem['item.item.egg'/152, l='MpServer', x=-176.92, y=4.00, z=684.31], EntityChicken['Chicken'/153, l='MpServer', x=-184.09, y=4.00, z=688.25], EntitySpider['Spider'/154, l='MpServer', x=-169.10, y=4.00, z=635.07], EntitySpider['Spider'/155, l='MpServer', x=-165.98, y=4.00, z=652.01], EntitySkeleton['Skeleton'/158, l='MpServer', x=-164.30, y=4.00, z=584.53], EntityZombie['Zombie'/159, l='MpServer', x=-155.22, y=4.00, z=604.38], EntityZombie['Zombie'/160, l='MpServer', x=-158.15, y=4.00, z=617.14], EntitySheep['Sheep'/161, l='MpServer', x=-157.71, y=4.00, z=630.97], EntityZombie['Zombie'/162, l='MpServer', x=-152.78, y=4.00, z=653.45], EntitySheep['Sheep'/164, l='MpServer', x=-130.74, y=4.00, z=606.21], EntitySheep['Sheep'/165, l='MpServer', x=-133.35, y=4.00, z=586.78], EntityZombie['Zombie'/166, l='MpServer', x=-141.19, y=4.00, z=591.81], EntityZombie['Zombie'/167, l='MpServer', x=-142.50, y=4.00, z=600.29], EntityCreeper['Creeper'/168, l='MpServer', x=-142.23, y=4.00, z=598.42], EntitySpider['Spider'/169, l='MpServer', x=-123.06, y=4.00, z=665.45], EntityCreeper['Creeper'/170, l='MpServer', x=-136.34, y=4.00, z=670.79], EntitySkeleton['Skeleton'/171, l='MpServer', x=-130.54, y=4.00, z=672.68], EntityZombie['Zombie'/172, l='MpServer', x=-129.50, y=4.00, z=678.50], EntityZombie['Zombie'/173, l='MpServer', x=-136.23, y=4.00, z=687.41], EntityCreeper['Creeper'/174, l='MpServer', x=-130.50, y=4.00, z=680.50], EntityZombie['Zombie'/175, l='MpServer', x=-129.67, y=4.00, z=683.83], EntitySkeleton['Skeleton'/176, l='MpServer', x=-128.50, y=4.00, z=695.50], EntityZombie['Zombie'/177, l='MpServer', x=-129.24, y=4.00, z=698.59], EntityZombie['Zombie'/178, l='MpServer', x=-141.19, y=4.00, z=707.19], EntitySpider['Spider'/179, l='MpServer', x=-127.94, y=4.00, z=566.07], EntityZombie['Zombie'/180, l='MpServer', x=-123.27, y=4.51, z=636.26], EntitySkeleton['Skeleton'/181, l='MpServer', x=-120.31, y=4.00, z=634.60], EntitySkeleton['Skeleton'/182, l='MpServer', x=-120.37, y=4.00, z=628.21], EntitySkeleton['Skeleton'/183, l='MpServer', x=-119.45, y=4.00, z=628.73], EntityZombie['Zombie'/184, l='MpServer', x=-110.53, y=4.00, z=646.22], EntitySlime['Slime'/185, l='MpServer', x=-109.17, y=4.00, z=648.28], EntitySkeleton['Skeleton'/186, l='MpServer', x=-109.75, y=4.00, z=661.33], EntityCreeper['Creeper'/187, l='MpServer', x=-114.50, y=4.00, z=653.50], EntityCreeper['Creeper'/188, l='MpServer', x=-117.15, y=4.00, z=668.57], EntitySkeleton['Skeleton'/189, l='MpServer', x=-116.72, y=4.00, z=661.42], EntityEnderman['Enderman'/190, l='MpServer', x=-123.35, y=4.00, z=679.66], EntitySpider['Spider'/191, l='MpServer', x=-124.41, y=4.00, z=679.11], EntityCreeper['Creeper'/192, l='MpServer', x=-125.56, y=4.00, z=672.81], EntityZombie['Zombie'/193, l='MpServer', x=-127.65, y=4.00, z=680.26], EntityCreeper['Creeper'/194, l='MpServer', x=-109.60, y=4.00, z=688.17], EntityPig['Pig'/195, l='MpServer', x=-129.23, y=4.00, z=712.75], EntityEnderman['Enderman'/196, l='MpServer', x=-113.50, y=4.00, z=710.50], EntitySpider['Spider'/201, l='MpServer', x=-99.95, y=4.00, z=556.03], EntitySheep['Sheep'/202, l='MpServer', x=-101.70, y=4.00, z=581.75], EntityZombie['Zombie'/203, l='MpServer', x=-107.15, y=5.00, z=622.14], EntityCreeper['Creeper'/204, l='MpServer', x=-116.21, y=4.00, z=642.70], EntityCreeper['Creeper'/205, l='MpServer', x=-92.64, y=4.00, z=651.21], EntityCreeper['Creeper'/206, l='MpServer', x=-97.70, y=4.00, z=655.31], EntitySheep['Sheep'/207, l='MpServer', x=-93.70, y=4.00, z=664.46], EntitySpider['Spider'/208, l='MpServer', x=-94.06, y=4.00, z=661.08], EntitySkeleton['Skeleton'/209, l='MpServer', x=-106.50, y=4.00, z=679.50], EntitySpider['Spider'/212, l='MpServer', x=-92.50, y=4.00, z=556.50], EntitySkeleton['Skeleton'/213, l='MpServer', x=-84.50, y=4.00, z=561.50], EntityCow['Cow'/214, l='MpServer', x=-101.13, y=4.00, z=586.21], EntitySkeleton['Skeleton'/215, l='MpServer', x=-87.50, y=4.00, z=582.50], EntityZombie['Zombie'/216, l='MpServer', x=-89.16, y=5.00, z=633.21], EntityCreeper['Creeper'/217, l='MpServer', x=-80.50, y=4.00, z=655.50], EntitySpider['Spider'/218, l='MpServer', x=-88.13, y=4.00, z=666.81], EntitySlime['Slime'/219, l='MpServer', x=-76.06, y=4.00, z=689.76], EntitySheep['Sheep'/220, l='MpServer', x=-82.42, y=4.00, z=674.25], EntityZombie['Zombie'/222, l='MpServer', x=-69.79, y=4.00, z=557.73], EntityPig['Pig'/223, l='MpServer', x=-70.58, y=4.00, z=597.54], EntityZombie['Zombie'/224, l='MpServer', x=-64.50, y=4.00, z=633.50], EntityZombie['Zombie'/225, l='MpServer', x=-72.18, y=4.00, z=659.18], EntityZombie['Zombie'/227, l='MpServer', x=-50.78, y=4.00, z=580.22], EntitySheep['Sheep'/228, l='MpServer', x=-56.27, y=4.00, z=611.23], EntitySpider['Spider'/229, l='MpServer', x=-57.02, y=4.00, z=599.02], EntitySkeleton['Skeleton'/230, l='MpServer', x=-63.60, y=4.00, z=604.27], EntityZombie['Zombie'/231, l='MpServer', x=-60.19, y=4.00, z=671.39], EntitySkeleton['Skeleton'/236, l='MpServer', x=-46.74, y=4.00, z=650.42], EntityPlayerSP['Ckeeze'/251, l='MpServer', x=-125.78, y=5.17, z=634.26]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 367936256 bytes (350 MB) / 837251072 bytes (798 MB) up to 5341904896 bytes (5094 MB)
	JVM Flags: 6 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID            | Version      | Source                                      | Signature                                |
	|:--------- |:------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft     | 1.12.2       | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp           | 9.42         | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge         | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | journeymap    | 1.12.2-5.5.2 | JourneyMap-Mod-1.12.2-Unlimited.jar         | None                                     |
	| UCHIJAAAA | lunatriuscore | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| UCHIJAAAA | schematica    | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.5.0 - Build 23.20.16.4973, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 23.20.16.4973
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by NaluNaluNalu** [comment]
Bump. I'm having the same issue and haven't been able to fix it.

**Comment by Pokechu22** [comment]
If I recall correctly, this is #321 and is caused by optifine.  Removing optifine fixes it, and disabling VBOs may also fix it.

**Comment by ckeeze** [comment]
I fixed it!
It was Optifine's fault, for whoever uses Optifine and Schematica at the same time you don't have to delete Optifine but make shure you have  fast render off!
