### ISSUE TITLE
1.12.2 Crash With Printer Schematica

### ISSUE THREAD

**Issue by TylerC19** [Lunatrius/Schematica#416]
I Loaded a schematic and turned on printer and it went fine for about 2 minutes but then it crashed and I think it was from how it was placing the redstone in the schematic. I tried a lot of things, for about two hours. not even disabling all of my mods and logging back on to the world fixed it, the world is now not accessable at all and it is by far my best world, I have been dabbling in complex redstone with project red and making calculators and many other redstone machines and devices. I have a backup of the world before after the crash and before any of the mods. Here is my first crash report. 
Please Help!!! Thank You!!

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/27/19 4:07 PM
Description: Exception while updating neighbours

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at com.google.common.collect.Lists.newArrayList(Lists.java:149)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:154)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:496)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:496)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:497)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:496)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:497)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175695_a(World.java:524)
	at net.minecraft.block.BlockRedstoneDiode.func_176400_h(BlockRedstoneDiode.java:235)
	at net.minecraft.block.BlockRedstoneRepeater.func_180663_b(SourceFile:128)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockRedstoneDiode.func_180650_b(BlockRedstoneDiode.java:64)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at com.google.common.collect.Lists.newArrayList(Lists.java:149)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:154)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=0,south=none,west=none]
	Block location: World: (1084,68,-955), Chunk: (at 12,4,5 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=12,south=none,west=none]
	Block location: World: (1084,68,-955), Chunk: (at 12,4,5 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:496)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=13,south=none,west=none]
	Block location: World: (1084,68,-954), Chunk: (at 12,4,6 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:496)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=13,south=none,west=none]
	Block location: World: (1084,68,-953), Chunk: (at 12,4,7 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:497)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=13,south=none,west=none]
	Block location: World: (1084,68,-955), Chunk: (at 12,4,5 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:496)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=14,south=none,west=none]
	Block location: World: (1084,68,-954), Chunk: (at 12,4,6 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:497)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=14,south=none,west=none]
	Block location: World: (1084,68,-955), Chunk: (at 12,4,5 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=15,south=none,west=none]
	Block location: World: (1084,68,-955), Chunk: (at 12,4,5 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire // minecraft:redstone_wire)
	Block: minecraft:redstone_wire[east=none,north=none,power=14,south=none,west=none]
	Block location: World: (1084,66,-955), Chunk: (at 12,4,5 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #94 (tile.diode // net.minecraft.block.BlockRedstoneRepeater // minecraft:powered_repeater)
	Block: minecraft:redstone_wire[east=none,north=none,power=15,south=none,west=none]
	Block location: World: (1084,66,-955), Chunk: (at 12,4,5 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175695_a(World.java:524)
	at net.minecraft.block.BlockRedstoneDiode.func_176400_h(BlockRedstoneDiode.java:235)
	at net.minecraft.block.BlockRedstoneRepeater.func_180663_b(SourceFile:128)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockRedstoneDiode.func_180650_b(BlockRedstoneDiode.java:64)

-- Block being ticked --
Details:
	Block: minecraft:powered_repeater[delay=1,facing=north,locked=false]
	Block location: World: (1084,67,-956), Chunk: (at 12,4,4 in 67,-60; contains blocks 1072,0,-960 to 1087,255,-945), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)

-- Affected level --
Details:
	Level name: Redstone World
	All players: 1 total; [EntityPlayerMP['JTC1929'/76, l='Redstone World', x=1081.36, y=59.19, z=-963.70]]
	Chunk stats: ServerChunkCache: 1001 Drop: 0
	Level seed: -6388150772172691139
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,3*minecraft:stone,52*minecraft:sandstone;2;
	Level spawn location: World: (835,4,-926), Chunk: (at 3,0,2 in 52,-58; contains blocks 832,0,-928 to 847,255,-913), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 9676655 game time, 1652220 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 74991 (now: false), thunder time: 106488 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 595694072 bytes (568 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2770 Optifine OptiFine_1.12.2_HD_U_E2 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version         | Source                                                 | Signature                                |
	|:--------- |:----------------------- |:--------------- |:------------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2          | minecraft.jar                                          | None                                     |
	| UCHIJAAAA | mcp                     | 9.42            | minecraft.jar                                          | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99       | forge-1.12.2-14.23.5.2770.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.5.2770    | forge-1.12.2-14.23.5.2770.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | codechickenlib          | 3.2.2.353       | CodeChickenLib-1.12.2.jar                              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | computercraft           | 1.80pr1         | ComputerCraft-Mod-1.12.1.jar                           | None                                     |
	| UCHIJAAAA | forgemultipartcbe       | 2.6.0.79        | Forge-Multipart-1.12.2.jar                             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe           | 2.6.0.79        | Forge-Multipart-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe   | 2.6.0.79        | Forge-Multipart-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | lunatriuscore           | 1.2.0.42        | LunatriusCore-1.12.2-1.2.0.42-universal.jar            | None                                     |
	| UCHIJAAAA | mrtjpcore               | 2.1.3.35        | MrTJPCore-1.12.2-2.1.3.35-universal.jar                | None                                     |
	| UCHIJAAAA | projectred-core         | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-Base.jar                    | None                                     |
	| UCHIJAAAA | projectred-compat       | 1.0             | ProjectRed-1.12.2-4.9.1.92-compat.jar                  | None                                     |
	| UCHIJAAAA | projectred-integration  | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-integration.jar             | None                                     |
	| UCHIJAAAA | projectred-transmission | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-integration.jar             | None                                     |
	| UCHIJAAAA | projectred-fabrication  | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-fabrication.jar             | None                                     |
	| UCHIJAAAA | projectred-illumination | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-lighting.jar                | None                                     |
	| UCHIJAAAA | schematica              | 1.8.0.169       | Schematica-1.12.2-1.8.0.169-universal.jar              | None                                     |
	| UCHIJAAAA | wrcbe                   | 2.3.1           | Wireless-Redstone-Chicken-Bones-Edition-Mod-1.12.2.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | worldedit               | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['JTC1929'/76, l='Redstone World', x=1081.36, y=59.19, z=-963.70]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4252
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by maruohon** [comment]
Make sure you have a backup of the world, and then try opening it in MCEdit-Unified and deleting the redstone dust blocks that are indicated in the crash report, for example at 1084,68,-955 and a few others.
