### ISSUE TITLE
Schismatica keeps crashing when i load a schematic please help me asap

### ISSUE THREAD

**Issue by YForYoshi** [Lunatrius/Schematica#419]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/02/19 1:04 PM
Description: Batching chunks

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:113)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)
	at com.github.lunatrius.schematica.client.renderer.chunk.overlay.RenderOverlay.func_178581_b(RenderOverlay.java:157)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.client.renderer.WorldRenderer.func_181662_b(WorldRenderer.java:437)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:113)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawQuads(GeometryTessellator.java:108)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:90)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:73)
	at com.github.lunatrius.core.client.renderer.GeometryTessellator.drawCuboid(GeometryTessellator.java:69)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Y_For_Yoshi'/105, l='MpServer', x=-38.63, y=23.19, z=989.21]]
	Chunk stats: MultiplayerChunkCache: 220, 220
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -14.00,4.00,983.00 - World: (-14,4,983), Chunk: (at 2,0,7 in -1,61; contains blocks -16,0,976 to -1,255,991), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 30628 game time, 15030 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 71 total; [EntitySlime['Slime'/7, l='MpServer', x=-114.13, y=4.00, z=990.72], EntityZombie['Zombie'/8, l='MpServer', x=-96.31, y=4.00, z=972.91], EntitySlime['Slime'/9, l='MpServer', x=-105.93, y=4.20, z=964.71], EntitySkeleton['Skeleton'/10, l='MpServer', x=-102.38, y=4.00, z=981.13], EntitySlime['Slime'/11, l='MpServer', x=-98.28, y=4.86, z=988.89], EntityZombie['Zombie'/12, l='MpServer', x=-104.50, y=4.00, z=1024.50], EntitySlime['Slime'/13, l='MpServer', x=-84.32, y=4.20, z=957.02], EntityZombie['Zombie'/14, l='MpServer', x=-89.19, y=4.00, z=984.16], EntitySlime['Slime'/15, l='MpServer', x=-86.42, y=4.05, z=975.17], EntitySlime['Slime'/16, l='MpServer', x=-82.91, y=4.00, z=1019.09], EntitySlime['Slime'/17, l='MpServer', x=-81.63, y=4.00, z=1024.53], EntitySlime['Slime'/18, l='MpServer', x=-91.24, y=4.38, z=1031.73], EntityPig['Pig'/19, l='MpServer', x=-89.03, y=4.00, z=1069.09], EntitySlime['Slime'/20, l='MpServer', x=-71.59, y=4.00, z=926.44], EntitySlime['Slime'/21, l='MpServer', x=-75.55, y=4.11, z=937.92], EntitySlime['Slime'/22, l='MpServer', x=-71.31, y=4.99, z=964.62], EntitySpider['Spider'/23, l='MpServer', x=-76.88, y=4.00, z=986.19], EntitySlime['Slime'/26, l='MpServer', x=-53.09, y=4.39, z=911.36], EntitySheep['Sheep'/27, l='MpServer', x=-55.53, y=4.00, z=927.22], EntityZombie['Zombie'/28, l='MpServer', x=-63.50, y=4.00, z=914.50], EntitySlime['Slime'/29, l='MpServer', x=-58.70, y=5.05, z=937.24], EntitySlime['Slime'/30, l='MpServer', x=-49.75, y=4.00, z=942.59], EntitySlime['Slime'/31, l='MpServer', x=-55.51, y=4.99, z=955.78], EntitySlime['Slime'/32, l='MpServer', x=-59.70, y=5.06, z=970.33], EntitySlime['Slime'/33, l='MpServer', x=-50.28, y=4.00, z=968.44], EntitySlime['Slime'/34, l='MpServer', x=-60.74, y=4.27, z=967.18], EntitySlime['Slime'/35, l='MpServer', x=-57.27, y=4.38, z=983.27], EntitySlime['Slime'/36, l='MpServer', x=-56.04, y=4.07, z=997.24], EntityCreeper['Creeper'/37, l='MpServer', x=-63.50, y=4.00, z=1002.50], EntitySpider['Spider'/38, l='MpServer', x=-63.88, y=4.00, z=1021.19], EntitySlime['Slime'/39, l='MpServer', x=-63.46, y=5.06, z=1036.26], EntitySlime['Slime'/45, l='MpServer', x=-46.51, y=4.71, z=927.87], EntitySlime['Slime'/46, l='MpServer', x=-44.88, y=4.00, z=952.22], EntitySlime['Slime'/47, l='MpServer', x=-49.09, y=4.99, z=957.74], EntitySlime['Slime'/48, l='MpServer', x=-43.35, y=4.87, z=956.32], EntitySlime['Slime'/49, l='MpServer', x=-34.48, y=4.71, z=973.35], EntitySkeleton['Skeleton'/50, l='MpServer', x=-32.49, y=4.00, z=974.43], EntitySpider['Spider'/51, l='MpServer', x=-43.64, y=4.00, z=961.00], EntitySlime['Slime'/52, l='MpServer', x=-42.00, y=4.21, z=960.20], EntityItem['item.tile.cactus'/53, l='MpServer', x=-33.50, y=4.00, z=995.31], EntityPlayerSP['Y_For_Yoshi'/105, l='MpServer', x=-38.63, y=23.19, z=989.21], EntitySlime['Slime'/54, l='MpServer', x=-46.80, y=4.99, z=994.55], EntitySlime['Slime'/55, l='MpServer', x=-43.34, y=4.00, z=1042.97], EntitySlime['Slime'/56, l='MpServer', x=-32.50, y=4.87, z=1025.30], EntitySlime['Slime'/59, l='MpServer', x=-31.51, y=4.88, z=975.66], EntitySlime['Slime'/60, l='MpServer', x=-32.16, y=4.66, z=961.19], EntityItem['item.item.slimeball'/61, l='MpServer', x=-30.56, y=4.00, z=976.69], EntityItem['item.item.slimeball'/62, l='MpServer', x=-21.53, y=4.00, z=987.19], EntityItem['item.tile.cactus'/63, l='MpServer', x=-26.44, y=4.00, z=977.84], EntityItem['item.tile.cactus'/64, l='MpServer', x=-21.41, y=4.00, z=979.78], EntityItem['item.tile.cactus'/65, l='MpServer', x=-21.09, y=4.00, z=991.50], EntitySlime['Slime'/66, l='MpServer', x=-20.94, y=4.71, z=978.47], EntityItem['item.item.slimeball'/67, l='MpServer', x=-21.56, y=4.00, z=992.41], EntitySlime['Slime'/68, l='MpServer', x=-20.46, y=4.07, z=1036.25], EntitySlime['Slime'/73, l='MpServer', x=-10.07, y=4.87, z=921.99], EntitySlime['Slime'/74, l='MpServer', x=-8.63, y=4.87, z=964.79], EntitySlime['Slime'/75, l='MpServer', x=-3.78, y=4.00, z=983.56], EntitySlime['Slime'/76, l='MpServer', x=-3.77, y=4.11, z=980.75], EntitySlime['Slime'/77, l='MpServer', x=-6.67, y=5.05, z=1004.96], EntityItem['item.item.egg'/78, l='MpServer', x=-12.03, y=4.00, z=1022.16], EntityChicken['Chicken'/79, l='MpServer', x=-3.69, y=4.00, z=1027.31], EntityZombie['Zombie'/80, l='MpServer', x=-9.50, y=4.00, z=1055.50], EntitySlime['Slime'/81, l='MpServer', x=-11.31, y=4.28, z=1065.69], EntitySpider['Spider'/83, l='MpServer', x=3.50, y=4.00, z=952.50], EntitySlime['Slime'/84, l='MpServer', x=15.34, y=4.28, z=997.06], EntitySkeleton['Skeleton'/85, l='MpServer', x=7.43, y=4.00, z=1024.12], EntitySlime['Slime'/86, l='MpServer', x=18.52, y=5.00, z=979.56], EntitySlime['Slime'/87, l='MpServer', x=20.78, y=5.05, z=1004.74], EntitySlime['Slime'/90, l='MpServer', x=38.53, y=4.00, z=1030.50], EntityCreeper['Creeper'/91, l='MpServer', x=35.50, y=4.00, z=1041.50], EntitySkeleton['Skeleton'/92, l='MpServer', x=37.50, y=4.00, z=1056.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 938254632 bytes (894 MB) / 1207959552 bytes (1152 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.142} [Schematica] (Schematica-1.8.9-1.7.7.142-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz

Please help this keeps happening when i load a schmatic

**Comment by YForYoshi** [comment]
also i have tried reinstalling, changing graphic stuff and more please help
