### ISSUE TITLE
Schematica crashing while loading the Shematic

### ISSUE THREAD

**Issue by LimitVL** [Lunatrius/Schematica#422]
Yeah, as it in the title stands. When I try to load an Object on the multiplayer server of my friend through the twitch-mod, it instantly crashes. This is the error I get:

### **---- Minecraft Crash Report ----**

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

**### Description: Unexpected error java.lang.NullPointerException: The validated object is null**

	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at stellarium.render.stellars.layer.StellarLayerModel.onStellarTick(StellarLayerModel.java:78)
	at stellarium.render.stellars.phased.StellarRenderModel.onTick(StellarRenderModel.java:64)
	at stellarium.render.stellars.StellarModel.onTick(StellarModel.java:41)
	at stellarium.render.sky.SkyModel.onTick(SkyModel.java:64)
	at stellarium.ClientProxy.updateTick(ClientProxy.java:179)
	at stellarium.StellarTickHandler.tickStart(StellarTickHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1468_StellarTickHandler_tickStart_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### **A detailed walkthrough of the error, its code path and all known details is as follows:**

Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at stellarium.render.stellars.layer.StellarLayerModel.onStellarTick(StellarLayerModel.java:78)
	at stellarium.render.stellars.phased.StellarRenderModel.onTick(StellarRenderModel.java:64)
	at stellarium.render.stellars.StellarModel.onTick(StellarModel.java:41)
	at stellarium.render.sky.SkyModel.onTick(SkyModel.java:64)
	at stellarium.ClientProxy.updateTick(ClientProxy.java:179)
	at stellarium.StellarTickHandler.tickStart(StellarTickHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1468_StellarTickHandler_tickStart_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CayB'/9742, l='MpServer', x=291.99, y=71.03, z=-176.15]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (259,68,-371), Chunk: (at 3,4,13 in 16,-24; contains blocks 256,0,-384 to 271,255,-369), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 20922687 game time, 47717244 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 81 total; [EntitySheep['Schaf'/9856, l='MpServer', x=220.50, y=68.00, z=-159.75], EntityZombie['Zombie'/13827, l='MpServer', x=302.50, y=35.00, z=-181.50], EntityBat['Fledermaus'/12808, l='MpServer', x=301.74, y=37.25, z=-157.25], EntitySpider['Spinne'/12558, l='MpServer', x=293.50, y=45.00, z=-120.50], EntityBat['Fledermaus'/15120, l='MpServer', x=239.52, y=24.93, z=-147.49], EntitySheep['Schaf'/9873, l='MpServer', x=218.51, y=70.00, z=-238.19], EntityBat['Fledermaus'/15121, l='MpServer', x=219.97, y=26.02, z=-163.66], EntityZombie['Zombie'/15505, l='MpServer', x=327.46, y=28.00, z=-171.27], EntitySkeleton['Skelett'/15506, l='MpServer', x=319.50, y=25.00, z=-168.50], EntityBabySkeleton['Baby-Skelett'/15251, l='MpServer', x=235.75, y=24.00, z=-170.12], EntitySkeleton['Skelett'/15507, l='MpServer', x=320.56, y=25.00, z=-168.70], EntityHorse['Pferd'/9877, l='MpServer', x=214.80, y=53.00, z=-181.98], EntityCow['Kuh'/9878, l='MpServer', x=216.48, y=65.00, z=-185.20], EntityZombie['Zombie'/13851, l='MpServer', x=243.28, y=34.00, z=-182.49], EntitySpider['Spinne'/15011, l='MpServer', x=217.50, y=23.00, z=-172.50], EntityBat['Fledermaus'/14757, l='MpServer', x=356.75, y=18.10, z=-143.25], EntityCreeper['Creeper'/15782, l='MpServer', x=281.50, y=50.00, z=-202.50], EntityCow['Kuh'/9896, l='MpServer', x=218.50, y=70.00, z=-113.85], EntityVillager['Dorfbewohner'/9768, l='MpServer', x=225.70, y=69.00, z=-173.30], EntityVillager['Dorfbewohner'/9769, l='MpServer', x=225.70, y=69.00, z=-173.30], EntityVillager['Dorfbewohner'/9770, l='MpServer', x=225.70, y=69.00, z=-173.30], EntityVillager['Dorfbewohner'/9771, l='MpServer', x=222.43, y=68.00, z=-160.24], EntityVillager['Dorfbewohner'/9772, l='MpServer', x=224.54, y=68.00, z=-160.24], EntityVillager['Dorfbewohner'/9773, l='MpServer', x=223.17, y=68.00, z=-160.24], EntityVillager['Dorfbewohner'/9774, l='MpServer', x=223.86, y=68.00, z=-160.24], EntitySheep['Schaf'/9776, l='MpServer', x=239.58, y=70.00, z=-129.25], EntityCreeper['Creeper'/15152, l='MpServer', x=223.70, y=60.00, z=-124.30], EntitySheep['Schaf'/9777, l='MpServer', x=243.49, y=70.00, z=-131.27], EntitySheep['Schaf'/9778, l='MpServer', x=243.92, y=70.00, z=-128.08], EntityCow['Kuh'/9779, l='MpServer', x=262.14, y=66.00, z=-239.61], EntityCow['Kuh'/9780, l='MpServer', x=266.48, y=66.00, z=-239.78], EntitySheep['Schaf'/9783, l='MpServer', x=267.22, y=69.00, z=-136.25], EntityBat['Fledermaus'/13879, l='MpServer', x=255.25, y=51.10, z=-119.62], EntitySheep['Schaf'/9784, l='MpServer', x=262.51, y=69.00, z=-126.29], EntitySheep['Schaf'/9786, l='MpServer', x=280.50, y=66.00, z=-153.74], EntityCreeper['Creeper'/14010, l='MpServer', x=319.50, y=24.00, z=-232.50], EntitySheep['Schaf'/9788, l='MpServer', x=268.77, y=67.00, z=-151.43], EntityZombie['Zombie'/15676, l='MpServer', x=296.50, y=36.00, z=-212.50], EntitySheep['Schaf'/9789, l='MpServer', x=295.41, y=67.00, z=-160.77], EntityCreeper['Creeper'/15677, l='MpServer', x=297.50, y=36.00, z=-215.50], EntitySheep['Schaf'/9790, l='MpServer', x=286.56, y=65.00, z=-136.81], EntityBat['Fledermaus'/14654, l='MpServer', x=324.15, y=23.28, z=-221.25], EntityBabySkeleton['Baby-Skelett'/15422, l='MpServer', x=284.50, y=42.00, z=-162.50], EntitySheep['Schaf'/9791, l='MpServer', x=285.65, y=67.00, z=-162.76], EntitySheep['Schaf'/9792, l='MpServer', x=272.52, y=67.00, z=-160.26], EntitySheep['Schaf'/9793, l='MpServer', x=309.24, y=66.00, z=-120.52], EntitySheep['Schaf'/9794, l='MpServer', x=322.25, y=69.00, z=-149.19], EntityCow['Kuh'/9795, l='MpServer', x=334.21, y=66.00, z=-120.50], EntityBat['Fledermaus'/15555, l='MpServer', x=307.55, y=19.10, z=-136.59], EntityZombie['Zombie'/12615, l='MpServer', x=214.50, y=12.00, z=-118.50], EntityCreeper['Creeper'/15178, l='MpServer', x=305.85, y=34.00, z=-189.47], EntityPlayerSP['CayB'/9742, l='MpServer', x=291.99, y=71.03, z=-176.15], EntitySkeleton['Skelett'/15310, l='MpServer', x=253.50, y=22.00, z=-168.50], EntitySkeleton['Skelett'/15311, l='MpServer', x=248.54, y=20.00, z=-170.27], EntityCreeper['Creeper'/15313, l='MpServer', x=252.50, y=22.00, z=-176.50], EntityChicken['Huhn'/9811, l='MpServer', x=368.40, y=72.00, z=-225.83], EntityItem['item.item.bone'/10452, l='MpServer', x=271.25, y=54.00, z=-188.63], EntityZombie['Zombie'/15444, l='MpServer', x=288.50, y=43.00, z=-160.50], EntityCreeper['Creeper'/15319, l='MpServer', x=264.46, y=21.00, z=-109.83], EntityChicken['Huhn'/9816, l='MpServer', x=368.86, y=69.00, z=-208.51], EntityCreeper['Creeper'/13144, l='MpServer', x=279.80, y=54.00, z=-199.56], EntitySheep['Schaf'/9818, l='MpServer', x=262.28, y=70.00, z=-111.46], EntityChicken['Huhn'/219, l='MpServer', x=265.11, y=66.00, z=-246.37], EntityChicken['Huhn'/220, l='MpServer', x=261.58, y=66.00, z=-246.88], EntityChicken['Huhn'/221, l='MpServer', x=264.47, y=66.00, z=-248.17], EntityEnderman['Enderman'/15069, l='MpServer', x=237.50, y=24.00, z=-172.50], EntityChicken['Huhn'/222, l='MpServer', x=261.49, y=66.00, z=-248.14], EntitySkeleton['Skelett'/13663, l='MpServer', x=294.50, y=30.00, z=-211.50], EntityBabySkeleton['Baby-Skelett'/15071, l='MpServer', x=234.32, y=24.00, z=-170.57], EntityChicken['Huhn'/9824, l='MpServer', x=352.59, y=76.00, z=-104.50], EntityCreeper['Creeper'/15714, l='MpServer', x=272.50, y=50.00, z=-189.50], EntityCreeper['Creeper'/15337, l='MpServer', x=309.50, y=21.00, z=-252.50], EntitySkeleton['Skelett'/12655, l='MpServer', x=333.50, y=35.00, z=-105.50], EntityCreeper['Creeper'/14831, l='MpServer', x=249.30, y=32.00, z=-142.30], EntityCreeper['Creeper'/14832, l='MpServer', x=250.50, y=32.00, z=-146.50], EntityCreeper['Creeper'/14833, l='MpServer', x=252.46, y=34.00, z=-136.81], EntitySpider['Spinne'/15346, l='MpServer', x=318.70, y=27.10, z=-229.71], EntityCow['Kuh'/9844, l='MpServer', x=325.46, y=66.00, z=-107.83], EntityHorse['Pferd'/9848, l='MpServer', x=215.37, y=54.00, z=-172.17], EntityEnderman['Enderman'/14075, l='MpServer', x=267.56, y=38.00, z=-126.46], EntityZombie['Zombie'/14589, l='MpServer', x=223.50, y=23.00, z=-178.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1678011800 bytes (1600 MB) / 5877268480 bytes (5605 MB) up to 8388608000 bytes (8000 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9000m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2808 128 mods loaded, 128 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID

**Comment by LimitVL** [comment]
It doesnt matter which size the object has. A small / medium / large one. It crashes all the time.
