### ISSUE TITLE
/schematicaReplace ?

### ISSUE THREAD

**Issue by Sethton** [Lunatrius/Schematica#424]
I am trying to replace chiseled stone bricks monster egg with normal chiseled stone bricks.  i cant seem to find a way to get it to work.  i did find that if i try /schematicaReplace monster_egg[variant=chiseled_brick] sand   it says 5 in red and then if i try it again its an unknown error.  i tried sand cause i figured turn the monster egg blocks to sand then sand to chiseled bricks  but either way  im just having alot of trouble fixing this or changing this.  if i could get a little help please and thank you

**Comment by Sethton** [comment]
does anyone check here?

**Comment by Pokechu22** [comment]
I saw this, but I didn't have a full answer so I didn't comment.

I guess, can you check if there's a stacktrace in the log?  `5` is the metadata value associated with the chiseled brick version, but I don't know why it would output that.  It should at least generate a stacktrace for the "Unknown error" version.

**Comment by Sethton** [comment]
how do i check whats in the log?

**Comment by Pokechu22** [comment]
Check `.minecraft/logs/latest.log` (after reproducing the issue).  `.minecraft` would be the location where you launched the game; depending on if you used a different launcher it might be elsewhere.

**Comment by Sethton** [comment]
[09:13:32] [main/ERROR] [schematica]: Something went wrong!
java.lang.ArrayIndexOutOfBoundsException: 5
	at pl.asie.foamfix.common.PropertyValueMapper.withProperty(PropertyValueMapper.java:309) ~[foamfix-0.10.3-1.12.2.jar:?]
	at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:52) ~[foamfix-0.10.3-1.12.2.jar:?]
	at com.github.lunatrius.schematica.block.state.pattern.BlockStateReplacer.applyProperties(BlockStateReplacer.java:37) ~[BlockStateReplacer.class:?]
	at com.github.lunatrius.schematica.block.state.pattern.BlockStateReplacer.getReplacement(BlockStateReplacer.java:27) ~[BlockStateReplacer.class:?]
	at com.github.lunatrius.schematica.client.world.SchematicWorld.replaceBlock(SchematicWorld.java:244) ~[SchematicWorld.class:?]
	at com.github.lunatrius.schematica.command.client.CommandSchematicaReplace.func_184881_a(CommandSchematicaReplace.java:63) [CommandSchematicaReplace.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:95) [ClientCommandHandler.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:422) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411) [blk.class:?]
	at GuiChatOF.func_175275_f(GuiChatOF.java:40) [GuiChatOF.class:?]
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81) [bkn.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:13:32] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] 5
[09:13:34] [main/ERROR] [schematica]: Something went wrong!
java.lang.ArrayIndexOutOfBoundsException: null
[09:13:34] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] An unknown error occurred while attempting to perform this command
[09:13:34] [main/ERROR] [FML]: Command 'schematicaReplace monster_egg[variant=chiseled_brick] stonebrick' threw an exception:
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Unknown Source) ~[?:1.8.0_121]
	at java.util.regex.Matcher.reset(Unknown Source) ~[?:1.8.0_121]
	at java.util.regex.Matcher.<init>(Unknown Source) ~[?:1.8.0_121]
	at java.util.regex.Pattern.matcher(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.text.TextComponentTranslation.func_150269_b(SourceFile:64) ~[hp.class:?]
	at net.minecraft.util.text.TextComponentTranslation.func_150270_g(SourceFile:51) ~[hp.class:?]
	at net.minecraft.util.text.TextComponentTranslation.iterator(SourceFile:152) ~[hp.class:?]
	at com.google.common.collect.Lists.newArrayList(Lists.java:150) ~[guava-21.0.jar:?]
	at net.minecraft.client.gui.GuiUtilRenderComponents.func_178908_a(GuiUtilRenderComponents.java:25) ~[bjc.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146237_a(SourceFile:142) ~[bjb.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146234_a(SourceFile:132) ~[bjb.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146227_a(SourceFile:128) ~[bjb.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.func_145747_a(EntityPlayerSP.java:554) ~[bud.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:132) ~[bj.class:?]
	at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:95) [ClientCommandHandler.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:422) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411) [blk.class:?]
	at GuiChatOF.func_175275_f(GuiChatOF.java:40) [GuiChatOF.class:?]
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81) [bkn.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:13:38] [main/ERROR] [schematica]: Something went wrong!
java.lang.ArrayIndexOutOfBoundsException: null
[09:13:38] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] An unknown error occurred while attempting to perform this command
[09:13:38] [main/ERROR] [FML]: Command 'schematicaReplace monster_egg[variant=chiseled_brick] stonebrick' threw an exception:
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Unknown Source) ~[?:1.8.0_121]
	at java.util.regex.Matcher.reset(Unknown Source) ~[?:1.8.0_121]
	at java.util.regex.Matcher.<init>(Unknown Source) ~[?:1.8.0_121]
	at java.util.regex.Pattern.matcher(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.text.TextComponentTranslation.func_150269_b(SourceFile:64) ~[hp.class:?]
	at net.minecraft.util.text.TextComponentTranslation.func_150270_g(SourceFile:51) ~[hp.class:?]
	at net.minecraft.util.text.TextComponentTranslation.iterator(SourceFile:152) ~[hp.class:?]
	at com.google.common.collect.Lists.newArrayList(Lists.java:150) ~[guava-21.0.jar:?]
	at net.minecraft.client.gui.GuiUtilRenderComponents.func_178908_a(GuiUtilRenderComponents.java:25) ~[bjc.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146237_a(SourceFile:142) ~[bjb.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146234_a(SourceFile:132) ~[bjb.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146227_a(SourceFile:128) ~[bjb.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.func_145747_a(EntityPlayerSP.java:554) ~[bud.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:132) ~[bj.class:?]
	at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:95) [ClientCommandHandler.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:422) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411) [blk.class:?]
	at GuiChatOF.func_175275_f(GuiChatOF.java:40) [GuiChatOF.class:?]
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81) [bkn.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:13:40] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Saving and pausing game...
[09:13:40] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World-'/overworld
[09:13:40] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World-'/overworld
[09:13:41] [Netty Local Client IO #0/INFO] [schematica]: Scheduling client settings reset.
[09:13:41] [main/INFO] [journeymap]: Mapping halted in C:\Users\Ryan\AppData\Roaming\.technic\modpacks\complex-pixelmon-reforged\journeymap\data\sp\New World~\DIM0
[09:13:41] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server

**Comment by Sethton** [comment]
hope that's what you meant

**Comment by Pokechu22** [comment]
Yep, thanks.

Try removing foamfix and see if that solves the issue.  (I don't know too much about what foamfix does, other than that it does make a lot of base changes; it's possible that this is a bug in it or not).

**Comment by Sethton** [comment]
i have no clue what foamfix is haha  maybe it was grouped in the mods i got for pixelmon.     i cant get rid of jukeboxs either lol   ill try to look at removing that if its a mod  if not ill comment back later
