### ISSUE TITLE
BufferOverflowException crash

### ISSUE THREAD

**Issue by eirikh1996** [Lunatrius/Schematica#431]
When loading a schematic of a significant size, this happens: Block textures are not rendered, and, after about a minute, the game crashes:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/29/19 12:48 AM
Description: Unexpected error

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:168)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:168)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 8 total; [EntityPlayerSP['eirikh1996'/18371721, l='MpServer', x=2139.41, y=82.00, z=6435.65], EntityOtherPlayerMP['Minerals'/18371920, l='MpServer', x=2016.52, y=64.00, z=6508.70], EntityOtherPlayerMP['Blacksmith'/18371923, l='MpServer', x=2022.51, y=64.00, z=6508.70], EntityOtherPlayerMP['Blacksmith'/18371926, l='MpServer', x=2022.51, y=64.00, z=6508.70], EntityOtherPlayerMP['Ship Supply'/18371914, l='MpServer', x=2018.70, y=64.00, z=6508.70], EntityOtherPlayerMP['Building Blocks'/18371917, l='MpServer', x=2020.49, y=64.00, z=6508.70], EntityOtherPlayerMP['Iridium Ships'/18371904, l='MpServer', x=2045.49, y=71.00, z=6516.38], EntityOtherPlayerMP['Foodstuffs'/18371938, l='MpServer', x=2049.67, y=72.00, z=6332.39]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (2300,106,6835), Chunk: (at 12,6,3 in 143,427; contains blocks 2288,0,6832 to 2303,255,6847), Region: (4,13; contains chunks 128,416 to 159,447, blocks 2048,0,6656 to 2559,255,7167)
	Level time: 2505903206 game time, 2268588529 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 17 total; [EntityPlayerSP['eirikh1996'/18371721, l='MpServer', x=2139.41, y=82.00, z=6435.65], EntityOtherPlayerMP['Minerals'/18371920, l='MpServer', x=2016.52, y=64.00, z=6508.70], EntityOtherPlayerMP['Blacksmith'/18371923, l='MpServer', x=2022.51, y=64.00, z=6508.70], EntityOtherPlayerMP['Blacksmith'/18371926, l='MpServer', x=2022.51, y=64.00, z=6508.70], EntityOtherPlayerMP['Minerals'/18371920, l='MpServer', x=2016.52, y=64.00, z=6508.70], EntityOtherPlayerMP['Ship Supply'/18371914, l='MpServer', x=2018.70, y=64.00, z=6508.70], EntityOtherPlayerMP['Building Blocks'/18371917, l='MpServer', x=2020.49, y=64.00, z=6508.70], EntityOtherPlayerMP['Iridium Ships'/18371904, l='MpServer', x=2045.49, y=71.00, z=6516.38], EntityOtherPlayerMP['Blacksmith'/18371923, l='MpServer', x=2022.51, y=64.00, z=6508.70], EntityOtherPlayerMP['Foodstuffs'/18371938, l='MpServer', x=2049.67, y=72.00, z=6332.39], EntityOtherPlayerMP['Blacksmith'/18371926, l='MpServer', x=2022.51, y=64.00, z=6508.70], EntityChicken['Høne'/18371722, l='MpServer', x=2147.57, y=82.00, z=6425.12], EntityOtherPlayerMP['Ship Supply'/18371914, l='MpServer', x=2018.70, y=64.00, z=6508.70], EntityChicken['Høne'/18371723, l='MpServer', x=2146.85, y=82.00, z=6427.91], EntityOtherPlayerMP['Building Blocks'/18371917, l='MpServer', x=2020.49, y=64.00, z=6508.70], EntityOtherPlayerMP['Iridium Ships'/18371904, l='MpServer', x=2045.49, y=71.00, z=6516.38], EntityOtherPlayerMP['Foodstuffs'/18371938, l='MpServer', x=2049.67, y=72.00, z=6332.39]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.13-SNAPSHOT:c26705e:1368) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1897105424 bytes (1809 MB) / 3657433088 bytes (3488 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_E2 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                      | Signature                                |
	|:------ |:------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft     | 1.12.2       | minecraft.jar                               | None                                     |
	| UCHIJA | mcp           | 9.42         | minecraft.jar                               | None                                     |
	| UCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge         | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | lunatriuscore | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| UCHIJA | mobends       | 0.24         | mobends-0.24_for_MC-1.12.jar                | None                                     |
	| UCHIJA | schematica    | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.01' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Norsk bokmål (Norge)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz

**Comment by ShayBox** [comment]
Getting this too, when opening the subtract menu after loading a schematic sometimes.

**Comment by Pokechu22** [comment]
This is a duplicate of #321, caused by Optifine's Render Regions setting.  Disabling that setting should solve it, though you may need to remove optifine entirely.

**Comment by ShayBox** [comment]
Thanks, turning that off did fix it, I hope that something can be done to prevent crashing but at-least we have a workaround :+1:
