### ISSUE TITLE
Schematica crashing after loading a schematic

### ISSUE THREAD

**Issue by pancreaticfemale** [Lunatrius/Schematica#462]
So when I load a schematic, it works fine for like 15 seconds up to 2 minutes, then it just freezes and crashes. Any help?

Here is the crashlog;

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ClientCommandsLoadingPlugin (clientcommands-1.12-20190105-snapshot.jar)
  ForgeHaxCoreMod (forgehax-1.12.2-2.9.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 10/1/19 7:31 PM
Description: Unexpected error

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:351)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_90_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:168)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:351)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_90_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:168)

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.1.7-SNAPSHOT
	Minecraft version: Minecraft 1.12.2 (1.12.2-forge1.12.2-14.23.4.2739/fml,forge/Forge)
	Expected version: 1.12.2
	Protocol version: 340
	Data version: 1343
	File location: ~~ERROR~~ IllegalArgumentException: URI is not hierarchical
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at net.minecraft.crash.CrashReportCategory.func_85073_a(CrashReportCategory.java:116)
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:351)
	at wdl.WDL.addInfoToCrash(WDL.java:1497)
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:381)
	at net.minecraft.crash.CrashReport.handler$onCrashReportPopulateEnvironment$zec000(CrashReport.java:532)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:144)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@4dcbadb4 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@4dcbadb4 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

-- World Downloader Mod - State --
Details:
	minecraft: net.minecraft.client.Minecraft@5352bc0e
	worldClient: net.minecraft.client.multiplayer.WorldClient@680eeb68
	networkManager: net.minecraft.network.NetworkManager@623d4297
	thePlayer: EntityPlayerSP['FortniteCum'/3497737, l='MpServer',
	windowContainer: net.minecraft.inventory.ContainerPlayer@30a9b2ef
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: net.minecraft.world.chunk.storage.AnvilSaveHandler@8774b9a
	chunkLoader: wdl.WDLChunkLoader@116fa55
	newTileEntities: {}
	newEntities: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: 
	baseFolderName: 2builders2tools

-- World Downloader Mod - Base properties --
Details:
	Messages.ON_WORLD_LOAD: false
	Messages.enableAll: true

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	-: empty

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['FortniteCum'/3497737, l='MpServer', x
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25750 game time, 1837720544 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295) <- Paper
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 435335112 bytes (415 MB) / 1174405120 bytes (1120 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID             | Version                | Source                                      | Signature                                |
	|:----------- |:-------------- |:---------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft      | 1.12.2                 | minecraft.jar                               | None                                     |
	| UCHIJAAAAAA | mcp            | 9.42                   | minecraft.jar                               | None                                     |
	| UCHIJAAAAAA | FML            | 8.0.99.99              | forge-1.12.2-14.23.4.2739.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge          | 14.23.4.2739           | forge-1.12.2-14.23.4.2739.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | clientcommands | 1.12-20190105-snapshot | clientcommands-1.12-20190105-snapshot.jar   | None                                     |
	| UCHIJAAAAAA | forgehax       | 2.9.0                  | forgehax-1.12.2-2.9.0.jar                   | None                                     |
	| UCHIJAAAAAA | lunatriuscore  | 1.2.0.42               | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| UCHIJAAAAAA | jmcm           | 9.2                    | MinecraftCapes Forge 1.12.2.jar             | None                                     |
	| UCHIJAAAAAA | schematica     | 1.8.0.169              | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
ClientCommandsLoadingPlugin (clientcommands-1.12-20190105-snapshot.jar)
  net.earthcomputer.clientcommands.core.ProxyTransformer
  net.earthcomputer.clientcommands.core.NetHandlerTransformer
  net.earthcomputer.clientcommands.core.IntegratedServerRaceFixTransformer
  net.earthcomputer.clientcommands.core.RenderManagerTransformer
ForgeHaxCoreMod (forgehax-1.12.2-2.9.0.jar)
  com.matt.forgehax.asm.ForgeHaxTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 418.81' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2739
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 418.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 1200 Quad-Core Processor 

**(I cut out the coordinates, shouldn't matter)**

**Comment by Magnum97** [comment]
I am also having this issue. Crash report: https://hatebin.com/llqevqetnd

Additionally when it is not crashing the holographic display is just blue highlights. No blocks are rendered.
