### ISSUE TITLE
Crash when loading a Schematic 1.8.9 

### ISSUE THREAD

**Issue by Traister101** [Lunatrius/Schematica#504]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/30/20 4:06 AM
Description: Updating screen events

java.lang.NoSuchMethodError: com.github.lunatrius.schematica.api.ISchematic.setBlockState(Lnet/minecraft/util/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:233)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:233)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Traister101'/0, l='MpServer', x=-259.23, y=8.78, z=1081.75]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -245.00,4.00,1088.00 - World: (-245,4,1088), Chunk: (at 11,0,0 in -16,68; contains blocks -256,0,1088 to -241,255,1103), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Level time: 102768 game time, 1186 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Traister101'/0, l='MpServer', x=-259.23, y=8.78, z=1081.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 448920072 bytes (428 MB) / 771751936 bytes (736 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_L5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon 3000 Graphics'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: ATI Radeon 3000 Graphics GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Awesome Pack [1.8.9] v2.7.2
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon 3000 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

Not sure if I'm being an Idiot or not but I simply can't figure out what I'm doing wrong and I don't see anywhere else to ask for help, I'd really appreciate whatever help you can give also yes I put the whole Crash report in here because I have no clue what could be related.

**Comment by Traister101** [comment]
I figured out what the problem was I was using the api mod and that was causing the crash
