### ISSUE TITLE
Loading a Schematic in to Print crashes my game about 30 seconds after it is loaded in

### ISSUE THREAD

**Issue by Tealn** [Lunatrius/Schematica#507]
Even trying just 1 chunk of a schematic, it would crash. It slowly got worse and worse the more I tried to load in schematics after loading the game back up. Here is the crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_20.15.2_Forge_1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/10/20 12:21 PM
Description: Unexpected error

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:351)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_466_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:351)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_466_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Tealn'/6093, l='MpServer', x=361.81, y=68.41, z=62.02]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (306,65,233), Chunk: (at 2,4,9 in 19,14; contains blocks 304,0,224 to 319,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 112163 game time, 600 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 43 total; [EntityPixelmon['Diglett'/6341, l='MpServer', x=307.50, y=49.00, z=49.50], EntityPixelmon['Gastly'/6342, l='MpServer', x=334.50, y=47.00, z=89.50], EntityPlayerSP['Tealn'/6093, l='MpServer', x=361.81, y=68.41, z=62.02], EntityPixelmon['Scatterbug'/6284, l='MpServer', x=323.50, y=63.00, z=30.76], EntityPixelmon['Taillow'/6285, l='MpServer', x=334.50, y=73.00, z=28.50], EntityPixelmon['Magikarp'/6358, l='MpServer', x=303.35, y=61.00, z=16.16], EntityPixelmon['Goldeen'/6359, l='MpServer', x=303.35, y=60.00, z=8.35], EntityPixelmon['Magikarp'/6298, l='MpServer', x=348.19, y=58.60, z=64.19], EntityPixelmon['Zigzagoon'/6362, l='MpServer', x=292.50, y=73.00, z=72.50], EntityPixelmon['Rattata'/6299, l='MpServer', x=353.30, y=66.00, z=37.82], EntityPixelmon['Pidove'/6363, l='MpServer', x=295.53, y=64.00, z=62.37], EntityPixelmon['Zigzagoon'/6300, l='MpServer', x=363.48, y=64.00, z=85.28], EntityPixelmon['Meowth'/6364, l='MpServer', x=348.50, y=63.00, z=102.50], EntityPixelmon['Electrike'/6301, l='MpServer', x=365.53, y=75.00, z=94.86], EntityPixelmon['Oricorio'/6302, l='MpServer', x=300.75, y=73.00, z=16.32], EntityPixelmon['Rattata'/6367, l='MpServer', x=346.50, y=74.00, z=115.50], EntityPixelmon['Surskit'/6304, l='MpServer', x=300.68, y=62.38, z=77.91], EntityPixelmon['Roggenrola'/6368, l='MpServer', x=372.50, y=52.00, z=22.50], EntityPixelmon['Magikarp'/6306, l='MpServer', x=372.65, y=58.45, z=44.65], EntityOtherPlayerMP['littfamm'/5869, l='MpServer', x=334.16, y=214.00, z=227.94], EntityPixelmon['Ledyba'/6308, l='MpServer', x=350.72, y=69.00, z=16.14], EntityPixelmon['Sentret'/6245, l='MpServer', x=332.80, y=64.00, z=60.41], EntityPixelmon['Roggenrola'/6309, l='MpServer', x=344.50, y=44.00, z=17.50], EntityPixelmon['Pidove'/6246, l='MpServer', x=335.53, y=69.69, z=35.14], EntityPixelmon['Pidove'/6310, l='MpServer', x=309.02, y=78.00, z=46.84], EntityOtherPlayerMP['bannjo_'/529, l='MpServer', x=323.95, y=81.37, z=249.16], EntityPixelmon['Diglett'/6311, l='MpServer', x=328.50, y=44.00, z=56.50], EntityPixelmon['Pidove'/6312, l='MpServer', x=356.50, y=73.00, z=26.50], EntityPixelmon['Rattata'/6313, l='MpServer', x=366.36, y=64.00, z=12.86], EntityPixelmon['Miltank'/6314, l='MpServer', x=362.50, y=66.00, z=69.50], EntityPixelmon['Voltorb'/6315, l='MpServer', x=336.85, y=62.17, z=85.85], EntityPixelmon['Magikarp'/6316, l='MpServer', x=343.51, y=58.50, z=73.51], EntityPixelmon['Rattata'/6253, l='MpServer', x=281.32, y=63.00, z=48.52], EntityPixelmon['Ponyta'/6317, l='MpServer', x=371.79, y=64.00, z=76.89], EntityPixelmon['Metapod'/6318, l='MpServer', x=394.25, y=64.00, z=81.51], EntityPixelmon['Oricorio'/6319, l='MpServer', x=367.65, y=74.00, z=55.20], EntityPixelmon['Oricorio'/6320, l='MpServer', x=315.24, y=81.00, z=110.36], EntityPixelmon['Scatterbug'/6321, l='MpServer', x=286.87, y=82.00, z=41.89], EntityPixelmon['Oricorio'/6322, l='MpServer', x=342.68, y=81.00, z=64.66], EntityPixelmon['Roggenrola'/6323, l='MpServer', x=315.50, y=49.00, z=23.50], EntityWormhole['entity.Wormhole.name'/6325, l='MpServer', x=298.50, y=75.00, z=125.50], EntityPixelmon['Zigzagoon'/6327, l='MpServer', x=329.50, y=73.00, z=115.50], EntityPixelmon['Snubbull'/6328, l='MpServer', x=324.50, y=63.00, z=103.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 650836552 bytes (620 MB) / 3517972480 bytes (3355 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6912m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                | Signature                                |
	|:------ |:-------------------- |:------------------------ |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                         | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core    | 1.12.2-1.0               | minecraft.jar                         | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar             | None                                     |
	| LCHIJA | appliedenergistics2  | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar  | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | blockcraftery        | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar        | None                                     |
	| LCHIJA | cfm                  | 6.3.0                    | cfm-6.3.0-mc1.12.2.jar                | None                                     |
	| LCHIJA | jei                  | 4.15.0.296               | jei_1.12.2-4.15.0.296.jar             | None                                     |
	| LCHIJA | chisel               | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar          | None                                     |
	| LCHIJA | chiselsandbits       | 14.33                    | chiselsandbits-14.33.jar              | None                                     |
	| LCHIJA | customnpcs           | 1.12                     | Custom-NPCs-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | extrabitmanipulation | 1.12.2-3.4.1             | ExtraBitManipulation-1.12.2-3.4.1.jar | None                                     |
	| LCHIJA | extrautils2          | 1.0                      | extrautils2-1.12-1.9.9.jar            | None                                     |
	| LCHIJA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar           | None                                     |
	| LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar     | None                                     |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar       | None                                     |
	| LCHIJA | oreexcavation        | 1.4.140                  | OreExcavation-1.4.140.jar             | None                                     |
	| LCHIJA | pixelmon             | 8.0.2                    | Pixelmon-1.12.2-8.0.2-universal.jar   | None                                     |
	| LCHIJA | realdrops            | 1.2.14                   | RealisticItemDrops-1.2.14.jar         | None                                     |
	| LCHIJA | xaerominimap         | 20.15.2                  | Xaeros_Minimap_20.15.2_Forge_1.12.jar | None                                     |
	| LCHIJA | lunatriuscore        | 1.2.0.42                 | {}{}LunatriusCore-1.12.2.jar          | None                                     |
	| LCHIJA | schematica           | 1.8.0.169                | {}{}Schematica-Mod-1.12.2.jar         | None                                     |
	| LCHIJA | mysticallib          | 1.12.2-1.7.0             | mysticallib-1.12.2-1.7.0.jar          | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
XaeroMinimapPlugin (Xaeros_Minimap_20.15.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.48' Renderer: 'GeForce RTX 2080 SUPER/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce RTX 2080 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by Tealn** [comment]
Lmao, read some other issue posts, turned off render regions, its working now
