### ISSUE TITLE
MC is crashing with schematica working

### ISSUE THREAD

**Issue by ri4ard55** [Lunatrius/Schematica#512]
I've tried to build buildings with schematica several times
Firstly i thought that "Printer" function is the reason why MC is crashing, but then I've tried to build with "Printer" turned off, but crashing still remains.

Here is two crash reports
first is when i used printer
second is when i didn't use it

1)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 8/19/20 11:56 AM
Description: Unexpected error

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Unknown Source)
	at java.nio.DirectIntBufferU.put(Unknown Source)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:310)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_183_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1952)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.nextPutIndex(Unknown Source)
	at java.nio.DirectIntBufferU.put(Unknown Source)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:310)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_183_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1952)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['necrominer'/114242, l='MpServer', x=2474.59, y=67.71, z=-6291.54]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-612,207,-3654), Chunk: (at 12,12,10 in -39,-229; contains blocks -624,0,-3664 to -609,255,-3649), Region: (-2,-8; contains chunks -64,-256 to -33,-225, blocks -1024,0,-4096 to -513,255,-3585)
	Level time: 10222743 game time, 12252496 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 9 total; [EntityZombie['Зомби'/116865, l='MpServer', x=2517.50, y=26.00, z=-6326.50], EntityZombie['Зомби'/116483, l='MpServer', x=2473.50, y=35.00, z=-6268.50], EntityPlayerSP['necrominer'/114242, l='MpServer', x=2474.59, y=67.71, z=-6291.54], EntitySheep['Овца'/114269, l='MpServer', x=2519.61, y=64.00, z=-6270.77], EntityCreeper['Крипер'/116832, l='MpServer', x=2498.50, y=12.00, z=-6274.50], EntityCow['Корова'/114277, l='MpServer', x=2437.78, y=64.00, z=-6251.51], EntityZombie['Зомби'/116712, l='MpServer', x=2518.50, y=38.00, z=-6278.50], EntityCreeper['Крипер'/116651, l='MpServer', x=2454.16, y=39.00, z=-6312.53], EntitySkeleton['Скелет'/116667, l='MpServer', x=2522.50, y=10.00, z=-6310.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 648000936 bytes (617 MB) / 2063323136 bytes (1967 MB) up to 3526623232 bytes (3363 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx3376M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F4 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version         | Source                                          | Signature                                |
	|:------ |:-------------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2          | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                        | 9.42            | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                        | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cocricotmod                | 1.0             | cocricotMOD-for-1.12.2-v0.3 (1).jar             | None                                     |
	| LCHIJA | dynmap                     | 3.0.1-343       | Dynmap-3.0.1-forge-1.12.2.jar                   | None                                     |
	| LCHIJA | flansmod                   | 5.5.2           | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | flansmodapocalypse         | 1.0             | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | cfm                        | 6.3.0           | furniture_6.3.0_1.12.2.jar                      | None                                     |
	| LCHIJA | ic2                        | 2.8.220-ex112   | industrialcraft-2-2.8.220-ex112 (1).jar         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | lunatriuscore              | 1.2.0.42        | LunatriusCore_1.12.2_1.2.0.42_universal (1).jar | None                                     |
	| LCHIJA | minetraps                  | 1.0.4           | minetraps-1.12.2-v.1.0.4 (3).jar                | None                                     |
	| LCHIJA | harvestcraft               | 1.12.2zb        | pamsharvestcraft1.12.2zg (1).jar                | None                                     |
	| LCHIJA | row                        | 1.12.2-2006-1o1 | railsofwar-1.12.2-2006-1o1 (1).jar              | None                                     |
	| LCHIJA | schematica                 | 1.8.0.169       | Schematica_1.12.2_1.8.0.169_universal (1).jar   | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4             | tlskincape_1.12.2-1.4.jar                       | None                                     |

	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9600 GT/PCIe/SSE2'
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce 9600 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8500 @ 3.16GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce 9600 GT/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

2)
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 8/19/20 12:10 PM
Description: Unexpected error

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Unknown Source)
	at java.nio.DirectIntBufferU.put(Unknown Source)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:310)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_183_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1952)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.nextPutIndex(Unknown Source)
	at java.nio.DirectIntBufferU.put(Unknown Source)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:310)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_183_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1952)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['necrominer'/118328, l='MpServer', x=2509.11, y=66.30, z=-6284.23]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-612,207,-3654), Chunk: (at 12,12,10 in -39,-229; contains blocks -624,0,-3664 to -609,255,-3649), Region: (-2,-8; contains chunks -64,-256 to -33,-225, blocks -1024,0,-4096 to -513,255,-3585)
	Level time: 10238717 game time, 12268470 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 23 total; [EntitySkeleton['Скелет'/119435, l='MpServer', x=2532.50, y=42.00, z=-6273.50], EntityCreeper['Крипер'/119434, l='MpServer', x=2533.50, y=42.00, z=-6271.50], EntityPlayerSP['necrominer'/118328, l='MpServer', x=2509.11, y=66.30, z=-6284.23], EntityZombie['Зомби'/119567, l='MpServer', x=2518.79, y=23.00, z=-6269.53], EntityEnderman['Эндермен'/119568, l='MpServer', x=2521.50, y=24.00, z=-6318.50], EntityZombie['Зомби'/118701, l='MpServer', x=2491.47, y=48.00, z=-6276.19], EntitySkeleton['Скелет'/119471, l='MpServer', x=2512.50, y=18.00, z=-6259.50], EntitySpider['Паук'/119481, l='MpServer', x=2542.50, y=17.00, z=-6326.50], EntityZombie['Зомби'/119362, l='MpServer', x=2526.50, y=45.00, z=-6268.50], EntitySkeleton['Скелет'/119490, l='MpServer', x=2544.71, y=38.00, z=-6266.50], EntitySkeleton['Скелет'/119492, l='MpServer', x=2510.50, y=7.00, z=-6284.50], EntityCreeper['Крипер'/119505, l='MpServer', x=2512.57, y=34.00, z=-6288.20], EntityCreeper['Крипер'/119252, l='MpServer', x=2505.85, y=32.00, z=-6291.48], EntityZombie['Зомби'/119254, l='MpServer', x=2466.50, y=46.00, z=-6303.50], EntitySpider['Паук'/119384, l='MpServer', x=2491.50, y=6.00, z=-6315.50], EntitySheep['Овца'/118369, l='MpServer', x=2536.69, y=64.00, z=-6258.21], EntitySheep['Овца'/118368, l='MpServer', x=2527.38, y=64.00, z=-6271.19], EntityPig['Свинья'/118377, l='MpServer', x=2546.24, y=64.00, z=-6269.68], EntityCreeper['Крипер'/119145, l='MpServer', x=2527.43, y=23.00, z=-6330.20], EntityZombie['Зомби'/119144, l='MpServer', x=2526.50, y=22.00, z=-6316.50], EntitySpider['Паук'/119530, l='MpServer', x=2498.35, y=6.00, z=-6314.40], EntitySkeleton['Скелет'/119537, l='MpServer', x=2506.50, y=21.00, z=-6276.50], EntityCreeper['Крипер'/119541, l='MpServer', x=2521.68, y=40.00, z=-6280.73]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 624340824 bytes (595 MB) / 1831952384 bytes (1747 MB) up to 3526623232 bytes (3363 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx3376M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F4 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version         | Source                                          | Signature                                |
	|:------ |:------------------ |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2          | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                | 9.42            | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cocricotmod        | 1.0             | cocricotMOD-for-1.12.2-v0.3 (1).jar             | None                                     |
	| LCHIJA | dynmap             | 3.0.1-343       | Dynmap-3.0.1-forge-1.12.2.jar                   | None                                     |
	| LCHIJA | flansmod           | 5.5.2           | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | flansmodapocalypse | 1.0             | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | cfm                | 6.3.0           | furniture_6.3.0_1.12.2.jar                      | None                                     |
	| LCHIJA | ic2                | 2.8.220-ex112   | industrialcraft-2-2.8.220-ex112 (1).jar         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | lunatriuscore      | 1.2.0.42        | LunatriusCore_1.12.2_1.2.0.42_universal (1).jar | None                                     |
	| LCHIJA | minetraps          | 1.0.4           | minetraps-1.12.2-v.1.0.4 (3).jar                | None                                     |
	| LCHIJA | harvestcraft       | 1.12.2zb        | pamsharvestcraft1.12.2zg (1).jar                | None                                     |
	| LCHIJA | row                | 1.12.2-2006-1o1 | railsofwar-1.12.2-2006-1o1 (1).jar              | None                                     |
	| LCHIJA | schematica         | 1.8.0.169       | Schematica_1.12.2_1.8.0.169_universal (1).jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9600 GT/PCIe/SSE2'
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce 9600 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8500 @ 3.16GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce 9600 GT/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by Timeless121** [comment]
f
