### ISSUE TITLE
Game crash ~10 seconds after loading a schematic (1.8.9 forge)

### ISSUE THREAD

**Issue by iQuabbagain** [Lunatrius/Schematica#527]
Hey there, whenever i load a schematic it will have me load it and then after 10 seconds to a minute my game fill freeze and shut down giving me this crash code:
The game crashed whilst unexpected error
Error: java.nio.BufferOverflowException
Exit Code: -1

Game version: 1.8.9
Forge version: 1.8.9-forge1.8.9-11.15.1.3218-1.8.9
Schematica version: [Minecraft-INSIDE.com]schematica-mod-1.8.9
Lunatriuscore version: Lunatriuscore-1.8.9-1.1.32-universal

The crash report it generates is the following:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  FMLLoadingPlugin (Skypixel-0.0.6.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.4-for-MC-1.8.9.jar)
  CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 12/15/20 4:19 PM
Description: Unexpected error

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:310)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:748)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:739)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:321)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:247)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:216)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_87_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:123)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:532)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1921)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1372)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:310)
	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:54)
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:748)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:739)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:321)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:247)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:216)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_87_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:123)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:532)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1921)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)

-- Affected level --
Details:
	Level name: MpServer
	All players: 7 total; [EntityPlayerSP['iQuabb'/3137247, l='MpServer', x=108.35, y=139.00, z=71.87], EntityOtherPlayerMP['EmilioIsToast'/3120044, l='MpServer', x=-2.34, y=67.00, z=-1.94], EntityOtherPlayerMP['Fenixkot'/3134426, l='MpServer', x=-8.72, y=67.00, z=-0.13], EntityOtherPlayerMP['HarveylMT'/3135366, l='MpServer', x=-24.63, y=70.00, z=-0.69], EntityOtherPlayerMP['IbimsderPrimus'/3137604, l='MpServer', x=-24.72, y=70.03, z=-0.16], EntityOtherPlayerMP['hugomau'/3119653, l='MpServer', x=42.89, y=131.36, z=5.61], EntityOtherPlayerMP['Galiro_'/3129139, l='MpServer', x=-6.13, y=67.00, z=-1.56]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -26.00,70.00,-1.00 - World: (-26,70,-1), Chunk: (at 6,4,15 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 586300440 game time, 276250 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 102 total; [EntityPlayerSP['iQuabb'/3137247, l='MpServer', x=108.35, y=139.00, z=71.87], EntityOtherPlayerMP['Gengarisnub'/3134663, l='MpServer', x=-28.29, y=73.01, z=-6.98], EntityOtherPlayerMP['Lordofbanana'/3136035, l='MpServer', x=-22.44, y=70.03, z=0.53], EntityOtherPlayerMP['hugomau'/3119653, l='MpServer', x=42.89, y=131.36, z=5.61], EntityOtherPlayerMP['XxMash'/2706643, l='MpServer', x=-11.66, y=67.00, z=2.38], EntityOtherPlayerMP['1kristiank'/3128196, l='MpServer', x=-6.00, y=67.00, z=7.75], EntityOtherPlayerMP['BRAUN456'/3129589, l='MpServer', x=-10.84, y=67.00, z=5.56], EntityOtherPlayerMP['JohnyIsGod'/3136698, l='MpServer', x=-3.25, y=67.00, z=5.44], EntityOtherPlayerMP['diuslolboychel'/3130093, l='MpServer', x=-21.09, y=70.00, z=-5.28], EntityOtherPlayerMP['mel0diqx'/3131377, l='MpServer', x=-23.84, y=70.00, z=-0.63], EntityOtherPlayerMP['kjaersg'/3131477, l='MpServer', x=-22.88, y=70.00, z=2.69], EntityOtherPlayerMP['Jenocchio'/3134062, l='MpServer', x=2.25, y=67.06, z=-2.50], EntityOtherPlayerMP['HarveylMT'/3135366, l='MpServer', x=-24.63, y=70.00, z=-0.69], EntityOtherPlayerMP['steven7192073'/3136692, l='MpServer', x=-29.31, y=71.00, z=0.53], EntityOtherPlayerMP['pingverschil100'/3136718, l='MpServer', x=-29.75, y=78.50, z=-65.50], EntityOtherPlayerMP['SinisterOatMeal'/3137228, l='MpServer', x=-17.09, y=67.97, z=1.22], EntityOtherPlayerMP['10y068s1w3'/58, l='MpServer', x=-8.50, y=67.00, z=-4.50], EntityOtherPlayerMP['nihal2379'/3128356, l='MpServer', x=-1.56, y=67.00, z=-9.28], EntityOtherPlayerMP['Galiro_'/3129139, l='MpServer', x=-6.09, y=67.00, z=-1.53], EntityOtherPlayerMP['Fenixkot'/3134426, l='MpServer', x=-8.72, y=67.00, z=-0.13], EntityOtherPlayerMP['MicAna'/3134520, l='MpServer', x=0.69, y=68.00, z=-5.03], EntityOtherPlayerMP['DCDOG'/3134526, l='MpServer', x=1.78, y=69.94, z=-8.31], EntityOtherPlayerMP['SuperMohawkT'/3135791, l='MpServer', x=-0.72, y=67.00, z=-5.06], EntityOtherPlayerMP['eckseswastaken'/3136221, l='MpServer', x=-2.13, y=67.00, z=-8.69], EntityOtherPlayerMP['iiGeorges'/3136694, l='MpServer', x=2.26, y=67.42, z=-2.27], EntityOtherPlayerMP['VegaBamiSchijf'/3136853, l='MpServer', x=-1.09, y=67.06, z=3.91], EntityOtherPlayerMP['theyqb'/3136711, l='MpServer', x=-0.28, y=70.00, z=-26.78], EntityOtherPlayerMP['u3xb1ji2nh'/8, l='MpServer', x=3.50, y=68.00, z=-2.50], EntityOtherPlayerMP['ofen49114a'/10, l='MpServer', x=-0.50, y=68.00, z=-8.50], EntityOtherPlayerMP['wy465y0427'/11, l='MpServer', x=1.50, y=68.00, z=-5.50], EntityOtherPlayerMP['fugass'/3127446, l='MpServer', x=9.06, y=67.06, z=0.72], EntityOtherPlayerMP['199191s225'/9, l='MpServer', x=3.50, y=68.00, z=3.50], EntityOtherPlayerMP['421y653yoh'/62, l='MpServer', x=13.50, y=69.00, z=17.50], EntityOtherPlayerMP['taevfx'/3133063, l='MpServer', x=6.66, y=75.63, z=21.91], EntityOtherPlayerMP['Jumilla_'/3137583, l='MpServer', x=-4.48, y=70.00, z=-24.39], EntityOtherPlayerMP['BLUEISQT'/3131380, l='MpServer', x=-11.91, y=69.00, z=-20.03], EntityOtherPlayerMP['whereispottah'/3134671, l='MpServer', x=-24.59, y=73.00, z=-41.53], EntityOtherPlayerMP['hugomau'/3119653, l='MpServer', x=20.63, y=91.88, z=7.94], EntityOtherPlayerMP['rkdtmdwls12'/3134157, l='MpServer', x=-38.51, y=70.45, z=59.57], EntityOtherPlayerMP['Nussmandembele'/3126574, l='MpServer', x=-77.00, y=97.00, z=-2.03], EntityPainting['Painting'/176, l='MpServer', x=-67.97, y=97.50, z=-58.50], EntityOtherPlayerMP['DannyRWC'/3134628, l='MpServer', x=-47.80, y=87.01, z=29.27], EntityOtherPlayerMP['DanLocker120'/3096763, l='MpServer', x=-26.13, y=71.00, z=-29.97], EntityOtherPlayerMP['Radiul'/3121091, l='MpServer', x=-23.25, y=70.00, z=-21.84], EntityOtherPlayerMP['v65x129e30'/2, l='MpServer', x=3.50, y=67.00, z=-14.50], EntityOtherPlayerMP['9v867dps36'/3, l='MpServer', x=10.50, y=67.00, z=0.50], EntityOtherPlayerMP['s1n5765nt3'/4, l='MpServer', x=1.50, y=68.00, z=6.50], EntityOtherPlayerMP['9r0a03312v'/6, l='MpServer', x=-0.50, y=68.00, z=9.50], EntityWither['§a§lHOLIDAY SALE - UP TO 85% OFF!'/-1234, l='MpServer', x=105.27, y=116.59, z=96.09], EntityOtherPlayerMP['TFJuice'/3137581, l='MpServer', x=-22.97, y=70.03, z=0.84], EntityOtherPlayerMP['Olifry'/3135785, l='MpServer', x=1.34, y=69.91, z=0.56], EntityOtherPlayerMP['kallihanni1234'/3135501, l='MpServer', x=-16.25, y=69.00, z=-22.94], EntityOtherPlayerMP['EmilioIsToast'/3120044, l='MpServer', x=-2.34, y=67.00, z=-1.94], EntityOtherPlayerMP['Kiritto'/3137586, l='MpServer', x=-2.23, y=67.30, z=-8.69], EntityOtherPlayerMP['HIGDON10'/3137588, l='MpServer', x=-32.06, y=72.00, z=5.69], EntityPainting['Painting'/1, l='MpServer', x=9.50, y=69.50, z=-5.97], EntityOtherPlayerMP['remikolac'/3137593, l='MpServer', x=-1.72, y=67.00, z=-7.84], EntityOtherPlayerMP['maya286'/3137598, l='MpServer', x=-20.53, y=69.00, z=1.38], EntityOtherPlayerMP['IbimsderPrimus'/3137604, l='MpServer', x=-24.72, y=70.03, z=-0.16], EntityOtherPlayerMP['Cynotic'/3137606, l='MpServer', x=-22.03, y=69.97, z=4.56], EntityOtherPlayerMP['theyqb'/3136711, l='MpServer', x=-3.23, y=71.41, z=-23.14], EntityOtherPlayerMP['DCDOG'/3134526, l='MpServer', x=3.59, y=67.00, z=-1.06], EntityOtherPlayerMP['GodOf_Thunder'/3137704, l='MpServer', x=-25.16, y=69.97, z=1.72], EntityOtherPlayerMP['ShadowMaster0401'/3137798, l='MpServer', x=-25.09, y=70.03, z=-0.72], EntityOtherPlayerMP['Slowgaleo'/3137800, l='MpServer', x=-23.97, y=70.03, z=0.78], EntityOtherPlayerMP['Nussmandembele'/3126574, l='MpServer', x=-75.31, y=96.53, z=-5.69], EntityOtherPlayerMP['199191s225'/9, l='MpServer', x=3.50, y=68.00, z=3.50], EntityOtherPlayerMP['DM_Hero'/3137569, l='MpServer', x=-23.06, y=70.03, z=1.59], EntityOtherPlayerMP['EmilioIsToast'/3120044, l='MpServer', x=75.16, y=74.56, z=34.94], EntityArmorStand['Armor Stand'/3138431, l='MpServer', x=49.84, y=117.44, z=43.94], EntityArmorStand['Armor Stand'/3138430, l='MpServer', x=49.84, y=117.78, z=43.94], EntityOtherPlayerMP['1kristiank'/3128196, l='MpServer', x=-5.88, y=67.00, z=7.52], EntityArmorStand['Armor Stand'/3138429, l='MpServer', x=49.84, y=118.09, z=43.94], EntityArmorStand['Armor Stand'/3138428, l='MpServer', x=49.84, y=119.31, z=43.94], EntityOtherPlayerMP['Magiccat'/3134852, l='MpServer', x=-2.88, y=67.00, z=9.22], EntityArmorStand['Armor Stand'/3138427, l='MpServer', x=45.59, y=116.44, z=44.31], EntityOtherPlayerMP['HIGDON10'/3137588, l='MpServer', x=-19.88, y=72.00, z=8.19], EntityArmorStand['Armor Stand'/3138426, l='MpServer', x=49.38, y=116.13, z=44.31], EntityArmorStand['Armor Stand'/3138425, l='MpServer', x=49.38, y=116.44, z=44.31], EntityOtherPlayerMP['XxMash'/2706643, l='MpServer', x=-11.69, y=67.00, z=2.34], EntityOtherPlayerMP['ilyot'/3137990, l='MpServer', x=-13.13, y=68.08, z=4.10], EntityArmorStand['Armor Stand'/3138421, l='MpServer', x=47.50, y=118.38, z=41.50], EntityPainting['Painting'/1, l='MpServer', x=9.50, y=69.50, z=-5.97], EntityOtherPlayerMP['fugass'/3127446, l='MpServer', x=9.06, y=67.06, z=0.72], EntityOtherPlayerMP['hugomau'/3119653, l='MpServer', x=42.89, y=131.36, z=5.61], EntityOtherPlayerMP['u3xb1ji2nh'/8, l='MpServer', x=3.50, y=68.00, z=-2.50], EntityOtherPlayerMP['ofen49114a'/10, l='MpServer', x=-0.50, y=68.00, z=-8.50], EntityOtherPlayerMP['wy465y0427'/11, l='MpServer', x=1.50, y=68.00, z=-5.50], EntityOtherPlayerMP['Galiro_'/3129139, l='MpServer', x=-6.13, y=67.00, z=-1.56], EntityOtherPlayerMP['maya286'/3137598, l='MpServer', x=-20.56, y=69.00, z=1.34], EntityOtherPlayerMP['maya286'/3137598, l='MpServer', x=47.50, y=119.50, z=41.50], EntityOtherPlayerMP['IlyVools'/3137572, l='MpServer', x=-24.50, y=70.03, z=0.03], EntityOtherPlayerMP['SmellyViking647'/3137574, l='MpServer', x=10.31, y=68.75, z=-13.06], EntityArmorStand['Armor Stand'/3138439, l='MpServer', x=50.84, y=117.31, z=40.91], EntityArmorStand['Armor Stand'/3138438, l='MpServer', x=44.13, y=117.31, z=40.91], EntityArmorStand['Armor Stand'/3138437, l='MpServer', x=45.13, y=117.47, z=43.94], EntityArmorStand['Armor Stand'/3138436, l='MpServer', x=45.13, y=117.81, z=43.94], EntityArmorStand['Armor Stand'/3138435, l='MpServer', x=45.13, y=119.00, z=43.94], EntityArmorStand['Armor Stand'/3138434, l='MpServer', x=47.47, y=117.81, z=44.88], EntityArmorStand['Armor Stand'/3138433, l='MpServer', x=47.47, y=118.16, z=44.88], EntityArmorStand['Armor Stand'/3138432, l='MpServer', x=47.47, y=119.34, z=44.88], EntityOtherPlayerMP['Thirddammaccount'/3137576, l='MpServer', x=-15.81, y=67.50, z=-0.84]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ct.js modules: [Module{name=DeepProxy,folder=.\config\ChatTriggers\modules\DeepProxy,metadata=ModuleMetadata(name=DeepProxy, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=null, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=DungeonUtilities,folder=.\config\ChatTriggers\modules\DungeonUtilities,metadata=ModuleMetadata(name=DungeonUtilities, version=0.9.9, entry=loader.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager, PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=Elementa,folder=.\config\ChatTriggers\modules\Elementa,metadata=ModuleMetadata(name=Elementa, version=1.4.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Gui Library, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=ExperimentationTable,folder=.\config\ChatTriggers\modules\ExperimentationTable,metadata=ModuleMetadata(name=ExperimentationTable, version=1.1.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Solves the Experimentation Table puzzles for you., requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=FishingUtilities,folder=.\config\ChatTriggers\modules\FishingUtilities,metadata=ModuleMetadata(name=FishingUtilities, version=1.4.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager], helpMessage=null, ignored=null, isRequired=false)}, Module{name=HoeUtilities,folder=.\config\ChatTriggers\modules\HoeUtilities,metadata=ModuleMetadata(name=HoeUtilities, version=3.0.1, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Provides various utility features to SkyBlock hoes, requires=[SettingsManager, requestV2, PromiseV2], helpMessage=&cType &a&l/hoeutils &r&cto open settings., ignored=null, isRequired=false)}, Module{name=PersistentData,folder=.\config\ChatTriggers\modules\PersistentData,metadata=ModuleMetadata(name=PersistentData, version=1.1.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily store data that persist between game and ct reloads, requires=[DeepProxy], helpMessage=null, ignored=null, isRequired=false)}, Module{name=Promise,folder=.\config\ChatTriggers\modules\Promise,metadata=ModuleMetadata(name=Promise, version=1.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Promise polyfill for 1.0.0, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=PromiseV2,folder=.\config\ChatTriggers\modules\PromiseV2,metadata=ModuleMetadata(name=PromiseV2, version=1.0.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=McPqndq, description=Promise polyfill, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=ReParty,folder=.\config\ChatTriggers\modules\ReParty,metadata=ModuleMetadata(name=ReParty, version=1.0.0, entry=main.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=ComPewPer, description=Disbands and then reparties. Useful for skipping dungeon cooldowns. /reparty, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=requestV2,folder=.\config\ChatTriggers\modules\requestV2,metadata=ModuleMetadata(name=requestV2, version=2.0.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson (uploaded by McPqndq), description=A nicer alternative to XMLHttpRequest with a promise-like API. See the README.md for a full api description. (PS from McPqndq: this module is a copy paste of Ecolsson's 'request' except using a different Promise polyfill.), requires=[PromiseV2], helpMessage=null, ignored=null, isRequired=false)}, Module{name=SettingsManager,folder=.\config\ChatTriggers\modules\SettingsManager,metadata=ModuleMetadata(name=SettingsManager, version=1.2.1, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Autogenerates a settings file and gui based on the object created and registers. Example usage can be found in UseExample.js, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=SkyblockCommands,folder=.\config\ChatTriggers\modules\SkyblockCommands,metadata=ModuleMetadata(name=SkyblockCommands, version=1.8.4, entry=main.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Dolphin0xyz, description=&5&k&l00&r&3 Sky&2Block &6Commands &r&5&k&l00&r &3&l&k0&r&6&l&o1&3&l&o.&6&l&o8&3&l&o.&6&l&o4&r&3&l&k0&r&c&o by &r&4&oDolphin0xyz
&a&l&k0&r&3 Adds keybinds for most skyblock commands, fast travel warps and more in the vanilla controls menu. Use /sc for help and to use some features. &r&a&l&k0
&r&e&l&k0&r&2 If keys conflicts with other keys things may not work and things outside this moudule may break. &r&e&l&k0
&r&b&l&k0&r&d Contact me if you find bugs, need help, or have features to suggest. My discord name is Dolphin0xyz#7887 and you can also find me on twitter @Dolphin0xyz. &r&b&l&k0, requires=null, helpMessage=&e&m---------------&r &5&k&l00&r&3 Sky&2Block &6Commands &r&5&k&l00&r &e&m---------------
&r&eRun /sc to see the help guide!
&r&e&m-----------------------------------------------------, ignored=null, isRequired=false)}, Module{name=SkyblockStats,folder=.\config\ChatTriggers\modules\SkyblockStats,metadata=ModuleMetadata(name=SkyblockStats, version=1.1.1, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Shows stats that you are earning in Hypixel Skyblock. Pin stats that you want to keep track of by opening chat and hovering over the stat you want to pin, requires=[Elementa], helpMessage=null, ignored=null, isRequired=false)}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1203686392 bytes (1147 MB) / 1711276032 bytes (1632 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCHIJA	fullbright{1.2} [Fullbright] (1.8.9-Fullbright-v1.2.1.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJA	Schematica{1.7.7.143} [Schematica] ([Minecraft-INSIDE.com] schematica-mod-1.8.9.jar) 
	UCHIJA	ct.js{1.3.0} [ChatTriggers] (ctjs-1.3.0-1.8.9.jar) 
	UCHIJA	notenoughupdates{1.7.1-REL} [NotEnoughUpdates] (NotEnoughUpdates-1.7.2-REL.jar) 
	UCHIJA	text_overflow_scroll{1.3} [Scrollable Tooltips] (Scrollable Tooltips-1.3 (1.8.9).jar) 
	UCHIJA	skyblockaddons{1.5.4} [SkyBlock Addons] (SkyblockAddons-1.5.4-for-MC-1.8.9.jar) 
	UCHIJA	skypixel{0.0.6} [Skypixel] (Skypixel-0.0.6.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
FMLLoadingPlugin (Skypixel-0.0.6.jar)
  io.prplz.skypixel.asm.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.4-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics 
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by iQuabbagain** [comment]
This also occurs then i download the 1.8.9 version on the 1.7.7.143 universal on the lunatri.us website
