### ISSUE TITLE
Schematica causing crashes on startup

### ISSUE THREAD

**Issue by FighterJet16** [Lunatrius/Schematica#550]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GameSense (GameSense.v2.3.0.jar)
  MixinLoaderForge (creepy-salhack-2.08.1.jar)
  KDgB (Inertia Client 3.1.3 - 1.12.2.jar)
  LambdaMixinLoader (lambda-2.07.01.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/11/21 10:22 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.FontRenderer.redirect$drawCustomFontStringWithShadow$zcf000(FontRenderer.java:958)
	at net.minecraft.client.gui.FontRenderer.func_175063_a(FontRenderer.java:274)
	at net.minecraft.client.gui.Gui.func_73732_a(SourceFile:98)
	at net.minecraftforge.fml.client.GuiDupesFound.func_73863_a(GuiDupesFound.java:43)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.FontRenderer.redirect$drawCustomFontStringWithShadow$zcf000(FontRenderer.java:958)
	at net.minecraft.client.gui.FontRenderer.func_175063_a(FontRenderer.java:274)
	at net.minecraft.client.gui.Gui.func_73732_a(SourceFile:98)
	at net.minecraftforge.fml.client.GuiDupesFound.func_73863_a(GuiDupesFound.java:43)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiDupesFound
	Mouse location: Scaled: (656, 304). Absolute: (1313, 471)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 303573040 bytes (289 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 13 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                                        | Signature |
	|:----- |:-------------- |:------------ |:--------------------------------------------- |:--------- |
	|       | minecraft      | 1.12.2       | minecraft.jar                                 | None      |
	|       | mcp            | 9.42         | minecraft.jar                                 | None      |
	|       | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar                 | None      |
	|       | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar                 | None      |
	|       | craftstudioapi | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None      |
	|       | lunatriuscore  | 1.2.0.42     | creepy-salhack-2.08.1.jar                     | None      |
	|       | schematica     | 1.8.0.169    | creepy-salhack-2.08.1.jar                     | None      |
	|       | creepy-salhack | 2.8.1        | creepy-salhack-2.08.1.jar                     | None      |
	|       | gamesense      | v2.3.0       | GameSense.v2.3.0.jar                          | None      |
	|       | inertia        | 3.1.3        | Inertia Client 3.1.3 - 1.12.2.jar             | None      |
	|       | lambda         | 2.07.01      | lambda-2.07.01.jar                            | None      |
	|       | lunatriuscore  | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None      |
	|       | schematica     | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal (1).jar | None      |

	Loaded coremods (and transformers): 
GameSense (GameSense.v2.3.0.jar)
  
MixinLoaderForge (creepy-salhack-2.08.1.jar)
  
KDgB (Inertia Client 3.1.3 - 1.12.2.jar)
  
LambdaMixinLoader (lambda-2.07.01.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.51' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: enchantmentglint.zip, Faihtful128x128 1.12.2
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 1400 Quad-Core Processor

**Comment by omerien** [comment]
Did removing Schematica removed the crash ?
