### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by OreCruncher** [Lunatrius/Schematica#67]
I get the following exception spammed in my console log when sitting at the Minecraft main menu before loading a world.  Using Schematica-1.7.10-1.7.5.107-universal.

```
[06:58:58] [Client thread/ERROR] [Schematica/]: Something went wrong...
java.lang.NullPointerException
	at com.github.lunatrius.schematica.handler.QueueTickHandler.onClientTick(QueueTickHandler.java:32) [QueueTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_724_QueueTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2053) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by Lunatrius** [comment]
Do you have bspkrsCore installed?

**Comment by OreCruncher** [comment]
Yes, I do.  Noticed it as fixed - what version is the change going into?

**Comment by Lunatrius** [comment]
Build 108 (latest as of now) has the fix.
