### ISSUE TITLE
Printer, and material not working Crash report inside.

### ISSUE THREAD

**Issue by Sean1183** [Lunatrius/Schematica#95]
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 10/14/15 2:10 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.block.Block.getPickBlock(Lnet/minecraft/util/MovingObjectPosition;Lnet/minecraft/world/World;IIILnet/minecraft/entity/player/EntityPlayer;)Lnet/minecraft/item/ItemStack;
	at com.github.lunatrius.schematica.client.util.BlockToItemStack.getItemStack(BlockToItemStack.java:14)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.placeBlock(SchematicPrinter.java:169)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.print(SchematicPrinter.java:114)
	at com.github.lunatrius.schematica.handler.client.TickHandler.onClientTick(TickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_14_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.client.util.BlockToItemStack.getItemStack(BlockToItemStack.java:14)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.placeBlock(SchematicPrinter.java:169)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.print(SchematicPrinter.java:114)
	at com.github.lunatrius.schematica.handler.client.TickHandler.onClientTick(TickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_14_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['TheeSwagMasterJ'/35, l='MpServer', x=78.04, y=71.20, z=-462.93]]
	Chunk stats: MultiplayerChunkCache: 260, 260
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (364,64,-240), Chunk: (at 12,4,0 in 22,-15; contains blocks 352,0,-240 to 367,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 249268 game time, 237625 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 93 total; [EntityCreeper['Creeper'/516, l='MpServer', x=101.50, y=77.00, z=-436.50], EntityCreeper['Creeper'/1414, l='MpServer', x=69.50, y=31.00, z=-500.50], EntityCreeper['Creeper'/1032, l='MpServer', x=138.50, y=73.00, z=-462.72], EntitySpider['Spider'/1033, l='MpServer', x=151.50, y=71.00, z=-491.50], EntityZombie['Zombie'/1036, l='MpServer', x=148.78, y=69.00, z=-499.25], EntityBat['Bat'/655, l='MpServer', x=126.56, y=37.37, z=-488.25], EntityBat['Bat'/1295, l='MpServer', x=28.60, y=19.00, z=-532.26], EntityBat['Bat'/1423, l='MpServer', x=112.69, y=26.96, z=-410.25], EntityBat['Bat'/1296, l='MpServer', x=24.32, y=18.85, z=-541.44], EntityCreeper['Creeper'/1169, l='MpServer', x=153.50, y=14.00, z=-438.50], EntityCreeper['Creeper'/1170, l='MpServer', x=146.59, y=15.00, z=-435.00], EntityBat['Bat'/1426, l='MpServer', x=113.56, y=16.02, z=-525.25], EntityCreeper['Creeper'/1171, l='MpServer', x=154.50, y=14.00, z=-437.50], EntityBat['Bat'/535, l='MpServer', x=92.20, y=27.43, z=-434.31], EntityBat['Bat'/537, l='MpServer', x=60.29, y=28.68, z=-446.50], EntityItem['item.tile.mushroom'/1050, l='MpServer', x=35.88, y=19.13, z=-516.88], EntityZombie['Zombie'/1438, l='MpServer', x=65.50, y=19.00, z=-536.50], EntityZombie['Zombie'/544, l='MpServer', x=78.50, y=36.00, z=-463.94], EntityZombie['Zombie'/545, l='MpServer', x=78.94, y=36.00, z=-466.63], EntitySkeleton['Skeleton'/1185, l='MpServer', x=81.50, y=27.00, z=-531.50], EntitySquid['Squid'/546, l='MpServer', x=67.56, y=43.38, z=-459.74], EntitySkeleton['Skeleton'/1186, l='MpServer', x=80.50, y=27.00, z=-531.50], EntityCreeper['Creeper'/421, l='MpServer', x=143.50, y=76.00, z=-468.50], EntityCreeper['Creeper'/1576, l='MpServer', x=155.50, y=77.00, z=-437.50], EntityCreeper['Creeper'/1193, l='MpServer', x=74.91, y=33.00, z=-470.38], EntityCreeper['Creeper'/1577, l='MpServer', x=157.50, y=77.00, z=-433.50], EntityCreeper['Creeper'/1196, l='MpServer', x=59.50, y=29.00, z=-443.50], EntitySkeleton['Skeleton'/557, l='MpServer', x=81.13, y=26.00, z=-461.56], EntityCreeper['Creeper'/1197, l='MpServer', x=60.50, y=29.00, z=-440.50], EntitySkeleton['Skeleton'/1453, l='MpServer', x=115.94, y=29.00, z=-475.44], EntitySquid['Squid'/558, l='MpServer', x=71.21, y=45.54, z=-461.02], EntitySkeleton['Skeleton'/1454, l='MpServer', x=118.50, y=29.00, z=-473.50], EntitySquid['Squid'/559, l='MpServer', x=82.39, y=47.28, z=-454.45], EntitySkeleton['Skeleton'/1199, l='MpServer', x=117.13, y=16.00, z=-424.47], EntitySkeleton['Skeleton'/1455, l='MpServer', x=115.63, y=28.00, z=-481.00], EntitySquid['Squid'/560, l='MpServer', x=84.39, y=46.86, z=-445.05], EntitySquid['Squid'/563, l='MpServer', x=73.21, y=56.83, z=-442.44], EntityZombie['Zombie'/1459, l='MpServer', x=121.50, y=29.00, z=-474.50], EntityCreeper['Creeper'/1590, l='MpServer', x=108.31, y=34.00, z=-537.28], EntitySquid['Squid'/567, l='MpServer', x=70.73, y=47.91, z=-459.80], EntityCreeper['Creeper'/1591, l='MpServer', x=112.57, y=33.14, z=-537.50], EntitySquid['Squid'/568, l='MpServer', x=72.32, y=55.15, z=-467.91], EntityZombie['Zombie'/440, l='MpServer', x=118.50, y=70.00, z=-383.50], EntitySquid['Squid'/569, l='MpServer', x=56.45, y=60.06, z=-460.38], EntityZombie['Zombie'/1465, l='MpServer', x=147.53, y=13.00, z=-462.25], EntitySquid['Squid'/570, l='MpServer', x=78.84, y=58.34, z=-456.38], EntitySquid['Squid'/571, l='MpServer', x=77.66, y=60.15, z=-467.99], EntitySquid['Squid'/572, l='MpServer', x=64.24, y=59.69, z=-440.74], EntitySquid['Squid'/573, l='MpServer', x=73.02, y=49.33, z=-446.12], EntitySkeleton['Skeleton'/1597, l='MpServer', x=140.50, y=70.00, z=-513.50], EntitySquid['Squid'/574, l='MpServer', x=68.22, y=50.65, z=-447.19], EntitySquid['Squid'/575, l='MpServer', x=85.33, y=54.38, z=-448.37], EntityChicken['Chicken'/576, l='MpServer', x=69.56, y=62.34, z=-400.41], EntitySkeleton['Skeleton'/67, l='MpServer', x=140.16, y=73.00, z=-469.53], EntityZombie['Zombie'/1606, l='MpServer', x=156.41, y=16.00, z=-463.06], EntitySkeleton['Skeleton'/840, l='MpServer', x=71.06, y=15.00, z=-448.50], EntitySheep['Sheep'/329, l='MpServer', x=109.97, y=64.00, z=-400.03], EntitySkeleton['Skeleton'/74, l='MpServer', x=133.50, y=13.00, z=-458.50], EntityPig['Pig'/330, l='MpServer', x=105.31, y=68.00, z=-399.53], EntityBat['Bat'/1482, l='MpServer', x=131.58, y=27.87, z=-540.25], EntityPig['Pig'/331, l='MpServer', x=110.03, y=67.00, z=-410.06], EntityBat['Bat'/1483, l='MpServer', x=117.73, y=31.52, z=-536.45], EntitySheep['Sheep'/332, l='MpServer', x=109.91, y=66.00, z=-403.59], EntitySheep['Sheep'/333, l='MpServer', x=98.69, y=63.00, z=-396.44], EntityBat['Bat'/1485, l='MpServer', x=129.74, y=27.79, z=-537.58], EntityPig['Pig'/334, l='MpServer', x=108.91, y=63.00, z=-389.97], EntityCreeper['Creeper'/974, l='MpServer', x=80.50, y=65.00, z=-384.50], EntitySheep['Sheep'/335, l='MpServer', x=105.06, y=63.00, z=-395.06], EntityZombie['Zombie'/464, l='MpServer', x=111.09, y=71.00, z=-431.53], EntitySheep['Sheep'/336, l='MpServer', x=98.34, y=65.00, z=-400.50], EntitySpider['Spider'/976, l='MpServer', x=82.66, y=66.00, z=-427.66], EntitySquid['Squid'/80, l='MpServer', x=112.75, y=55.34, z=-519.06], EntityBat['Bat'/1488, l='MpServer', x=94.36, y=24.25, z=-443.99], EntityPig['Pig'/337, l='MpServer', x=101.88, y=67.00, z=-398.84], EntitySheep['Sheep'/338, l='MpServer', x=105.31, y=67.00, z=-398.31], EntityZombie['Zombie'/595, l='MpServer', x=74.50, y=27.00, z=-484.50], EntityCreeper['Creeper'/1620, l='MpServer', x=103.40, y=68.00, z=-489.49], EntityCreeper['Creeper'/1621, l='MpServer', x=107.50, y=69.00, z=-493.50], EntityCreeper['Creeper'/1622, l='MpServer', x=106.50, y=69.00, z=-495.50], EntityPig['Pig'/343, l='MpServer', x=85.97, y=67.00, z=-424.91], EntitySheep['Sheep'/344, l='MpServer', x=90.53, y=63.00, z=-397.63], EntityCreeper['Creeper'/1632, l='MpServer', x=148.50, y=73.00, z=-420.50], EntitySkeleton['Skeleton'/1122, l='MpServer', x=94.56, y=18.00, z=-412.06], EntitySkeleton['Skeleton'/744, l='MpServer', x=121.38, y=72.00, z=-417.06], EntitySpider['Spider'/625, l='MpServer', x=63.53, y=25.00, z=-470.28], EntitySkeleton['Skeleton'/1268, l='MpServer', x=132.50, y=25.00, z=-491.50], EntitySkeleton['Skeleton'/1269, l='MpServer', x=132.50, y=25.00, z=-490.50], EntitySpider['Spider'/1016, l='MpServer', x=86.50, y=28.00, z=-458.50], EntityZombie['Zombie'/1018, l='MpServer', x=83.50, y=28.00, z=-458.50], EntityCreeper['Creeper'/1146, l='MpServer', x=124.50, y=70.00, z=-400.50], EntityClientPlayerMP['TheeSwagMasterJ'/35, l='MpServer', x=78.04, y=71.20, z=-462.93], EntityCreeper['Creeper'/382, l='MpServer', x=139.50, y=12.00, z=-506.50], EntitySkeleton['Skeleton'/1150, l='MpServer', x=154.50, y=58.00, z=-495.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 139842720 bytes (133 MB) / 395042816 bytes (376 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Schematica{1.7.6.129} [Schematica] (Schematica-1.7.10-1.7.6.129-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8550G GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by Lunatrius** [comment]
Update to Forge 10.13.2.1234 or later.

**Comment by Lunatrius** [comment]
Closing this, if it still happens feel free to re-open with the crash log using a newer Forge version.
